### ISSUE TITLE
Stellar aberration 

### ISSUE THREAD

**Issue by denisGrBach** [IvS-KULeuven/PlatoSim3#1000]
To apply absolute stellar aberration, the provided orbit file is used. The average cadence in this file is about 20h and it seems that there is no interpolation with respect to the actual time step. This leads to jumping star positions each time a new obit file timestamp is reached.

**Comment by Dries-Seynaeve** [comment]
Hi Dennis, 

This should now be in the latest version of PlatoSim. 

Kind regards
Dries

**Comment by denisGrBach** [comment]
Hi Dries, 

we checked the new implementation with the orbit file as delivered with PlatoSim. Here produce imagettes with a cadence of one day and track the individual star movements on the CCDs. We got the following: 
![grafik](https://github.com/user-attachments/assets/fd80c1ac-0484-47cf-a5d8-7af8410a35b5)

Next we checked with a new orbit file with a much higher cadence (0.5h) and it looks as expected:
![grafik](https://github.com/user-attachments/assets/3e6b4fa7-3c41-49da-8e21-8fba6878c02c)

with the LoS stellar aberration correction of the S/C we get the expected output due to KDA. 
![grafik](https://github.com/user-attachments/assets/639183af-1871-416e-98c7-7fe9f25e02f3)

So it seems that either there is a problem in the linear interpolation or it is just not sufficient for the given orbit file with a cadence of about 20h.

**Comment by Dries-Seynaeve** [comment]
Hi, 

Yes, this might be a problem with the interpolation. Could you send me the other orbit file that you use, the star catalog  and script that you used to get these images. This can help me pin down where the problem might be. 

Kind regards 
Dries

**Comment by Dries-Seynaeve** [comment]
Hi Dennis, 

This problem caused some issues for Nich so I reverted these changes so he can run his simulations without issues. 
I create a new branch where we can still test this called **aberrationInterpolation**. 

Kind regards 
Dries

**Comment by PLATO-OS** [comment]
Hi Dries,

Denis asked me to provide the needed files to you since I performed the simulations. I'll attach the star catalog and the script we used. Regarding the orbit file, we need to check with TAS (who provided it to us) if we are allowed to redistribute it. I'll also attach the PlatoSim config we used and the PSF file. 

[aberrationSimulation.zip](https://github.com/user-attachments/files/16520725/aberrationSimulation.zip)

Example command line for our script:
`python paraPlatoFGS.py /path/to/inputfilefgs.yaml.ideal /path/to/PlatoSim3/inputfiles/RR_SBM_FGS_cat.txt /path/to/result_folder --aberration 31536000.0 --correction /path/to/PlatoSim3/inputfiles/new_orbit.txt`

Best regards
Johannes (DLR)

**Comment by PLATO-OS** [comment]
Please find attached the orbit file, generated from spacecraft velocity data from TAS:

[new_orbit.txt](https://github.com/user-attachments/files/16521285/new_orbit.txt)

**Comment by Dries-Seynaeve** [comment]
Hello, 

I believe I have found the issue. I have updated the branch, please let me know if this solves the issue for you. Than I will merge the branch. 

Kind regards 
Dries

**Comment by PLATO-OS** [comment]
Hi Dries,

I think there might be a problem in your current implementation for velocity vector v = (0,0,0).

I'll let you know if the normalization did the trick for the above problem hopefully tomorrow, we are currently evaluating the data.

Best regards
Johannes

**Comment by Dries-Seynaeve** [comment]
Hi Johnannes, 

Thanks for mentioning this, I made sure the code now checks for this. 

Kind regards
Dries

**Comment by PLATO-OS** [comment]
Hi Dries,

sorry for the super late reply, but I bring good news: The interpolation looks good now and produces the expected results, see screenshot below. Thanks!

![image (7)](https://github.com/user-attachments/assets/e44e5b51-5ea4-47f0-ab8d-57889e1ebebe)

Best regards
Johannes
