### ISSUE TITLE
Picsim error

### ISSUE THREAD

**Issue by AstroSaad** [IvS-KULeuven/PlatoSim3#1005]
I'm getting an error when trying to run picsim to generate a catalogue. I'm on the platosim develop branch.

```
Traceback (most recent call last):
  File "/Users/saadahmed/anaconda3/envs/platosim_develop/bin/picsim", line 1297, in <module>
    p.plotTargetsPIC()
  
File "/Users/saadahmed/anaconda3/envs/platosim_develop/bin/picsim", line 606, in plotTargetsPIC
    self.fig1, ax = pt.plotPlatoFOV(self.field, df.ra, df.dec, magStars=mag,
  
File "/Users/saadahmed/PlatoSim/PlatoSim3/python/platosim/plot.py", line 1314, in plotPlatoFOV
    if system == 'icrs':
  
File "/Users/saadahmed/anaconda3/envs/platosim_develop/lib/python3.9/site-packages/pandas/core/generic.py", line 1577, in __nonzero__
    raise ValueError(
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

**Comment by Dries-Seynaeve** [comment]
Hello Ahmed, 

Can you share the piece of code that you ran to get this error? 

Kind regards 
Dries

**Comment by AstroSaad** [comment]
It was one of the tutorial lines of code

`picsim --pic 150 P5 LOPN1 --dist 30 --dmag 8 --project Test1`

**Comment by nicholasjannsen** [comment]
Hi @AstroSaad, hm that seems strange because I'm on the latest version of the develop branch (git tag: 6759e0372b0a1e99959ec682ba02f482a404b197) and I can run the command above successfully:
```
(platonium) nicholas@messier:~/software/PlatoSim3/python/platosim/platonium$ python picsim.py --pic 150 P5 LOPN1 --dist 30 --dmag 8 --project test

PIC of Destiny
Loading stellar catalogues..

PIC targets
User catalog contains 150 stars of 1656 time series drawn from:
+--------+---------+-------------+
| N-cams | Targets | Time series |
+--------+---------+-------------+
|   6    |    65   |     390     |
|   12   |    62   |     744     |
|   18   |    5    |      90     |
|   24   |    18   |     432     |
+--------+---------+-------------+

PIC contaminants
Fetching contaminants within 30 arcsec and 8 mag from each target:
100%|██████████████████████████████████████████████████| 150/150 [00:00<00:00, 286.56it/s]                                                                                                                  

Prologue
Copying YAML configuration file
Saving all plots to /lhome/nicholas/software/workdir/test/input
Saving file /lhome/nicholas/software/workdir/test/input/starcat_P5_LOPN1_targets.ftr
Saving file /lhome/nicholas/software/workdir/test/input/starcat_P5_LOPN1_contaminants.ftr
Saving file /lhome/nicholas/software/workdir/test/input/cluster_starcat_P5_LOPN1.data

Total execution time: 0:00:10.881220 [hh:mm:ss]
``` 

Can you check which commit you are using? E.g. `git log` and  read of the long string and the date etc.?

**Comment by nicholasjannsen** [comment]
Note that you are probably using the the plotting flag `-p` because otherwise you would not see a crash in the function ` pt.plotPlatoFOV()`.

**Comment by AstroSaad** [comment]
From `git log`, this is the latest commit

```
commit 286bc64da0678c1c4e1a3ccfba50ff2808c5e445 (HEAD -> develop, origin/develop, origin/HEAD, master)
Merge: 164b98df e075f9cd
Author: Nicholas Jannsen <36379445+nicholasjannsen@users.noreply.github.com>
Date:   Mon Aug 5 20:01:53 2024 +0200

    Merge pull request #1003 from nicholasjannsen/develop
    
    Update of MOCKA project

```

**Comment by nicholasjannsen** [comment]
Hm this is very strange, I just checked out that exact brach, updated the source code of PlatoSim, and ran the command:
```
python picsim.py --pic 150 P5 LOPN1 --dist 30 --dmag 8 --project test -p
```
This works perfectly fine. 

I think the reason to why you face issues is because you are using an old "script" of `picsim.py`. Can you please try to run the true source code which is located here `$PLATO_PROJECT_HOME/python/platosim/platonium`? Whenever you update the PlatoSim develop branch you need to copy the PLATOnium script (that is `picsim.py`, `varsim.py`, `payload.py`, and `platonium.py`) into your `bin` folder such it's accessible from anywhere on your system (this may be different for you if you're using Mac). Or you could simply just run the script from the parent folder like I did above.

Let me know how that works :)

**Comment by AstroSaad** [comment]
Hi Nicholas.

It's possible I'm running an old script of `picsim.py`.

I ran your command from the parent folder and it was able to run! So for now, I'll run future commands from the parent directory.

Before I close the comment, do you have any further details on copying the platonium script into my bin folder? I'm on a Mac. I'm sure I've done this before as I can run the commands from the terminal regardless of location.

**Comment by nicholasjannsen** [comment]
Hi @AstroSaad 

Okay great to hear that! Actually you should in principle be able to reach any of your global variables if they are placed inside your Conda bin folder and you have activated your Conda environment. 

After activating your Conda environment, first check if the path environments are well defined:
```
echo $PLATO_PROJECT_HOME
echo $CONDA_PREFIX
```
As per the documentation page here (http://ivs-kuleuven.github.io/PlatoSim3/platonium_prerequisites.html) you should simply do the following from the command line:
```
PLATONIUM=$PLATO_PROJECT_HOME/python/platosim/platonium
```
then
```
cp $PLATONIUM/picsim.py    $CONDA_PREFIX/bin/picsim
cp $PLATONIUM/varsim.py    $CONDA_PREFIX/bin/varsim
cp $PLATONIUM/payload.py   $CONDA_PREFIX/bin/payload
cp $PLATONIUM/platonium.py $CONDA_PREFIX/bin/platonium
```
and lastly
```
chmod +x $CONDA_PREFIX/bin/picsim
chmod +x $CONDA_PREFIX/bin/varsim
chmod +x $CONDA_PREFIX/bin/payload
chmod +x $CONDA_PREFIX/bin/platonium
```
Can you let me know if that works for you to make all the scripts globally accessible?

Cheers,
Nicholas

**Comment by AstroSaad** [comment]
Hi Nicholas

The fix has worked. Thanks for the help!

**Comment by nicholasjannsen** [comment]
You're welcome!
