### ISSUE TITLE
Python dependency name changed: integrate.cumtrapz is now integrate.cumulative_trapezoid

### ISSUE THREAD

**Issue by PLATO-OS** [IvS-KULeuven/PlatoSim3#1009]
Hi,

I recently had to upgrade SciPy for another dependency and stumbled upon the following change:

SciPy 1.14 removed integrate.cumtrapz in favor of integrate.cumulative_trapezoid.

This is no big deal for me, I can just replace the names in utilities.py. But I thought I'd inform you about it anyway.

Best regards
Johannes (DLR)

**Comment by Dries-Seynaeve** [comment]
Thank you for mentioning this. I have added this in the code.
