### ISSUE TITLE
Varsim issues

### ISSUE THREAD

**Issue by AstroSaad** [IvS-KULeuven/PlatoSim3#1016]
Hello all.

I've encountered an issue when running varsim with a specific command. The command:
 `varsim --star_params 1 1 577 4.5 0.0 --planet_params 100 50 0 90 0 1 1 --time 365 -o Test2 ` (almost word for word one of the example commands in the tutorial) gets to the "Solar-like oscillations" stage but at the "Computing limb darkening coefficients with LDTk" stage, stops with an error: 
`scipy.spatial._qhull.QhullError: QH6013 qhull input error: input is less than 4-dimensional since all points have the same x coordinate 2300`

I tried a different command: `varsim --star WASP-33 --planet Jupiter --quarter 2-4 -o Test2` and this was able to run fine. I want to know what when wrong the first time, whether there's a bug or something I've not understood.

I'd also like some clarification into the role of Varsim. I understand that it is used to generate exoplanet light curves for variables and you can tune the parameters for the star and the planet. And then later on, this varsourcefile can be referenced when running platonium.
I'm not entirely clear what happens when platonium is run with this variable source file. For the star ID you enter, are its features from picsim overwritten by the ones from the varsourcefile? What if this star ID is one with contaminants; are the variable features modelled alongside the contaminants?

**Comment by nicholasjannsen** [comment]
Hi @AstroSaad, 

Hm I think you are working on brown dwarf here that's why. You have used `Teff=577 K` and I get the exact same error when running the above script. However, using the correct solar `Teff = 5772 K` everything works fine.

Cheers,
Nicholas
