### ISSUE TITLE
Platonium - payload and platonium errors

### ISSUE THREAD

**Issue by AstroSaad** [IvS-KULeuven/PlatoSim3#1017]
I'm getting errors running different parts of Platonium. When I run a `payload` command, I get this error when the code gets to the "Thermo-Elastic Distortion" part.

```
Traceback (most recent call last):
  File "/Users/saadahmed/anaconda3/envs/platosim_develop/bin/payload", line 405, in <module>
    x.createTED()
  File "/Users/saadahmed/anaconda3/envs/platosim_develop/bin/payload", line 336, in createTED
    ns.getTED(self.Q, ofile=self.fileNameTED, ampl=self.ted_ampl,
  File "/Users/saadahmed/PlatoSim/PlatoSim3/python/platosim/noise.py", line 1158, in getTED
    da = da.astype({'Quarter':np.int})
  File "/Users/saadahmed/anaconda3/envs/platosim_develop/lib/python3.9/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
```

When I run the platonium command, I get the error `[Error]: Not valid PLATO field! Options: {LOPS2, LOPN1, SPF, NPF}`; despite the fact that I've generated catalogues using picsim.

**Comment by nicholasjannsen** [comment]
Hi @AstroSaad, 

can you please provide the exact version of the `develop` branch you are using (e.g. the `git log` tag) and also the exact commands you use for both `payload` and `platonium`?

I think that the first issue could be a bug using just single value of the mission quarters, e.g. perhaps parsing `--quarter 1-8` would work fine?

**Comment by AstroSaad** [comment]
From git log; these are the details of the latest merge
```Merge: 490183ed e1f72c54
Author: Nicholas Jannsen <36379445+nicholasjannsen@users.noreply.github.com>
Date:   Thu Sep 5 17:38:40 2024 +0100

    Merge pull request #1015 from nicholasjannsen/develop
    
    Bugfix of varsim for usage of solar-like models
```

My payload command was `payload 100 LOPN1 --project Test2 -p`. I just tried `payload 100 LOPN1 --quarter 1-8 --project Test2 -p` but got the same error.

My platonium command was `platonium 1 1 1 1 --project Test2 -p `

**Comment by nicholasjannsen** [comment]
I just checked out the version of the develop branch that you are using. Running the command:
```
python $PLATO_PROJECT_HOME/python/platosim/platonium/payload.py 100 LOPN1 --quarter 1-8 --project test -p
```
everything works fine. I'm afraid you again are using some old `payload` scripts copied into your `$BIN` folder. Can you please check that the above command? If I recall correctly the above error message is from a quite old version of `payload.py`. 

Now for the `platonium` command, are you 100p sure you created a LOPN1 catalogue using `picsim`? Because if I do:
```
python $PLATO_PROJECT_HOME/python/platosim/platonium/picsim.py --pic 100 P1 LOPN1 --project test -p
```
and then:
```
python $PLATO_PROJECT_HOME/python/platosim/platonium/platonium.py 1 1 1 1 --project test -p
```
everything works perfectly fine without errors in the version you are using. If this is not the case, please provide us with a step-by-step execution of everything you do (it's very difficult to know why something is not working for you if you only provide a minimal example).

**Comment by AstroSaad** [comment]
I made a new project to test everything.

`python $PLATO_PROJECT_HOME/python/platosim/platonium/picsim.py --pic 100 P1 LOPN1 --project test -p`
works as expected.

`python $PLATO_PROJECT_HOME/python/platosim/platonium/payload.py 100 LOPN1 --quarter 1-8 --project test -p`
still returns the same error.

`python $PLATO_PROJECT_HOME/python/platosim/platonium/platonium.py 1 1 1 1 --project test` does work so there was likely an error on my part (Apologies for that).

However, adding the plotting command `-p` produces an error at the "Visualizing simulation" stage.
Specficically the command `python $PLATO_PROJECT_HOME/python/platosim/platonium/platonium.py 1 1 1 1 --project test -p` returns the following error:

```
Traceback (most recent call last):
  File "/Users/saadahmed/PlatoSim/PlatoSim3/python/platosim/platonium/platonium.py", line 2046, in <module>
    p.show_subfield(sim)
  File "/Users/saadahmed/PlatoSim/PlatoSim3/python/platosim/platonium/platonium.py", line 1045, in show_subfield
    drawStarInCCDfocalPlane(fig, sim,
  File "/Users/saadahmed/PlatoSim/PlatoSim3/python/platosim/plot.py", line 789, in drawStarInCCDfocalPlane
    ax.add_patch(descartes.PolygonPatch(one, fc='gray', ec='none', alpha=0.2))
  File "/Users/saadahmed/anaconda3/envs/platosim_develop/lib/python3.9/site-packages/descartes/patch.py", line 87, in PolygonPatch
    return PathPatch(PolygonPath(polygon), **kwargs)
  File "/Users/saadahmed/anaconda3/envs/platosim_develop/lib/python3.9/site-packages/descartes/patch.py", line 62, in PolygonPath
    vertices = concatenate([
  File "/Users/saadahmed/anaconda3/envs/platosim_develop/lib/python3.9/site-packages/descartes/patch.py", line 63, in <listcomp>
    concatenate([asarray(t.exterior)[:, :2]] +
IndexError: too many indices for array: array is 0-dimensional, but 2 were indexed
```
For the payload issue, would it be easiest to just make a new environment?

**Comment by nicholasjannsen** [comment]
Okay thanks for the update!

Regarding the error of `platonium.py` using the plotting option, it looks like it's coursed by the package `descartes` used to visualise where the star is located in the CCD focal plane. I haven't seen this error before actually. Some debugging steps:
- Does is work for any other star/group/camera/quarter or do you always encounter this error message?
- Could you tell me what version of this package you use? I use version 1.1.0, so if you are on the same version can you tell;
- How did you install the python dependencies (with Poetry)?

Regarding the issue with `payload.py`, I would indeed try to start from a fresh Conda environment and try again. I don't get any error on the branch version you are working on so it's a bit difficult to tell why you encounter an error.

**Comment by AstroSaad** [comment]
These are my updates for the platonium issue.
- I always encounter this error message, regardless of whichever configuration I'm trying to model
- The descartes version I have is 1.1.0 so same as you
- I believe I used poetry to install the dependencies; I have a lock file present in my directory (I tried attaching it but I don't think github will accept this file format). 
My current installation is on a Mac which I had to install with the help of Dries Seynaeve because I wasn't able to install it through conda. I wonder if some of my issues might be due to using a Mac?

I'm planning on moving to a Linux machine and install platosim with platonium and the lesia pipeline there. I'm fine to end this issue as "close as not planned" and move on if there's no obvious fix.

**Comment by nicholasjannsen** [comment]
Hm this is very strange. I'm not happy to leave the issue open as it's purely a python issue and should not (in theory) be related to the hardware or OS. If you have the time, can we have a quick call where we start from scratch and I can see how you install everything?

**Comment by AstroSaad** [comment]
That should be fine. Can you send me your email? We'll arrange a time for the call.

**Comment by nicholasjannsen** [comment]
Okay great, what's your email?

**Comment by AstroSaad** [comment]
It's sa2173@cam.ac.uk. Let me know what days and times you're free

**Comment by nicholasjannsen** [comment]
I've sent you an email. Cheers

**Comment by nicholasjannsen** [comment]
This issue was solved over a telecon.
