### ISSUE TITLE
problems using a larger psf

### ISSUE THREAD

**Issue by BertoltLang** [IvS-KULeuven/PlatoSim3#102]
I created interpolated versions of the psf arrays within the psf.hdf5 file with the goal of being able to use larger subpixel matrices. However, when I create images with the new psf, the pixel values are to high.

Currently I'm using psf matrices with the size of 4096x4096 to work with 512 subpixels per pixel. I would like to illustrate the problem with different output files, but they are to large to attach them here. I send them along with the my psf.hdf5 file via email to Joris.

I hope there is a general solution to this issue, since I'd like to use even larger PSF files.

**Comment by SaraRegibo** [comment]
Hi Bertolt,
the problem is that the new PSFs are not normalised (and that PlatoSim currently doesn't do that for you).  I will add a normalisation step at the appropriate locations!

**Comment by SaraRegibo** [comment]
Code to adapt: PointSpreadFunction.cpp
-> add normalisation step in:
- rotate()
- rebinToPixels()
- rebinToSubPixels()

**Comment by SaraRegibo** [comment]
Resolved in #105

**Comment by SaraRegibo** [comment]
Assigning to @BertoltLang for closure.

The PSFs are now automatically normalised by PlatoSim:

`print(sum(sum(output.getPSF("rebinnedPSFpixel"))))` -> 1 (more or less)
`print(sum(sum(output.getPSF("rebinnedPSFsubPixel"))))` -> 1 (more or less)
`print(sum(sum(output.getPSF("rotatedPSF"))))` ->  1 (more or less)

The fluxes in `output.getImage(0)` look ok (individual fluxes as well as `sum(sum(output.getImage(0)))`).

**Comment by BertoltLang** [comment]
This looks fine - Thank you, Sara!
