### ISSUE TITLE
terminate called after throwing an instance of 'H5::FileIException'

### ISSUE THREAD

**Issue by drsamadi** [IvS-KULeuven/PlatoSim3#1033]
Hi,
I get this message: "terminate called after throwing an instance of 'H5::FileIException'"
followed by a 'core dumped' message.

The only change I made w.r.t my usual configurationfile  is the PSF, I'm using a **AnalyticGaussian**  with the following parameters:
    AnalyticGaussian:     Gaussian
        Sigma00:                     1.0
        SigmaX18:                   1.0
        SigmaY18:                   1.0

[010000001.yaml.txt](https://github.com/user-attachments/files/17729766/010000001.yaml.txt)

PlatoSim 3.6.0-640-gf70cf22e

Réza

**Comment by Dries-Seynaeve** [comment]
Hi Reza, there was a problem when writing the PRNU to the flatfield group in the HDF5 file. This should now be fixed.

**Comment by drsamadi** [comment]
Problem solved!  Thanks

**Comment by drsamadi** [comment]
Hi,

i was able to compute a full image using a Gaussian PSF but when I compare the star positions and the Center Of  Brightness of a large sample of stars in the field of view I get a systematic shift of exactly  -0.5 px in both X(col) and Y(row) directions.

With the usual AnalyticNonGaussian, the differences are centered approx. around zero (but nevertheless the dispersion is high I presume because of the chromatic aberration, which is not included in colPix and rowPix , see issue #930, on the other hand the  Gaussian PSF does not show such high dispersion, which is normal since the latter is not concerned by the chromatic aberration ).

**Comment by drsamadi** [comment]
The histogram below shows the difference between the platosim X positions and the X-COB  computed by the L1 pipeline, here the simulation was build assuming  Gaussian PSF 
![Screenshot from 2024-11-16 14-15-31](https://github.com/user-attachments/assets/411928b4-2cb0-46da-9352-b2b0a8e00b37)
The difference is centered at exactly -0.5 pixel. 

The histogram below is for a simulation based on the NonGaussianAnalytical PSFs:

![Screenshot from 2024-11-16 14-13-36](https://github.com/user-attachments/assets/b7e4ae13-3724-4fae-9c51-14954d387379)

as you can see here the difference is centered around zero.
but the dispersion is higher and you can see two distinct points of accumulation, which I interpret to be caused by the fact that the platosim positions do not include the chromatic aberration (see the issue #930 )
