### ISSUE TITLE
utilities.py: backward compatibility

### ISSUE THREAD

**Issue by jcabrera271828** [IvS-KULeuven/PlatoSim3#1037]
Hi,

the file "utilities.py" contains the following 'backward compatibility' script (lines 33-37)
# Backward compatability
if (scipy.__version__ > "1.6"):
    from scipy.integrate import cumulative_trapezoid as cum_trapz
else:
    from scipy.integrate import cumtrapz as cum_trapz

It actually fails with scipy.__version__ = "1.14.0"
>>> scipy.__version__
'1.14.0'
>>> scipy.__version__ > "1.6"
False

I would propose to write instead:
if "cumtrapz" in dir(scipy.integrate):
    from scipy.integrate import cumtrapz as cum_trapz
elif "cumulative_trapezoid" in dir(scipy.integrate):
    from scipy.integrate import cumulative_trapezoid as cum_trapz

**Comment by JorisDeRidder** [comment]
I fixed this bug in the latest version of develop. I have to rely on you to test it, however, because my conda installer doesn't even allow me to install such old versions. Could you check if it now works with your version of scipy?

**Comment by jcabrera271828** [comment]
thanks, Joris! I have checked and it works.
