### ISSUE TITLE
simfile.py: getFlux

### ISSUE THREAD

**Issue by jcabrera271828** [IvS-KULeuven/PlatoSim3#1038]
In simfile.py the function getFlux(self, starID, fluxType="estimated", df=False) computes the flux from the imagette in electrons / s

In line 1758 of the current version the flux is normalized by the readout time
df0 /= self.getReadoutTime()[0

The current implementation is incorrect:
- The readout time is 4s for the N-CAMs and 0.2s for the F-CAMs. 
- The correct normalization is by the *exposure* time, which is 21s for the N-CAMs (cycle=25s) and 2.3s for the F-CAMs (cycle=2.5s)

The proposed correction is:
df0 /= self.getExposureTime()

**Comment by JorisDeRidder** [comment]
Thanks for reporting this bug. I fixed it in the latest version of the develop branch.

**Comment by jcabrera271828** [comment]
Thanks!
