### ISSUE TITLE
problem with MappedFromFile PSF

### ISSUE THREAD

**Issue by drsamadi** [IvS-KULeuven/PlatoSim3#1045]
Hi, 
using a working configuration with a single star within a 6x6 imagette, I changed the PSF model from AnalyticNonGaussian to MappedFromFile, and the star is no longer in the imagette, and the data set "StarPositions" contains only NaN

Changing the size to 8x8 does not solve the problem.

The MappedFromFile was downloaded from http://ivs-kuleuven.github.io/PlatoSim3/run_input.html#psf-data-packages 

PlatoSim 3.6.0-664-g28530e68

[000000045.yaml.txt](https://github.com/user-attachments/files/18128581/000000045.yaml.txt)

[000000045.coo.txt](https://github.com/user-attachments/files/18146833/000000045.coo.txt)

**Comment by Dries-Seynaeve** [comment]
Hello Réza, 

I think this has to do with the fact that we use a different field distortion for mappend then for analytic psf. 

Depending on your need, I could implement a function that should give a good analytic approximation of the mapped psf distortion.

Kind regards 
Dries

**Comment by drsamadi** [comment]
Hi Dries,
ok, I see. Then if I use reference.Frame.pixelToSkyCoordinates() to infer the position of the star in the sky this should solve my problem right ?

**Comment by Dries-Seynaeve** [comment]
I believe this should work.

**Comment by drsamadi** [comment]
This works ! Thanks for you feedback
