### ISSUE TITLE
error "CTEMean" of field "CCD" is not available in the configuration file, but "MeanCTE" is

### ISSUE THREAD

**Issue by ghost** [IvS-KULeuven/PlatoSim3#107]
Running the tutorial "Scripting PlatoSim with Python", I'm having at the command 14, i.e. "simFile = sim.run()".
The error message is the following : 
<< ConfigurationParameters: The sub-field "CTEMean" of field "CCD" is not available in the configuration file (.../Run01.yaml) >>
However, looking in the output file Run01.yaml, I can see the field "CCD" and the sub-field "MeanCTE".

**Comment by JorisDeRidder** [comment]
Since the workshop the PlatoSim has been updated with new features that modified the configuration file, but the tutorial files have not yet been adapted accordingly. We'll do this asap.

**Comment by ghost** [comment]
I don't think this is related to the tutorial files : I've run the same commands in a python script in my working directory, and it crashes at command 14, giving the same error message.
My apologies if I'm writing something stupid, but would it be possible that the simulator is writing "MeanCTE" in "Run01.yaml", and afterwards tries to look for the sub-field "CTEMean" in "Run01.yaml"?

**Comment by SaraRegibo** [comment]
Hi Steve,

could you confirm that you have the latest version of PlatoSim and re-built the code, like this (taken from the documentation pages):

```
cmake ..
make clean
make -j 4
```

**Comment by ghost** [comment]
Hi. I just got the latest version, and I've re-built the code as you instructed : I was able to run the command line in python "sim = Simulation('Run01', outputDir=workDir)" without having the error message I described. Thank you - you can close the issue.

On the PlatoSim3 web page (i.e. "http://ivs-kuleuven.github.io/PlatoSim3/"), in the section "Retrieving & Updating the Software", in the sentence << You can then update the software by executing [...] in the directory in which you installed PlatoSim3. >>, perhaps you could add that it is necessary to re-built the code locally as indicated in the "Build & Install" section.

**Comment by SaraRegibo** [comment]
Glad it works now!  I will make sure the documentation gets improved.

**Comment by SaraRegibo** [comment]
Updated the documentation to make it more clear that you have to re-build the software after updating it. See #108 & #109
