### ISSUE TITLE
Cmake problems with gcc 6.1.1

### ISSUE THREAD

**Issue by BertoltLang** [IvS-KULeuven/PlatoSim3#112]
I was not able to build the platosim executable with gcc 6.1.1 due to a missing linker to the pthread library.
Adding it in the CMakeLists.txt file in line 136 solved the problem.

org:
target_link_libraries(platosim platosimLibrary hdf5 hdf5_cpp armadillo yaml-cpp fftw3f fftw3f_threads)

new:
target_link_libraries(platosim platosimLibrary hdf5 hdf5_cpp armadillo yaml-cpp fftw3f fftw3f_threads pthread)

**Comment by rhuygen** [comment]
Will add the pthread library.

**Comment by rhuygen** [comment]
@BertoltLang can this issue be closed?
