### ISSUE TITLE
Runtime regex error with gcc v4.8.5

### ISSUE THREAD

**Issue by rhuygen** [IvS-KULeuven/PlatoSim3#12]
Excerpt from an email conversation:

On a suse server (gcc (SUSE Linux) 4.8.5):

The runtime error that I get on the server after compiling with is:

chifuv@plato1:~/work/PlatoSim3/build> ./platosim ../inputfiles/inputfile.yaml out.out
terminate called after throwing an instance of 'std::regex_error'
 what():  regex_error
Aborted

I also tried to run the tests (see the attached file one with the log and the other the output). It seems the error comes from parsing the input configuration file which seem consistent with the runtime error ...

**Comment by rhuygen** [comment]
The problem here is that gcc prior to version 4.9.2 doesn't properly implement the regex standard of C++11. Regular expressions are currently only used when parsing the input YAML file. This is related to issue #6, where the problem was solved by updating the compiler. However, in order to try to be backward compatible as much as possible, the regex code will be replaced with plain string functions.

**Comment by rhuygen** [comment]
Fixed in pull request #11.
Assigned to Valerian to check and validate the fix.

**Comment by dk766** [comment]
I've made some tests with the fixes and I can confirm that the error does not appear any more.
All the 61 tests passed and the initial run with the defaults configuration file generated the expected output.
