### ISSUE TITLE
missing parameter in inputfgs.yaml

### ISSUE THREAD

**Issue by BertoltLang** [IvS-KULeuven/PlatoSim3#134]
In the new version, PlatoSim needs the parameter "CCD/Polarization/ExpectedValue" in the inputfgs.yaml file. Currently it's missing and PlatoSim cancels the simulation. Adding the parameter solves the problem for me.

**Comment by JorisDeRidder** [comment]
Thanks for reporting this. I fixed this problem in commit fbe8e2c.
