### ISSUE TITLE
Add version number

### ISSUE THREAD

**Issue by dk766** [IvS-KULeuven/PlatoSim3#15]
From installation maintenance point of view it would be helpful to have a simple way to obtain the version of a compiled PLATOSim3 similar with other applications (in humanly readable format):

`$ python --version`
Python 2.7.4

`$ java -version`
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) Client VM (build 25.91-b14, mixed mode, sharing)

Every push on the master should change this version (or alternatively build number)
In this way any reported bugs on a particular version of PLATOSim can be immediately match to the version from git.

**Comment by dk766** [comment]
I tried to find out if git offers some functionality to support this request and from what I found until now it seems the usage of tags is the most solid approach.
See this [article](http://nvie.com/posts/a-successful-git-branching-model/)

**Comment by rhuygen** [comment]
We are already looking into this.

In addition to the request, the version or build number shall also be available in the HDF5 output file and written to the log file.

**Comment by rhuygen** [comment]
The implementation is in pull request #25.

Version information will be automatically included in `platosim` executable after running cmake.

Version information is printed on the command line with the optional argument -version.

`platosim -version`

Version information is written to the log file.
Version information is written to the HDF5 file.
