### ISSUE TITLE
installation of fadeeva in alphaRelease fails

### ISSUE THREAD

**Issue by BertoltLang** [IvS-KULeuven/PlatoSim3#153]
I get an error, when I run the installation script.
Changing line 35 in install_fadeeva.py from:

tar -xzvf {package}.tgz;   

to:

tar -xvf {package}.tgz;

solved the problem for me.

**Comment by rhuygen** [comment]
Bertolt, is this still a problem for you. If so, can you provide details about the system on which you try to compile PlatoSim3?

**Comment by BertoltLang** [comment]
Yes, fadeeva is only installed when I alter the install_fadeeva.py file as mentioned. 

I'm running PLATOSim on Ubuntu 16.04 (64-bit).

**Comment by JorisDeRidder** [comment]
Fixed in the current release candidate in the 'alphaRelease' branch.
