### ISSUE TITLE
deviant CCD positions

### ISSUE THREAD

**Issue by BertoltLang** [IvS-KULeuven/PlatoSim3#157]
I tested the position of the star: 82.900016    -45.925317     5.6200000
with the pointing Coordinates: 86.79870    -46.39595
with fast Cameras and no other influences or rotations.

The focal plane coordinates (in mm) calculated by referenceFrames.py are:

2.30190657247  11.6234953662

which should result in a position on the BF CCD if I interpret the attached image correctly. 

![platoccds](https://cloud.githubusercontent.com/assets/18306603/26198956/83ba9e68-3bc8-11e7-8dc4-f4bd5b07e62b.JPG)

However, I get the result, that the starlight falls on the CF CCD.  

In this context I wonder why the orientation of the CCDs are differently defined within ln. 32 and following in referenceFrames.py and in ln. 212 in inputfile.yaml. As far as I see it, the rotations used are the same and not inversed in the respective functions "focalPlaneToPixelCoordinates" within the python and C++ code.

**Comment by BertoltLang** [comment]
I have checked my statement again with the new reference frame documentation. I still think, that the simulation with the above mentioned values should result in a position on the BF CCD. 

However, since this is only a matter of definition and a simple swap of the orientation values of the BF and CF CCDs within referenceFrames.py and input.yaml results in the same simulator output, I don't see further problems with this issue.

**Comment by JorisDeRidder** [comment]
Today we updated the nomenclature of PlatoSim3 (in branch 'alphaRelease') to correspond with what is used in the payload consortium. The new labelling of the CCDs can be found on page 9 of docs/technicalnote/PLATO-KUL-PL-TN-0001.pdf

<img width="451" alt="ccdlabeling" src="https://cloud.githubusercontent.com/assets/5747893/26725017/a2474b6c-479c-11e7-83b0-36a90d40d497.png">
