### ISSUE TITLE
setting the "Position" variable, when starting PLATOSim via fgs.py

### ISSUE THREAD

**Issue by BertoltLang** [IvS-KULeuven/PlatoSim3#158]
I suggest to automatically set the "Position" variable to "Custom" or to the respective CCD number, when PLATOSim is started with the python script, since PLATOSim only produces unusable data for stars which are not on the, in "inputfile.yaml" specified, CCD.

**Comment by rhuygen** [comment]
This is indeed a mistake, the default inputfile.yaml has Position set to Custom, the inputfgs.yaml has Position set to 1. I will change this to Custom also.

**Comment by BertoltLang** [comment]
Thank you.
