### ISSUE TITLE
Platosim3.2 installation, Faddeeva.hh is missing

### ISSUE THREAD

**Issue by manugr788** [IvS-KULeuven/PlatoSim3#160]
I got an error when compiling PlatoSim 3.2 about Faddeeva.hh file :

/obs/grolleau/git/PlatoSim3.2/include/DetectorWithAnalyticNonGaussianPSF.h:13:23: fatal error: Faddeeva.hh: No such file or directory
 #include "Faddeeva.hh"

I have just looked for faddeeva on the net and found it within this package :
libopenspecfun-dev

Nevertheless it’s not Faddeeva.hh but Faddeeva.h (only .h), 

https://packages.debian.org/fr/jessie/amd64/libopenspecfun-dev/filelist

Do you know in which Debian package I can get faddeva includes and library ?

Cheers,

**Comment by rhuygen** [comment]
Faddeeva is installed with PlatoSim3. You probably have to run ./install.sh again from the installation directory to get this working.

**Comment by JorisDeRidder** [comment]
It would be useful if you could give us the installation log of Faddeeva.

**Comment by manugr788** [comment]
I saw the update you made on friday 
"Fixed install_faddeeva.py so that Faddeeva installs on both Mac and Linux".

How to update this new version of PlatoSim ?
Usually I use these command lines : 
$ git pull origin master
$ cd build
$ rm -rf *
$ cmake ..
$ make clean
$ make -j 4

but since I have used "git checkout -b release-3.2-rc1 v3.2.0-RC1" to checkout this 3.2 release I am not sure the command lines above are the good way

**Comment by rhuygen** [comment]
The easiest way to follow the patches on the release 3.2 is to switch to the alphaRelease branch:

`$ git checkout origin alphaRelease`

You probably will get a message that your branch is behind and you can fast-forward, so execute the command:

`git pull origin alphaRelease`

This of course asumes that origin is pointing to the PlatoSim3 GitHub of IvS-KULeuven. You can check that with the following command:

`git remote -v`

**Comment by manugr788** [comment]
Ok, I have just successfully compiled Platosim v3.2 !
