### ISSUE TITLE
Images datasets output dataype and specification

### ISSUE THREAD

**Issue by manugr788** [IvS-KULeuven/PlatoSim3#167]
Philippe Plasson & Loic Gueguen Team (N-DPU Software) have made a “wise” comment about PlatoSim HDF5 output file. They have noticed that “Images” dataset is coded using **32 bits floating-point** datatype whereas it should use “**unsigned int 16bits**”. Actually, the pixel value coming from FEE uses unsigned int 16bits (big endian, to be very complete). The unit is ADU, every value is an integer between 0 and 65,535 (216 − 1), the digital saturation. This range should not be a problem for Platosim or PIS output, we will just have to check the value stored in case of saturation.

I think we will change PIS output (so far 32 bits int) to match this requirement, may you do the same for Platosim V3 ? Moreover, this change may save almost 50% of space over the disk.

By the way, is there any **interface specification** that describes the Platosim hdf5 output file format, especially the datatype? If not, it was requested by Philippe Plasson Team. A simple extraction of the properties of the file using a tool like h5ls -rv file.hdf5 may be enough to initiate this document.

**Comment by JorisDeRidder** [comment]
PlatoSim's output is configureable in the yaml input file. Depending on whether the QE, the gain, saturation, etc is taken into account, the units of the output can be photons, electrons, or ADU. We could consider switching to integers, but 16 bits would definitely not be enough to cover all types of output. 

An interface specification document might indeed be handy. We'll put that on our to-do list.

**Comment by SaraRegibo** [comment]
Assigning to myself to document it on the PlatoSim documentation pages.

**Comment by SaraRegibo** [comment]
Documented on the [PlatoSim documentation pages](http://ivs-kuleuven.github.io/PlatoSim3/OutputFileDescription.html) since #262.
