### ISSUE TITLE
Clarification on the SubPixels parameter in the configuration file

### ISSUE THREAD

**Issue by dk766** [IvS-KULeuven/PlatoSim3#175]
By reading the comment in the sample configuration file:
"_(Sqrt of) nr of subpixels per CCD pixel. Should be 2^n <= 128._"

and the explanation of the http://ivs-kuleuven.github.io/PlatoSim3/InputFileDescription.html
is not very clear to me if this value is a power of 2 or a square root.

Could you pls tell me if for a simulation with 256 sub-pixels per pixel what value should I set for **SubPixels** param ?

**Comment by JorisDeRidder** [comment]
If you want a pixel of 256 * 256 = 65536 subpixels you should specify in the configuration file 256. The total number of subpixels per pixel will then be 65536. If you want 256 = 16 * 16 subpixels per pixel, then you should specify 16 in the configuration file.

**Comment by SaraRegibo** [comment]
Updated description of the `SubPixels` parameter and added an example.

Closed by #196 and #197.
