### ISSUE TITLE
throughputMap is independent of CCD position

### ISSUE THREAD

**Issue by BertoltLang** [IvS-KULeuven/PlatoSim3#193]
In void Detector::generateThroughputMap() the programs loops over the numRowsPixelMap and numColumnsPixelMap which are defined in ln. 237 f. as "SubField/NumRows" and "SubField/NumColumns". This means in my case always from 0 to 9, independent of the position of the subfield. This always leads to the presumably wrong calculation of the "angle" variable and results in the same throughputMap for every star.
I would loop over the subfield in the range of SubField/zeroPointRow to SubField/zeroPointRow + SubField/NumRows and SubField/zeroPointColumn to SubField/zeroPointColumn + SubField/NumColumn respectively. This should make sure the influence of the CCD position of the subfield is taken into consideration and effects like vignetting, polarization and quantum efficiency are implemented correctly.

**Comment by SaraRegibo** [comment]
This indeed a mistake.  The method `pixelToFocalPlaneCoordinates` indeed takes the coordinates in the CCD as input and not the coordinates in the sub-field.  This got looked over at some point in time.  Luckily you spotted this!  I will fix the ranges in the `for`-loops of the `generateThroughputMap` method, both in the `master` and in the `develop` branch.

I checked whether this problem could also have arisen at other places in the code, but this does not seem to be the case.

**Comment by SaraRegibo** [comment]
Solved in:
* master branch: pull request #194 
* develop branch: pull request #195

**Comment by SaraRegibo** [comment]
Re-assigning to Bertolt for closure.

**Comment by BertoltLang** [comment]
I was a little too eager to close the issue - there is still a little mistake that causes the program to crash, the way it is now.
The throughputMap variable is an array with the size of the subfield, but it is fed with the row and column variables (ln. 352 ff.), which are coordinates of the whole ccd. This causes an "out of range-error".
I fixed this by replacing each call to throughputMap in the loop with: 

throughputMap(row-subFieldZeroPointRow, column-subFieldZeroPointColumn)

**Comment by SaraRegibo** [comment]
Sorry about this, Bertolt!

Solved in:

* master branch: pull request #200 
* develop branch: pull request #201

**Comment by BertoltLang** [comment]
Thank you Sara!
