### ISSUE TITLE
Outliers in BiasMaps ?

### ISSUE THREAD

**Issue by dk766** [IvS-KULeuven/PlatoSim3#203]
This is more a question: shouldn't cosmics also affect BiasMaps (not only the image and the smearing maps) ?
Currently I see no cosmic effects of cosmics in bias maps.

**Comment by JorisDeRidder** [comment]
I think so, bias maps should be affected by cosmics indeed. If I remember well, the bias prescan are physical readouts, while the smearing (overscan) are virtual readouts. We'll adapt the code asap.

**Comment by manugr788** [comment]
Hi,
In order to compute the Bias Maps we will use the serial prescan rows (not the register), whereas to measure the smearing pattern we will use the parallel overscan rows. Both are "virtual readouts" but the latter see the sky through the image section whereas the former only see the register. Since image section and register section are both real,  cosmics may affect both bias and smearing maps.

**Comment by SaraRegibo** [comment]
Hi Emmanuel,
indeed the pixel map, bias register map, and smearing map must be affected by the cosmics.  I actually thought I had implemented it like that, but apparently I made a silly mistake in the implementation.  Looking into it right now!

**Comment by SaraRegibo** [comment]
Issue solved by pull request https://github.com/IvS-KULeuven/PlatoSim3/pull/205.

**Comment by SaraRegibo** [comment]
Assigning to Emmanuel for closure.

**Comment by dk766** [comment]
I confirm that cosmics now also affect BiasMaps.

Can you pls. clarify for me how the Intensity configuration parameter (see below) is used ?

Intensity: [20000, 40000] # Interval of the total number of e- in a cosmic hit [e-]

What I would like to know is, based on this configuration, what is the max outlier value that I could expect ?

Currently the max value in the BiasMap is about 5.4E3 so if I substract the average BiasMap value (without cosmics) whict is abou 9.9E2 I get 4.4 E3 which is roughly the upper boundary of the Intensity interval/10 Is this correct ? 
If so what does 10 represent ?

**Comment by SaraRegibo** [comment]
Consider an individual cosmic hit.  The total number of excess electrons inhibited by this cosmic hit is in the specified intensity interval (here [20000, 40000]).  These electrons are spread over a trail (the length is in the specified trail length interval [0, 15]), following a decay function.

So for a cosmic hit of 30000 electrons and a trail length of 10 pixels, these 30000 electrons are spread out over 10 pixels.
