### ISSUE TITLE
Issue with cosmics in images

### ISSUE THREAD

**Issue by dk766** [IvS-KULeuven/PlatoSim3#204]
PlatoSim v3.2.0-RC1-177-g5b12879

I modified the defauls input config file with:
    IncludeCosmics:                  yes             # Whether or not to include cosmics
    Cosmics:
      CosmicHitRate:                 10000              # Cosmic hit rate [events / cm^2 / s]
      TrailLength:             [0, 15]               # Intervalof the length of the cosmic trails [pixels]
      Intensity:               [20000, 40000]         # Interval of the total number of e- in a cosmic hit [e-]

and changed the size of the image:
   NumColumns:                      2255            # Number of columns, should be >= 8 [pixels]
   NumRows:                         100             # Number of rows,    should be >= 8 [pixels]
All the other parameters are unchanged.

I would expect to have a high energy cosmics on the entire image. However only the first about 200 columns seem to be affected. 

To show the problem I made a graph of a few random lines from the image data (rows 7,11,19,49 ...) It is visible that the high (cosmic impacts) values  are only at the beginning of the graph (in the first approx 200 columns) which is unexpected.

![screenshot from 2017-11-27 17-49-56](https://user-images.githubusercontent.com/18440862/33278358-97260062-d39b-11e7-9cb5-d16a00512fd8.png)

**Comment by SaraRegibo** [comment]
Solved together with issue #203 by pull request https://github.com/IvS-KULeuven/PlatoSim3/pull/205. Attached is an image indicating the cosmic hits are spread all over the image (I increased the cosmic hit rate and intensity to make it more obvious).

<img width="349" alt="screen shot 2017-11-28 at 10 39 24" src="https://user-images.githubusercontent.com/10076088/33313405-d52551f8-d42a-11e7-9356-f69f963aff71.png">

**Comment by SaraRegibo** [comment]
Assigning to Emmanuel for closure.

**Comment by dk766** [comment]
As a validation test I would suggest a larger (than 250x250 pixels) image. In the original bug that I submitted it is visible that the high cosmics values are already present in the first 200 columns. The problem appears though in the columns > 250.

I recompiled PlatoSim (from develop branch !)
And retested but the behaviour seems similar (high outlier values only clearly visible in the first 250 columns)

PlatoSim version:
        Application = PlatoSim3
        GitVersion = v3.2.0-RC1-181-g1cfff9e

Valerian (not Emmanuel) ;)

![screenshot from 2017-11-28 11-29-11](https://user-images.githubusercontent.com/18440862/33314948-7f46f048-d42f-11e7-90f9-5fd6bb508a90.png)

**Comment by dk766** [comment]
After looking more carefully at both the BiasMaps and the Images it seems the problem is a bit different:
- for Bias Maps the average values are around 1000 + - 4 After the fix I see now that the cosmics are affecting the bias values too (all of them) and that the max value is about 5000 
- for Images the behaviour seems more or less similar (to the BiasMaps) with one exception: there are some very high values (34632.0, 33324.0) but only in the first approx 250 columns. The columns >250 still contain outliers but with significantly smaller values.

This seems strange. I would expect to have very high cosmics values on the entire CCD and probably also in the BiasMaps (which is not the case) ...

**Comment by dk766** [comment]
This effect was due to the fact that there were stars only in the first 200 columns. So while in the first columns the plot displays star intensity + cosmics in the rest of the plot there are only cosmics.
