### ISSUE TITLE
kernel dimension restrictions

### ISSUE THREAD

**Issue by BertoltLang** [IvS-KULeuven/PlatoSim3#211]
I wanted to cut back on computation time and storage space and tried to start simulations with a smaller subfield (7x7 instead of 9x9) for a simulation with a mapped PSF from file.
I got an error message, that the kernel dimensions should be smaller than the input matrix dimensions. 

I didn't find any other restrictions within the code and just uncommented the respective lines in Convolver.cpp, Convolver::initialise(int Nrows, int Ncols, matrix &kernel) ln. 106 -113. 
The results were good, I got smaller imagettes in a shorter period of time (a simulation took around 70% of the time it usually takes).

Is there a reason for the restriction I overlooked?

**Comment by SaraRegibo** [comment]
Hi Bertolt,
If your PSF is bigger than your image, you risk to loose a lot of flux falling off the image after convolution.  On the other hand, it is possible that the input file of the PSF is much bigger than the actual size of the PSF, so I will remove this restriction.
