### ISSUE TITLE
rotation of analytic, non-gaussian psf 

### ISSUE THREAD

**Issue by BertoltLang** [IvS-KULeuven/PlatoSim3#212]
At the moment, when the analytic PSF is calculated, the orientation of the CCD, the starlight falls on, is not taken into account. In most cases, this leads to a presumably wrong alignment of said PSF.

I solved the issue for me by tweaking the function:

tuple<bool, double, double> DetectorWithAnalyticNonGaussianPSF::addFlux(double xFP, double yFP, double flux)

the azimuth angle p has to be adapted before it is used in the integrateAnalyticPSF() function. Therefore I included the following lines before calling it:

    IntegralOfAnalyticPSF psf(size);
    double r = rad2deg(camera.getGnomonicRadialDistanceFromOpticalAxis(xFP, yFP));
    double p = atan2(yFP, xFP);

    **//orientation of the ccd has to be considered
    double ccdOrientation = getOrientationAngle();
    p -= ccdOrientation;**

    integrateAnalyticPSF(psf, column0, row0, r, p);

After that, the PSFs seemed to be aligned with the respective mapped PSFs from file.

**Comment by JorisDeRidder** [comment]
Well spotted! I'll include the fix in the develop branch right away.

**Comment by JorisDeRidder** [comment]
Done.
