### ISSUE TITLE
large jitter file as a performance drain

### ISSUE THREAD

**Issue by BertoltLang** [IvS-KULeuven/PlatoSim3#221]
I used to use always the same (very large) jitter file, even for shorter simulations or simulations there I didn't include jitter effects at all, not realizing how much that slowed the simulation process.

I suggest to alter PlatoSim in a way, that it checks whether jitter is really used in the simulation, before loading data from the jitter file. This happens when the parameter "UseJitter" == False and "UseJitterFromFile" == True within the .yaml file, if I'm not mistaken.

Furthermore, a feature could be added to stop the loading of jitter data from file, when there is enough to cover the timespan, the simulation takes place in. This could free some resources and speed up the process.

Cheers,

Bert

**Comment by JorisDeRidder** [comment]
Thanks for the suggestion! In the latest develop version, the jitter file is no longer read when UseJitter == no, even if UseJitterFromFile == yes. In addition, only the relevant part of the jitter file is read into memory.  Idem with UseDrift and the thermo-elastic drift file.
