### ISSUE TITLE
Use an external defined star ID in input star catalogues

### ISSUE THREAD

**Issue by dk766** [IvS-KULeuven/PlatoSim3#229]
Currently the star catalogue input file only have 3 columns: RA, DEC and Magnitude.
It would be useful if a start_id column will also be added (maybe as an optional column for sake of  backward compatibility).

Currently if I understood well the starID is the number of the row from the input star catalog file. 
Is this correct ? (also what is currently the first star id that PlatoSim assigns: 0 or 1 ?)
If so this is not too convenient since when using a large star catalogue many times filtering and sorting are done (with external tools) so the original row positions are lost. Using a star id column (which is usually available in a star catalogue) would circumvent this problem.

**Comment by JorisDeRidder** [comment]
This feature has been on our to-do list for quite a while, be it with a lower priority as we were not sure whether it would actually be used. If it would really help you, we would be happy to implement it. The implementation is in fact not too difficult.

Currently the first star ID is 0.

**Comment by dk766** [comment]
Yes I think this would be useful. 
Most importantly this will ensure that order of stars in the starcatalog is not important. This will also ensure that if I have an updated version of an older catalog (the common stars will have the same ID) which will be very helpful specially in regression tests of the L1 pipeline since we expect incremental updates of the PIC.

Also I would advice a few other minor changes related to this:
1. when loading a CSV usually (but not always) the first row may contain the header of the table. It would be nice is PlatoSim would also accept this. I do not necessarily need PlatoSim to read and "understand" the header but at least to ignore it without crashing. So is perfectly ok to have hard-coded in PlatoSim the order of the values in the input file but to at least accept some comments. This would make the editing of these files easier (without having to check the documentation for every step) 

For instance In my applications I usually accept bash style commented lines (everything that starts with '#') and I simply ignore those lines when load the csv. This simple approach might be something to consider since it would not change too much the existing behaviour .
In this case the starcatalogue.txt could look like (columns order cannot be changed):
```
# ra, dec, flux, star_id
142.31408301273 -89.34723712528931 8.01126 star_1
298.5524384888419 -89.27180003767359 9.61558 star_2
...
```
and I could even add comments to explain some columns:
```
# Input columns are (in this order): ra, dec, flux, star_id
# where: ra ..
# star_id - is created based on ....
142.31408301273 -89.34723712528931 8.01126 star_1
298.5524384888419 -89.27180003767359 9.61558 star_2
...
```
2. since the starcatalog.txt is basically a csv using ' ' (blank) as separator it would be helpful if I could configure the separator. In most cases the separator will be "," (comma) and the spaces and tabs (if there are any) should trimmed.
In this case the file could look like (pls note I have comma + space after each value):
```
# ra, dec, flux, star_id
142.31408301273, -89.34723712528931, 8.01126, star_1
298.5524384888419, -89.27180003767359, 9.61558, star_2
...
```

**Comment by JorisDeRidder** [comment]
I added the possibility of header lines (starting with '#' as the first character of the line), and you can now add a fourth column with the star IDs (positive integer numbers). If the star ID column is omitted, the row numbers are still used as ID. The column separator is not yet configurable, it should still be spaces.

Can you have a look at the latest version of the develop branch, and see if this works for you?

**Comment by dk766** [comment]
I tried to test the new code from develop branch but id doesn't seem to work as expected:
- If I have comments in the starcatalog.txt platosim crashes (Segmentation fault (core dumped) )
- if I have a 4th column (no comment line) it runs but the 4th column is not interpreted as ID
What I did notice though is that now the ID starts from 1 and not from 0 (which is ok)

**Comment by JorisDeRidder** [comment]
Strange, I tested all this last night. Could you please post the starcatalog.txt file?

**Comment by dk766** [comment]
While debugging I created a test one ...
./platosim -version
PlatoSim v3.2.0-RC1-322-gbb3362d
[starcatalog_test.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/1747533/starcatalog_test.txt)

![screenshot from 2018-02-22 11-43-02](https://user-images.githubusercontent.com/18440862/36534062-c0aee16a-17c5-11e8-902a-d932002469f4.png)

**Comment by JorisDeRidder** [comment]
Could you please double-check if you included the correct starcatalog file? Because your _test catalog file works perfectly fine for me. Also adding header lines that start with '#' works fine in my case. Could you post an example of a starcatalog with header lines that crashed on your computer?

<img width="912" alt="screencapture at thu feb 22 12 17 34 cet 2018" src="https://user-images.githubusercontent.com/5747893/36535568-6e94705c-17ca-11e8-80f8-303d76f912bd.png">

**Comment by dk766** [comment]
Yes the paths were ok.
I ran a "git pull" again and after I compiled it works for me too.
Not sure what happened.

**Comment by JorisDeRidder** [comment]
OK, good to hear it works for you too. Closing the issue.

**Comment by SaraRegibo** [comment]
Documented in pull request #234
