### ISSUE TITLE
PlatoSim library dependencies

### ISSUE THREAD

**Issue by dk766** [IvS-KULeuven/PlatoSim3#230]
As it is now the PlatoSim executable still have some dependencies on some external libraries. This is in principle fine but the problem is that these libraries are referenced (linked is the correct term ?)  with absolute paths which makes it a a bit complicated especially when I have multiple users that need access to run PlatoSim (permission issues etc etc.)
In our environment PlatoSim runs on several machines so to make sure that it can run I have to put at the same absolute paths al the libraries (regardless of where the PlatoSim executable is). This is not always possible (or at least not with ease). 
It would be great if I could have these libraries either included in the executable or at some relative paths so I could move them together with the  PlatoSim executable.

**Comment by JorisDeRidder** [comment]
We don't have a lot of experience with setting the link path, but we'll look into this. We do know that it's different on Mac and Linux, which complicates the task.

**Comment by SaraRegibo** [comment]
Sent email to Valerian to do a quick test with the installation via conda.  Once this works for him, we will put documentation in place and inform all other users.

**Comment by SaraRegibo** [comment]
Installation via conda described in https://github.com/SaraRegibo/PlatoSim3/tree/documentInstallationViaConda (will merge it to the develop branch if it works for Valerian).
