### ISSUE TITLE
Can PlatoSim select stars outside the CCD ?

### ISSUE THREAD

**Issue by dk766** [IvS-KULeuven/PlatoSim3#237]
This is more of a question than a issue. I have run recently a simulation that created some problems in Phaedrus and debugging it we found the reason: one of the stars position on the CCD was set (in the PlatoSim output hdf5 file) as being outside the limits of the CCD.
I used the default size of 100x100 pixels CCD and the star was located at: (104.8 x -0.2)
The question is if there is any reason why such star might have been was selected ?
In case this is a bug that you might want to look at in more detail let me know and I can provide the star positions too (from the star catalog)
![screenshot from 2018-02-23 15-35-39](https://user-images.githubusercontent.com/18440862/36599284-37eede30-18af-11e8-9393-2e20fb429e4f.png)

**Comment by JorisDeRidder** [comment]
Could you please post the input yaml file, and the (ra, dec) coordinates of the star?

**Comment by dk766** [comment]
Here is the catalog that I use. The PlatoSim input configuration file is the default. The only changed parameter is the starcatalog.

A note for the starId: I think you assume that the starID is a number. For now it is but the PIC ID will probably change into an alphanumeric string so it would be ideal if PlatoSim would support that (sorry for not noticing this earlier)

[starcatalog_test.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/1761920/starcatalog_test.txt)

**Comment by SaraRegibo** [comment]
This has probably due to the fact that we were rounding the sub-pixel coordinates when checking whether the reside inside the sub-field.  We have corrected this in pull request #241 (to be merged).

**Comment by SaraRegibo** [comment]
Closed by #241

**Comment by SaraRegibo** [comment]
@dk766 Can you confirm that is no longer a problem since #241?  Just fetch the latest version from the develop branch.  If it works, please, re-assign this issue to me again and I will fix it in the master.  Thanks!

**Comment by dk766** [comment]
I rerun the test and I confirm that all the start positions are within the boundaries of the CCD (>0 and <100)

I did had also a note regarding the starID as a string. As this is outside of the scope of this issue I did not test it. If it was not implemented though it should be recorded, perhaps in a new issue ?
