### ISSUE TITLE
Cosmics do not seem to affect the offset rows

### ISSUE THREAD

**Issue by dk766** [IvS-KULeuven/PlatoSim3#245]
I a few simulations with various cosmic rates (up to 100000 see the attached config) and none seem to affect the offset rows.

Note: I run with a different starcatalog but this should have no effect over the cosmics.

My PlatoSim3 version is : PlatoSim v3.2.0-RC1-385-g3f28479

[offset_inputfile_100000.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/1797386/offset_inputfile_100000.txt)

**Comment by JorisDeRidder** [comment]
Are we talking about the bias map or the smearing map? If bias map: we indeed do not add cosmics here, because the pixels are very "short-lived" (serial pre-scan). For the smearing map there should be cosmics, although few, because the probability of a cosmic there scales with the readout time.

**Comment by dk766** [comment]
I refer to the BiasMaps. It is true that the serial readout is very short lived (few ms or tens of ms) however at high rates cosmics can still affect it. 
We have a Offset Outlier Detection algorithm specifically for this (rare cases) so it would be great if PlatoSim could also support this. This used to be the case (but the number of cosmics for both pre-scan and over-scan were too high as reported in #206). There was a fix that corrected the smearing (over-scan) but not the pre-scan (Bias Maps).

**Comment by JorisDeRidder** [comment]
I would need to talk first to the CCD folks then, because I'm not sure what a cosmic in a serial pre-scan actually looks like. They're unlikely the same shape as in the normal exposure area.

**Comment by dk766** [comment]
Yes, I definitely agree that think this would be the best approach; actually I think I was suggesting the same in #206

**Comment by JorisDeRidder** [comment]
I talked to Jason about this, and we now know how to implement this. I'll contact you with a private follow-up email, because Jason's explanation made me doubt a bit that this is what you really need/want.  :-)
