### ISSUE TITLE
some issues with the charge diffusion implementation

### ISSUE THREAD

**Issue by BertoltLang** [IvS-KULeuven/PlatoSim3#247]
Unfortunately we couldn't reproduce the expected results with the new implementation. There are some issues with the functionality and the code in its current state:

1. the function void DetectorWithMappedPSF::applyDiffusionKernel() declares the input values subpixRow and subpixCoulumn as int - they should be double, or ox and oy will always be zero.

2. As far as I can see the diffusionKernel keeps his values over time and gets normalized only. The kernel should be created newly for each time flux is applied, so its values should be put to zero after using it. Normalization isn't needed.

It seems to me, that the introduction of the diffusionKernel creates more fuss than usability. Would you consider changing the implementation of charge diffusion a bit more to the template? Though, your version is easier to read and more understandable, I think the code would be more compact and efficient.

**Comment by JorisDeRidder** [comment]
Sara implemented and tested this code. She is returning on Monday and will surely address this issue. I admit that we are quite often sacrificing compactness, and sometimes even a bit of efficiency. But we're already dealing with 15000 lines of code, and the code is growing every month. So object-oriented design, consistency with the existing code, readability and maintainability are quite high on our priority list. Nevertheless, apologies if we didn't properly use your template code. We'll look into it.

**Comment by SaraRegibo** [comment]
I am back and looking into this issue.
(1) Agreed.  Fixing this right now.
(2) The method `applyDiffusionKernel` is called (`Camera::exposeDetector` -> `DetectorWithMappedPSF::addFlux` -> `DetectorWithMappedPSF::applyDiffusionKernel`) every time flux is added to the current exposure (for each source, for each jitter step, etc.).  Here, I create (each time) a new `signalReponse` of the appropriate (and fixed over time) size and call the `addPart` method on this.  Based on this, I can extract the diffusion kernel.  It is true that the latter is not reset (i.e. I don't set the values to zero after each call), but I do over-write all elements in it, so it is not constant over time.

**Comment by SaraRegibo** [comment]
I see now that the normalisation is indeed not necessary.  I did not realise this was done in the `()` operator.  Deleting the line of code that did the normalisation....

**Comment by SaraRegibo** [comment]
Bertolt, I am re-assigning the issue back to you to check the content of pull request #248.
* The sub-pixel row and column are not doubles instead of integers
* I've omitted the normalisation, since this is already taken care of by the `()`-operator of the `IntegralOfAnalyticSignalResponse` class.
However, each time flux is applied, the diffusion kernel is not reset to zero, but all its elements are over-written with new values (double `for`-loop starting on line 541 in the `DetectorWithMappedPSF` class).

**Comment by BertoltLang** [comment]
I see your point with the overwriting of the kernel and will test the new implementation on thursday.

Thank you for looking into the issue. I will close this, as soon, as I tested it.

**Comment by BertoltLang** [comment]
I just conducted a simulation with the changes from pull request #248 and got exactly the results I was expecting - thank you Sara! I will close this issue.
