### ISSUE TITLE
Error during compilation

### ISSUE THREAD

**Issue by manugr788** [IvS-KULeuven/PlatoSim3#26]
Hi,

I have just updated Platosim3 from grithub (git pull origin master).
When I try to compile with a basic ./install.sh command, I get an error : 

[ 65%] Building CXX object CMakeFiles/platosimLibrary.dir/source/UnsupportedException.cpp.o
/obs/grolleau/git/PlatoSim3/source/SkyCoordinates.cpp: In function ‘std::vector<double> angularDistanceBetween(double, double, const std::vector<double>&, const std::vector<double>&, Unit)’:
/obs/grolleau/git/PlatoSim3/source/SkyCoordinates.cpp:222:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
/obs/grolleau/git/PlatoSim3/source/StarCatalog.cpp: In member function ‘StarRecord StarCatalog::operator[](unsigned int) const’:
/obs/grolleau/git/PlatoSim3/source/StarCatalog.cpp:138:63: **error: ‘out_of_range’ was not declared in this scope**
/obs/grolleau/git/PlatoSim3/source/StarCatalog.cpp: In member function ‘StarCatalog StarCatalog::getStarsWithinRadiusFrom(double, double, double, Unit)’:
/obs/grolleau/git/PlatoSim3/source/StarCatalog.cpp:188:48: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-deprecated-register" [enabled by default]
make[2]: **\* [CMakeFiles/platosimLibrary.dir/source/StarCatalog.cpp.o] Error 1
make[2]: **\* Waiting for unfinished jobs....
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-deprecated-register" [enabled by default]
make[1]: **\* [CMakeFiles/platosimLibrary.dir/all] Error 2
make: **\* [all] Error 2

FYI :
gcc --version
gcc (Debian 4.7.2-5) 4.7.2

**Comment by JorisDeRidder** [comment]
I updated the code. Can you retry compilation with the latest version, and let me know the result?

**Comment by manugr788** [comment]
Everything is OK now, many thanks Joris.
