### ISSUE TITLE
bug when using demo_fgs.py with field distortion

### ISSUE THREAD

**Issue by BertoltLang** [IvS-KULeuven/PlatoSim3#280]
When starting a series of simulations with the python script demo_fgs.py with field distortion activated the script crashes. I think the reason behind this is a bug within simulation.py. 

I had to change the lines 637 to 639 from:

        if (self["Camera/IncludeFieldDistortion"] == "yes")  or (self["Camera/IncludeFieldDistortion"] == "1"):
            includeFieldDistortion = True
            distortionCoefficients = sim["Camera/FieldDistortion/ConstantCoefficients"]

to:

        if (self["Camera/IncludeFieldDistortion"] == "yes")  or (self["Camera/IncludeFieldDistortion"] == "1" or (self["Camera/IncludeFieldDistortion"] == True)):
            includeFieldDistortion = True
            distortionCoefficients = self["Camera/FieldDistortion/ConstantCoefficients"]

After that I could start the simulations.

Kind regards,

Bert

**Comment by SaraRegibo** [comment]
Implemented in 
* `develop`: #281 
* `master`: #282

**Comment by SaraRegibo** [comment]
Assigning back to @BertoltLang for closure.

**Comment by BertoltLang** [comment]
thank you!
