### ISSUE TITLE
Backward compatibility to the configuration files ?

### ISSUE THREAD

**Issue by dk766** [IvS-KULeuven/PlatoSim3#292]
As more features are added to Platosim the configuration file (inputfile.yaml) requires sometimes a refactoring not only to accomodate the new parameters but also to reorganize the existing ones in different logical entities. 
This is a perfectly normal evolution but generates a few issues one of the most important one being that rerunning an older simulations (a new Platosim with an old config file) is no longer possible. 
Sometimes a simple diff is enough to identify the problem but if the changes are extensive this will not suffice.

So what we would need is either some kind of "backward compatibility" within Platosim or a some kind of independent migration tool that can upgrade an old configuration file to a new version (by taking the old info and set some meaningfull defaults for the newly introduced parameters).

The minimum thing that should probably be implemented now would be to add in each configuration file a version parameter. When a new Platosim (with modfied config files structure) is released the default version should be increased.

In this way at runtime Platosim will know which versions of configuration can process and can inform the user if a wrong (too old) inputfile.yaml is used.

**Comment by JorisDeRidder** [comment]
In the Python folder we have a python script `migtool.py` that was exactly designed for the use case you mention. It is run using:
```
$ python migtool.py old_inputfile.yaml new_inputfile.yaml
```
It requires an inputfile.yaml from an old release and an inputfile.yaml from a newer PlatoSim release. It will compare the two, remove obsolete keys from the old one, add the new keys with their default values taken from the more recent yaml file. The updated configuration will be saved in a 3rd yaml file. At the moment the comments behind the configuration parameters are unfortunately not conserved (working on that) but it should get you going. 

We're of course open to any suggestion to facilitate the transit from one version of PlatoSim to the next.  The idea to include a version number in the yaml file is probably a good one, as it can indeed lead to more meaningful error messages. We'll look into it.

**Comment by SaraRegibo** [comment]
Added information on the migration tool on the documentation in the `develop` branch (pull request #300 ).  This means that it can only be viewed in `/docs/html` (so locally), rather than on the documentation pages.
