### ISSUE TITLE
inconsistency in star position output

### ISSUE THREAD

**Issue by BertoltLang** [IvS-KULeuven/PlatoSim3#294]
Dependent on which method of psf integration is chosen, the output in the hdf5 file for the single exposures in "StarPositions" is different. When using a mapped PSF, the values for colPix and rowPix are the pixel values within the CCD coordinate system, while with an anlytic PSF approach they depict the star position within the subfield reference frame. This should be fixed to avoid confusion.

**Comment by JorisDeRidder** [comment]
Thanks for the report! We'll look into this.

**Comment by SaraRegibo** [comment]
Pinpointed the problem to the `addFlux` method in `DetectorWithMappedPSF`, where the sub-field zeropoint is not subtracted from the pixel coordinates, in contrast to the `addFlux` method in `DetectorWithAnalyticGaussianPSF` and `DetectorWithAnalyticNonGaussianPSF`.

I will add the subtraction in `DetectorWithMappedPSF`.

**Comment by SaraRegibo** [comment]
Solved in `develop` by pull request #299.  Assigning to @BertoltLang for closure.

**Comment by BertoltLang** [comment]
Thank you.

**Comment by manugr788** [comment]
May you push this correction into the Master branch. I have just try to run Platosim 3.3.4 Master branch once with Model=MappedFrom, once with Model=AnalyticalGaussian and I got the same inconsistency as described by Bert.

**Comment by SaraRegibo** [comment]
Solved by pull request #309 and will by installable via conda as version 3.3.5.

@manugr788 Can you check and close this issue if it is solved, please?

**Comment by manugr788** [comment]
Checked and validated for version 3.3.5 (master branch).
