### ISSUE TITLE
Using varsources doesn't generate expected output 

### ISSUE THREAD

**Issue by dk766** [IvS-KULeuven/PlatoSim3#295]
I am running a simulation with 1 single star. I am trying to insert a transit using the variable sources (see my attached configuration) but the generated simulation (and extracted LC) does not seem to contain the injected transit (which for the purpose of this test is exagerately large so it should be easily visible in the generated LC). 

To be able to upload to GitHub  I renamed inputfile.yaml to inputfile.txt.

[inputfile.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/2438075/inputfile.txt)
[starcatalog_onestar.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/2438077/starcatalog_onestar.txt)
[varsource.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/2438078/varsource.txt)
[Sun+50pctDepth_1AU_noise1000e-6_delta-mag10.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/2438079/Sun%2B50pctDepth_1AU_noise1000e-6_delta-mag10.txt)

**Comment by rhuygen** [comment]
Thanks for the report, I will look into this.

**Comment by dk766** [comment]
Actually this behaviour is different from the one I got: in my case the simulation run just that the output simulation did not seem to contain the injected transit ...

**Comment by rhuygen** [comment]
Issue #297 was just a mal configuration from my side that resulted in the segmentation fault. The input that you provided is ok and I have planned to run the simulation and look into your problem in the next days.

**Comment by rhuygen** [comment]
The problem is an incorrect format for file containing the variable time series, i.e. ``Sun+50pctDepth_1AU_noise1000e-6_delta-mag10.txt``. The file should have two columns, time [s] and delta_mag. The columns shall be separated by blanks and not commas. When I corrected the time series file, the lightcurve for pixel 5,5 in the exposures cube looks like below.

![pixel5-5](https://user-images.githubusercontent.com/6662864/46661541-b4f2cf00-cbb9-11e8-8025-b082c57e36b1.png)

**Comment by dk766** [comment]
Great, thanks for looking into the problem. Indeed this is the expected shape that we also expected to see.

In order to avoid similar user configuration problems it would be great if Platosim could treat these cases in a more user-friendly way: either accept a range of colum separators (like comma, semi colon, space, tab, pipe etc) or if we want to be more strict to simply inform the user when the number of expected columns is missing. This would help other users to do the same mistake and would give them better tools to identify the problem by themselves.

**Comment by rhuygen** [comment]
I agree, I'll pick this up in another issue, can you close this issue if it solves your problem?

**Comment by dk766** [comment]
I corrected the configuration file and rerun the test and my results are still not correct. 
![figure](https://user-images.githubusercontent.com/18440862/47154706-52997d00-d2e3-11e8-9d3f-7f86dbc857f0.png)

I will attach my configuration files and my script to generate the lc.
[inputfile.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/2491895/inputfile.txt)
[starcatalog_onestar.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/2491899/starcatalog_onestar.txt)
[Sun_1AU.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/2491902/Sun_1AU.txt)
[varsource.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/2491903/varsource.txt)

If blank is teh separator needed in the stellar variability file pls correct the documentation http://ivs-kuleuven.github.io/PlatoSim3/SupplementaryFiles.html#stellarVariability which asks for a comma-separated file.

The python script that I use to extract the LC is (pls. rename to extract_lc.py):
[extract_lc.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/2491930/extract_lc.txt)

My current PlatoSim is: v3.2.0-RC1-542-g60c8a16

**Comment by rhuygen** [comment]
I'll have a look at this...

**Comment by rhuygen** [comment]
I'm looking into this, but do not understand your configuration. Your PlatoSim3 is Release 3.2.0, but the stellar variability is only implemented since 3.3.0. Could you please update to the latest Release of PlatoSim3, i.e. 3.3.4 and re-run your simulation? We can then continue the investigation. Thanks, Rik.

**Comment by dk766** [comment]
I may do something wrong but I don't quite see what, maybe you can advice me ?
I understand that you use something similar to gitflow for development so a master for releases and a develop branch where all the features go (so develop branch contain always "the newest changes").
I am currently on develop branch:
```
$ git status
On branch develop
Your branch is up-to-date with 'origin/develop'.
$ git fetch
$ git pull
Already up-to-date.
```
After compiling in the build folder I run:
```
./platosim -version
PlatoSim v3.2.0-RC1-542-g60c8a16
```

Am I on the wrong branch ?

**Comment by rhuygen** [comment]
Can you put the output of the following command here?

```
git remote -v
```

**Comment by dk766** [comment]
```
$ git remote -v
origin  git@github.com:IvS-KULeuven/PlatoSim3.git (fetch)
origin  git@github.com:IvS-KULeuven/PlatoSim3.git (push)

$ git branch -r
 origin/HEAD -> origin/develop
 origin/alphaRelease
 origin/develop
 origin/gh-pages
 origin/master
```

**Comment by dk766** [comment]
Also note that since I had some compiler related problems I am using the attached install.sh and CMaleLists.txt files (also provided by PlatoSim team but not part of the git repository)
[CMakeLists.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/2514593/CMakeLists.txt)
[install.sh.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/2514598/install.sh.txt)

**Comment by rhuygen** [comment]
Let's debug your PlatoSim3 version/installation off-line. I suggest that you start using the conda distribution of PlatoSim3, see Installing PlatoSim3 via Conda at http://ivs-kuleuven.github.io/PlatoSim3/ViaConda.html

For the problem that you encounter with the stellar variability, the first thing to do is remove the first line in the ``Sun_1AU.txt`` file. We do not support comment lines in that file yet. I extracted the following lightcurve with your ``extract_lc.py``.

![lc](https://user-images.githubusercontent.com/6662864/47499045-3ce60380-d85f-11e8-9dd5-21aaf422c7ee.png)

**Comment by dk766** [comment]
Problem was solved. I can confirm that varsources are correctly used by PlatoSim

**Comment by rhuygen** [comment]
All right, thanks.

**Comment by rhuygen** [comment]
As far as I understood, also the PlatoSim3 installation and git problem was solved.
