### ISSUE TITLE
SkyBackground value

### ISSUE THREAD

**Issue by manugr788** [IvS-KULeuven/PlatoSim3#304]
Hi,

Do you know what is the computation behind this sentence (in PLATO-KUL-PL-TN-003):
"The background signal amounts 100 e-/pixel/s, a value that is taken from [AD-1] - [AD-6] (req. 160), which corresponds to a value of 342 photons/pixel/s".

We need this formula to compute light curves from Platosim imagette since within platosim configuration file we get the value in photons (342) but we need to use the value in electron (100) to build the binary mask.

Moreover, when running a computation with PLATOSIM using SkyBackground=342 photons/pixel/s, we get within the output file a constant background value of 5861 which I assume to be in e-/exposure, so we expected 100 * 25 = 2500, I have obviously missed something ?

Emmanuel

**Comment by SaraRegibo** [comment]
These values were taken from the PLATO System Parameters, Req. 160:

`160, background signal, ph/pix/s,                               342             , RD13, D, corresponds to 100 
e-/pix/s`

---

I try to reproduce this conversion with the formulae and numbers from PLATO-DLR-PL-RP-001 (Instrument Noise Budget):
 
From Eq. 4-7 (without multiplying with t_exp):
 
```
# background photons [photons / s / pixel]
 = # background e- [pe- / s / pixel] * E * mean(T_optics(i) * T_filters(i) * QE(i))
```
 
 
Taking the numbers from Table 4-4:
 
```
# background photons [pe- / s / pixel]
= 100 * / [(0.987 * 0.989 * 0.980 * 0.957 * 0.993 * 0.945) * 0.382]
= 100 / 0.328
= 309
```
 
which is not exactly 342 photons / s / pixel, but close enough(?)...  I asked Anko about the missing photons, but I never got an answer...

**Comment by JorisDeRidder** [comment]
Hi @manugr788 Can we close this issue?
