### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by drsamadi** [IvS-KULeuven/PlatoSim3#305]
Hi,
I have followed the installation procedure published here
http://ivs-kuleuven.github.io/PlatoSim3/Building.html

The compilation failed, nothing is generated in  the folder build/
I have executed the following command: ./install.sh > output.txt 2> errors.txt

I attach here the files generated.
[output.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/2472219/output.txt)
[errors.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/2472220/errors.txt)

Some information about my system:
gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0

cmake version 3.10.2

clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

**Comment by JorisDeRidder** [comment]
Which version did you try to install: the latest `master` or the latest `develop` version?

**Comment by drsamadi** [comment]
Hi Joris,
this is Master

**Comment by drsamadi** [comment]
Below is the results of the command make -j 4  (from http://ivs-kuleuven.github.io/PlatoSim3/Building.html)

[ 90%] Built target platosimLibrary
[ 95%] Linking CXX executable testplatosim
[ 95%] Linking CXX executable platosim
libplatosimLibrary.a(ConfigurationParameters.cpp.o): In function `ConfigurationParameters::getIntegerVector(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
ConfigurationParameters.cpp:(.text+0x4fcc): undefined reference to `YAML::detail::node_data::convert_to_map(boost::shared_ptr<YAML::detail::memory_holder>)'
libplatosimLibrary.a(ConfigurationParameters.cpp.o): In function `ConfigurationParameters::getDoubleVector(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
ConfigurationParameters.cpp:(.text+0x70fb): undefined reference to `YAML::detail::node_data::convert_to_map(boost::shared_ptr<YAML::detail::memory_holder>)'
libplatosimLibrary.a(ConfigurationParameters.cpp.o): In function `YAML::Node YAML::Node::operator[]<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
ConfigurationParameters.cpp:(.text._ZN4YAML4NodeixINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEES0_RKT_[_ZN4YAML4NodeixINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEES0_RKT_]+0x3c1): undefined reference to `YAML::detail::node_data::convert_to_map(boost::shared_ptr<YAML::detail::memory_holder>)'
libplatosimLibrary.a(ConfigurationParameters.cpp.o): In function `YAML::detail::node& YAML::detail::node_data::get<int>(int const&, boost::shared_ptr<YAML::detail::memory_holder>)':
ConfigurationParameters.cpp:(.text._ZN4YAML6detail9node_data3getIiEERNS0_4nodeERKT_N5boost10shared_ptrINS0_13memory_holderEEE[_ZN4YAML6detail9node_data3getIiEERNS0_4nodeERKT_N5boost10shared_ptrINS0_13memory_holderEEE]+0x4d6): undefined reference to `YAML::detail::node_data::convert_to_map(boost::shared_ptr<YAML::detail::memory_holder>)'
collect2: error: ld returned 1 exit status
CMakeFiles/testplatosim.dir/build.make:95: recipe for target 'testplatosim' failed
make[2]: *** [testplatosim] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/testplatosim.dir/all' failed
make[1]: *** [CMakeFiles/testplatosim.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
libplatosimLibrary.a(ConfigurationParameters.cpp.o): In function `ConfigurationParameters::getIntegerVector(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
ConfigurationParameters.cpp:(.text+0x4fcc): undefined reference to `YAML::detail::node_data::convert_to_map(boost::shared_ptr<YAML::detail::memory_holder>)'
libplatosimLibrary.a(ConfigurationParameters.cpp.o): In function `ConfigurationParameters::getDoubleVector(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
ConfigurationParameters.cpp:(.text+0x70fb): undefined reference to `YAML::detail::node_data::convert_to_map(boost::shared_ptr<YAML::detail::memory_holder>)'
libplatosimLibrary.a(ConfigurationParameters.cpp.o): In function `YAML::Node YAML::Node::operator[]<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
ConfigurationParameters.cpp:(.text._ZN4YAML4NodeixINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEES0_RKT_[_ZN4YAML4NodeixINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEES0_RKT_]+0x3c1): undefined reference to `YAML::detail::node_data::convert_to_map(boost::shared_ptr<YAML::detail::memory_holder>)'
libplatosimLibrary.a(ConfigurationParameters.cpp.o): In function `YAML::detail::node& YAML::detail::node_data::get<int>(int const&, boost::shared_ptr<YAML::detail::memory_holder>)':
ConfigurationParameters.cpp:(.text._ZN4YAML6detail9node_data3getIiEERNS0_4nodeERKT_N5boost10shared_ptrINS0_13memory_holderEEE[_ZN4YAML6detail9node_data3getIiEERNS0_4nodeERKT_N5boost10shared_ptrINS0_13memory_holderEEE]+0x4d6): undefined reference to `YAML::detail::node_data::convert_to_map(boost::shared_ptr<YAML::detail::memory_holder>)'
collect2: error: ld returned 1 exit status
CMakeFiles/platosim.dir/build.make:96: recipe for target 'platosim' failed
make[2]: *** [platosim] Error 1
CMakeFiles/Makefile2:141: recipe for target 'CMakeFiles/platosim.dir/all' failed
make[1]: *** [CMakeFiles/platosim.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by JorisDeRidder** [comment]
We're currently looking into this. Meanwhile you could use `conda` to download a pre-compiled version of Platosim. The steps are described in http://ivs-kuleuven.github.io/PlatoSim3/ViaConda.html and are summarized below:

```
$ conda create -n platosim python=3.5 anaconda
$ source activate platosim
$ conda config --add channels conda-forge
$ conda install -c http://<username>:<password>@www.miricle.org/platosim/ platosim
```
after which you can simply launch platosim with the command `platosim` on the command line. I will email you the username and password separately.

**Comment by rhuygen** [comment]
Hi Reza,

from the email (referenced below) we understand that you are now able to compile platosim. We would however like to have a smooth installation for all and would like to find the cause of your original problem. Also, because now you have the executables and libraries in your platosim root instead of the build directory.

Could you provide me with the following information:

* a list of the build directory after the failed 'cd build ; make .. ; make -j 4' or better a tar-ball of the content of that directory
* the output of 'echo $PATH’

Thanks, Rik 

```
Hi Joris,

I've finally solved the problem. I don't know exactly how.

I have removed form my system a package libyaml-ccp-dev  but I'm not sure that the problem was link to this package.

By the way the following commands given in ghttp://ivs-kuleuven.github.io/PlatoSim3/Building.html
>    1 cmake ..
>    2 (make clean)
>    3 make -j 4
do no work, here is the message I get:
>	CMake Error: The source directory "/ho	me/reza/plato> algorithms /tools/platosim" does not appear to contain >CakeLists.txt.
>	Specify --help for usage, or press the help button on the CMake
>GUI.

In the script install.h, the following commands also do not work:
> cd build
> cmake ..
> make -j 4
I get:
-- Git current branch: master
-- Git describe: 3.3.4
-- CMake source dir: /home/reza/plato/algorithms/tools/platosim/platosim3
-- CMake current source dir: /home/reza/plato/algorithms/tools/platosim/platosim3
-- CMake binary dir: /home/reza/plato/algorithms/tools/platosim/platosim3
-- Generating version.h
-- Configuring done
-- Generating done
-- Build files have been written to: /home/reza/plato/algorithms/tools/platosim/platosim3
reza@maya:~/plato/algorithms/tools/platosim/platosim3/build$ make -j 4
make: *** No targets specified and no makefile found.  Stop.


Finaly typing the following commands in the root directory works well:

> cmake .
> make -j 4

```
