### ISSUE TITLE
Improved treatment of large star input catalogs

### ISSUE THREAD

**Issue by JorisDeRidder** [IvS-KULeuven/PlatoSim3#306]
There is currently a limit on the size of the star input catalogs that can be read, which is particular relevant for full frame simulations. We can improve by only reading the part of the star catalog file relevant for the FOV, assuming that the drift is not too dramatic during the time series.

**Comment by nicholasjannsen** [comment]
Is this still a problem? I have made full-frame simulations with the entire LOPS1 and LOPN1 (i.e. more than 100,000 stars) before and it worked perfectly fine.
