### ISSUE TITLE
Improve documentation on supplementary input files of PlatoSim

### ISSUE THREAD

**Issue by JorisDeRidder** [IvS-KULeuven/PlatoSim3#308]
In the section http://ivs-kuleuven.github.io/PlatoSim3/SupplementaryFiles.html#stellarVariability the sentence currently reads "The latter files also consist of two comma-separated columns:" while it should read "The latter files consist of two columns, separated by a space:".

**Comment by SaraRegibo** [comment]
Solved in:
* `master`: #311 
* documentation pages: #312 
* `develop`: #315
