### ISSUE TITLE
Jitter default parameter

### ISSUE THREAD

**Issue by dk766** [IvS-KULeuven/PlatoSim3#317]
On a comment of the Issue #316 
> ... The corresponding RMS of the yaw, pitch, and roll in the inputfile is set to a generative 1.0, but the Plato spacecraft will do much better in fact. Can you redo your simulations with JitterYawRms, JitterPitchRms, and JitterRollRms set to 0.05?

it is stated that the default values for the Jitter settings are not consistent with the expected performance of the Plato spacecraft. 

Please set as default values for the PlatoSim input configurations parameters values that shall produce CCD images similar to the ones expected to be obtained from the Plato spacecraft.

**Comment by JorisDeRidder** [comment]
Will do. But note that not only the values of the RMS are relevant but also the distribution of the pointing perturbations, which may not be exactly the AR(1) process that we are currently using in the simulation. This can affect the profile in the frequency domain. This is why PlatoSim allows for a jitter input file to feed the simulations with jitter perturbations obtained from an engineering model that includes the FGS stabilizing feedback loop. I will contact DLR what the most recent version is that they are currently using. 

Also, please consider what is most relevant for your application: the expected jitter performance, or the worst case jitter performance specified by the requirements.

**Comment by dk766** [comment]
I think the PlatoSim approach (which allows external input files as well as internally implemented jitter algorithms) is very good and flexible enough. Regarding the other perturbations (e.g. pointing) the same approach should be followed: the default value should be as close as possible to the expected PLATO spacecraft generated images.

Either the expected performance or worst case acceptable performance are acceptable as long as we are consistent (although I personally would vote for a "typical" PLATO image so an expected performance as default). 

It would also be useful for the PlatoSim users if the meaningful values (expected performance, worst acceptable performance etc.) would be easily available either as a comment directly in the configuration file (although this would probably make the configuration unnecessarily large) or as a comment in the configurations user manual (and website).

**Comment by nicholasjannsen** [comment]
As to this issue I think we can safely close since each of the input parameters are tried to be updated with the PLATO parameter database as the mission progress. Since these parameters change all the time, I would argue that the user (which as part of the Consortium and thus also has access to these parameters)  should fetch these parameters for different usage cases.  

Regarding  second comment of @dk766 this has been implemented using the LOPS1 as default.
