### ISSUE TITLE
Remove python 3.5 dependency

### ISSUE THREAD

**Issue by PierreRoyer** [IvS-KULeuven/PlatoSim3#318]
Platosim has currently a dependency on python 3.5. It would be really appreciated to remove that dependency and allow for python > 3.5. Sara has already verified that all tutorials run under python 3.7

**Comment by JorisDeRidder** [comment]
We'll change the Jenkins requirement from == 3.5 to >= 3.5.
We'll also consult other users to what extend moving to Python 3.7 would impact them.

**Comment by dk766** [comment]
As PlatoSim sometimes runs on servers where a more conservative approach with regards to newer libraries is usually followed I would propose to only switch from == 3.5 to >= 3.5 rather than jump directly to 3.7

**Comment by BertoltLang** [comment]
I see it the same way as Valerian.

**Comment by WimDeMeester** [comment]
The platosim conda installation needs h5py to be installed. h5py for python 3.7 only works for hdf 1.8.18, 1.8.20, 1.10.2 or 1.10.3. At this moment, platosim installs version 1.8.16 of hdf5. To be able to make platosim work with python 3.6 and / or 3.7, I request to update hdf5 to one of the supported versions.

**Comment by SaraRegibo** [comment]
Tested HDF5 1.10.2.  Building and running PlatoSim works fine.

Required (for now in `develop` only):
* download `tar.gz` file from  https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.2/src/
* update package name in `install_hdf5.py` to `hdf5-1.10.2`
* in `CMakeLists.txt`:  update line 70 & 110
* send email to users (that install PlatoSim via GitHub) to tell them they need to re-install HDF5 (and how they have to do that)

At a later stage we will have to roll out these changes to `master`.

**Comment by WimDeMeester** [comment]
A jenkins build was made successfully. When platosim.devel is installed using anaconda, the new version of hdf5 (1.10.2) is installed. This makes sure that python 3.5, 3.6 and 3.7 can be used.

**Comment by SaraRegibo** [comment]
Everything is in place for the manual installation of version 1.10.2 of HDF5.  See #322.

Only remaining action: inform the users.

**Comment by SaraRegibo** [comment]
Users informed.

Assigning to @PierreRoyer  for closure.

**Comment by PierreRoyer** [comment]
Tested in development track under python 3.7.
Thanks for the quick solution!
