### ISSUE TITLE
Sky background in electrons

### ISSUE THREAD

**Issue by JorisDeRidder** [IvS-KULeuven/PlatoSim3#319]
Currently the sky background is given in photons/exposure. Provide a measure for the sky background in electrons. Since the background value in electrons varies over the CCD, it is to be determined what exactly should be computed. Possible options are e.g. sky background in the center of the subimage, an average value over the subimage, or at the position of each star. This will not matter for small imagettes, but may differ for larger subimages. 

For the rationale, see issue #313.

**Comment by SaraRegibo** [comment]
During a discussion with DLR (28/7/2020) it was decided that the input value for the sky background should be specified in e-/pixel/s, as this is consistent with the requirement (from PLATO-INAF-TOU-REP-0010).

**Comment by Dries-Seynaeve** [comment]
This is not possible for large simulations, since the sky background (in electrons) is not necessarily constant for the entire subfield.
