### ISSUE TITLE
incorrect sky background level 

### ISSUE THREAD

**Issue by drsamadi** [IvS-KULeuven/PlatoSim3#325]
I've discovered a problem still regarding the amount of sky background.

In one of my simulation, I measure in the image a sky background of about 2000 e-.
Given my configuration file (here attached), this is consistent, however the contribution of the background flux collected during the frame transfer is missing.
For instance, assume a sky background of 100 e-/s, the amount of background collected during the integration is obviously 2100 e-, but one must also take into account the amount of background collected during the transfer time (4s), accordingly the background should be equal to 
 2500 e-. 
Réza

PlatoSim 3.3.5

[PSMOB-TC-OSC-001-COB_000.yaml.gz](https://github.com/IvS-KULeuven/PlatoSim3/files/2584461/PSMOB-TC-OSC-001-COB_000.yaml.gz)

_Originally posted by @drsamadi in https://github.com/IvS-KULeuven/PlatoSim3/issue_comments#issuecomment-438969341_

**Comment by SaraRegibo** [comment]
Hi Réza, thanks for spotting this!  This should be corrected, indeed.

* Normal cam: background accumulated during readout
* Fast cam: background accumulated over the duration of the frame transfer (no further accumulation during the readout of the lower CCD half, as this is shielded off)

Let me first correct this in the `develop` branch, for you to test.

**Comment by SaraRegibo** [comment]
Solved by pull request #328.  Assigning to @drsamadi for testing in `develop` (and closure).

**Comment by JorisDeRidder** [comment]
Hi Réza, could you have a look at our solution, and see if it indeed resolves the issue your raised?

**Comment by JorisDeRidder** [comment]
If you find any more problems, please let us know.

**Comment by drsamadi** [comment]
Dear Sara,

I finally managed to  check this new implementation (v3.2.0-RC1-607-gc6d99c6).
If the sky background is now closer to the expected value, I get some strange results.

My simulation is a 6x6 imagettes and contains a very very faint star (magnitude 100!  just to be sure to be in a situation where they are indeed no stars in my imagette). 
I've plotted my imagette, here attached the figure.
The figure shows a strange structure.
The value of the background in the corner is 3050 e-, it is 3400 e-  in the edge (this is approximatively the expected value) and in the middle (the yellow part) it is not constant but it is around 3800 e-. 
The pixel values are the following: 
      [[ 3050.,  3350.,  3375.,  3400.,  3375.,  3000.],
       [ 3400.,  3775.,  3800.,  3800.,  3775.,  3325.],
       [ 3400.,  3800.,  3800.,  3825.,  3800.,  3350.],
       [ 3400.,  3775.,  3825.,  3825.,  3800.,  3350.],
       [ 3375.,  3800.,  3825.,  3800.,  3800.,  3350.],
       [ 3050.,  3375.,  3375.,  3400.,  3375.,  3025.]],

The value of 3400 e- is very close to the value derived by Emmanuel on the basis of the information given in the YAML file. This calculation is detailed below (can you confirm it?). 
Accordingly,  one expects a background level of 135.800069085  * 25 s = 3395 e-. This is very close to the value I get in the edge of the imagette (3400 e-), but the background level is very different elsewhere and has a strange structure. 

My simulation data set can be downloaded here: 
https://upload.obspm.fr/get?k=JI381J82wUTG3lQi8XW

Gain = 25.025025025   [ADU->e-]
SkyBackground photons/pix/s * Quantum Efficiency * TransmissionEfficiency * polarization = 150.221317974  
SkyBackground = 150.221317974 e-/pix/s  
offset_m = 1000.0   [ADU]
SkyBackground e-/pix/s with Vignetting = 135.800069085  

Cheers,
Réza

![000000000_bkg](https://user-images.githubusercontent.com/19569211/52114432-57710b00-260c-11e9-8808-70022960c54c.png)

**Comment by SaraRegibo** [comment]
Sorry, I lost track of this issue.  After a brief investigation, it turns out that the problem only arises when convolving with either a Gaussian PSF or a pre-computed PSF (from a file):
```
PSF:
     Model:     MappedGaussian/MappedFromFile

CCD:
     IncludeConvolution:     yes
```

In order to (or at least in an attempt to) properly treat the edges of the image upon convolution, we zero-pad the image.  My guess would be that too few zeroes have been added in the padding process...

**Comment by JorisDeRidder** [comment]
To move forward we need to deal with one problem at the time. @SaraRegibo, can you please repeat Réza's experiment with an analytic PSF, and assess whether the sky background is as expected? If not, we need to fix this first. If yes, we can close this issue about the sky background as the problem lays with the convolution. Verify whether the problem still persists with the minimal 8x8 subfields (as specified in the yaml input file and PlatoSim manual) rather than the 6x6 imagettes of above. If yes, please open another issue with a bug report on edge effects when selecting the PSF convolution method. If no, please open another issue requesting a "Code Improvement" to work with smaller imagettes.

**Comment by SaraRegibo** [comment]
With the input provided by @drsamadi I have repeated the simulations with the latest version of the `develop` branch.  I had to run the migration tool to make the original input file compatible with the current implementation.  The resulting `yaml` file is attached, though renamed to a `txt` (you cannot attach `yaml` files here, apparently).  The catalogue is not really relevant here, as I tweaked the configuration parameters to make sure there are no stars in the sub-field.

[inputfile.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/3032955/inputfile.txt)

I ran the simulation as follows:

```
from simfile import SimFile
from simulation import Simulation

outputDir = "/Users/sara/work/Instrumentation/Plato/scripts/issue325/"

sim = Simulation("issue325", configurationFile=outputDir+"inputfile.yaml")
sim.outputDir = outputDir
simFile = sim.run(removeOutputFile = True)
```

The content of the imagette for the 1st exposure (obtained with `simFile.getImage(0)`) is:

```
[[1126 1138 1138 1138 1138 1122]
 [1139 1153 1153 1153 1153 1136]
 [1138 1154 1153 1153 1154 1136]
 [1138 1153 1153 1153 1153 1136]
 [1135 1150 1152 1153 1153 1136]
 [1123 1136 1137 1137 1137 1123]]
```

An estimation of the sky background can be obtained as follows:

```
cycleTime = 25
gain = 25
expectedSkyBackground = sim["Sky/SkyBackground"] * sim["Telescope/TransmissionEfficiency/BOL"] * sim["CCD/QuantumEfficiency/MeanQuantumEfficiency"] * sim["CCD/QuantumEfficiency/MeanAngleDependency"] * sim["CCD/Polarization/ExpectedValue"] * sim["CCD/Contamination/MolecularContaminationEfficiency"] * sim["CCD/Contamination/ParticulateContaminationEfficiency"] * cycleTime / gain + sim["FEE/ElectronicOffset/RefValue"]
```

which yields a value of 1155 ADU/pixel.  This is consistent with the values in the imagettes, away from the edges.  So in conclusion, the calculation of the sky background in PlatoSim is correct, but then something goes wrong with the edges when convolving with the (non-analytic) PSF (see my earlier analysis).

**Comment by SaraRegibo** [comment]
* Not considering the edges: the calculation of the sky background is correct, irrespectively of the PSF that was used for the convolution.
* The problem with the edges is absent when convolving with an analytic PSF.
* Increasing the size of the imagettes from 6 x 6 pixels to 8 x 8 pixels does not resolve the problem.

As suggested above by @JorisDeRidder I will close this issue and open a new one for the edge effects introduced by the convolution with a non-analytic PSF.
