### ISSUE TITLE
incorrect flatfield level

### ISSUE THREAD

**Issue by drsamadi** [IvS-KULeuven/PlatoSim3#326]
In one simulation, I have set FlatfieldPtPNoise = 0.01 (= 1%) 
but I measure a RMS value of 0.002  (=0.2%) in the array 'flatfield/PRNU'

Here attached the simulation data set.

PlatoSim 3.3.5

[PSMOB-TC-OSC-001-COB_000.tar.gz](https://github.com/IvS-KULeuven/PlatoSim3/files/2584503/PSMOB-TC-OSC-001-COB_000.tar.gz)

**Comment by JorisDeRidder** [comment]
The FlatfieldPtPNoise is a value such that the flatfield values are all between 1.0-FlatfieldPtPNoise and 1.0. So it is not an RMS value. Does this answer your question?

**Comment by drsamadi** [comment]
Hi Joris,
yes this partially answer the question, but do you mean then a uniform random value between  1.0-FlatfieldPtPNoise ?
Furthermore, I have to check the CCD specifications, but I think that the PRNU value is understand as a rms value, no ?
Réza

**Comment by drsamadi** [comment]
Here attached the specification for the PRNU. It is clearly understood as a RMS value.

![screenshot from 2018-12-07 11-04-09](https://user-images.githubusercontent.com/19569211/49641242-ddf3dc80-fa0f-11e8-9ddf-6275504c3f71.png)

**Comment by SaraRegibo** [comment]
Hi Réza,
thank you for the attached explanation!

No, we don't use a random uniform distribution in `[1.0-FlatfieldPtPNoise, 1.0]`.  In Fourier space we generate white noise (`N(0,1)`) and include a `1/f` dependency.  We then take the real part of the inverse Fourier transform and do the required scaling.  Only, we did this scaling not as required by CCD-PRN-001...

**Comment by JorisDeRidder** [comment]
OK, it shouldn't be too difficult to adapt PlatoSim to the CCD-PRN-001 requirement. We may have to change the name `FlatFieldPtPNoise` to (e.g.) `FlatFieldNoiseRMS` as the original name would no longer cover its use. This would mean a backward incompatible change to the inputfile.yaml.

**Comment by SaraRegibo** [comment]
Solved in `develop` branch and built by Jenkins.  Closing the issue.
