### ISSUE TITLE
Simulation with too short external jitter file

### ISSUE THREAD

**Issue by dk766** [IvS-KULeuven/PlatoSim3#327]
This is not a bug but rather change request related to #303 

**Context:**
- run a simulation with an external jitter file
- the Jitter file used as input covers a shorter time period as the desired simulation (eg. length 1000s which is about  1000/25 = 40 exposures)
- the length of the simulation (number of exposures * (exposure time + readout time) ) exceeds the time from the input jitter file (e.g. length 5000s = 200exposures)

**Current Befaviour:**
Platosim will generate a simulation containing min(40, 200) = 40 exposures
The time length of the generated simulation will be determined by the minimum of the 2 values (num exp * exposure time and jitter file time length). 

The current behaviour is not ideal since the simulation runs with no error and in case of running multiple simulations in parallel it is difficult notice that the resulting simulation does not contain the desired number of exposures.

**Desired Behaviour:**

At initialization PlatoSim should check the time of coverage of the Jitter file and the simulation and if the jitter file is too short exit with an error message informing the user about this. Ideally Platosim should inform the user how many exposures can be covered by the provided Jitter file in order to make it easier for the user to change the configuration.

**Comment by SaraRegibo** [comment]
In fact not only the jitter file is a potential problem but also the following files need to be checked (in case they are used in the simulation):
- thermo-elastic drift
- focal-plane orientation
- focal length
- field distortion
- temperature file for the FEE
- temperature file for the CCD

**Comment by SaraRegibo** [comment]
To read the last (non-empty) line in a file, we can use `seekg` (see https://stackoverflow.com/questions/11876290/c-fastest-way-to-read-only-last-line-of-text-file).

**Comment by SaraRegibo** [comment]
When configuring the `Simulation`, we calculate the readout time before the next exposure starts.  Together with the exposure time and the number of exposures (and the index of the first exposure!), we can work out how much time we need to cover in the files that are listed above.

We could add a method to `Simulation` that checks the time spanned in the time dependent files that are actually being used in the simulation.
