### ISSUE TITLE
Segfault on running test harness  

### ISSUE THREAD

**Issue by jmccormac01** [IvS-KULeuven/PlatoSim3#329]
Hi,
I am having some issues after installing PlatoSim3. I forked the development version of PlatoSim3 and installed it using ```install.sh```. I then tried running the test harness from the build directory using:

```sh
PLATO/PlatoSim3/build  develop ✗                            
▶ ./testplatosim                                            
[==========] Running 34 tests from 9 test cases.            
[----------] Global test environment set-up.                
[----------] 11 tests from ConfigurationParametersTest      
[ RUN      ] ConfigurationParametersTest.Constructor        
[       OK ] ConfigurationParametersTest.Constructor (0 ms) 
[ RUN      ] ConfigurationParametersTest.readGlobalValues   
[1]    84108 segmentation fault  ./testplatosim                                                               
```

The test harness segfaults right at the beginning. I am rerunning the installation to capture the output and errors as suggested in the troubleshooting section.  I have attached the ```output.txt``` and ```install.txt``` files captured during a reinstall. 

I am running MacOS High Sierra (10.13.6) with the following CMAKE and gcc. 

```sh
▶ cmake --version
cmake version 3.11.1

▶ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

I've not tried to run PlatoSim3 yet as I wanted to be sure the test cases run before trying anything. Any help/advice would be great. Thanks!

[output.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/2620360/output.txt)
[errors.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/2620362/errors.txt)

**Comment by JorisDeRidder** [comment]
Hi James, I'm running the same OS version as you, but up to now I cannot reproduce the problem. Could you try to run PlatoSim? If there is an error message, it may help us to locate the source of the problem.

**Comment by JorisDeRidder** [comment]
You may also opt to try our precompiled binary version of PlatoSim (which is described in the [doc pages](http://ivs-kuleuven.github.io/PlatoSim3/ViaConda.html)) which is meant to save users from any potential installation issues on their local computer system.

**Comment by jmccormac01** [comment]
Hi Joris, Ok, I will try both of those tonight and let you know how I get on. Thanks for your advice.

**Comment by rhuygen** [comment]
Hi James, I don't know if your segfault problem has been solved in the mean time. If not, can we take up this issue again. Can you send me information on your building the dependencies and the PlatoSim. Include as much information as possible, e.g. use 'make -n -d' to print debugging info on make, send the output of the 'set' command, ...

Did you try to run PlatoSim itself instead of ./testplatosim and did that also give a segfault?

Thanks, Rik

PS: After this comment was sent, I could reproduce the segfault in a terminal session where I forgot to setup my PlatoSim environment properly. The Python I was running was version 2.7 and truned out to be an installation by HomeBrew. Could you check that your problem is related to that or not?

PS2: Please check if you have properly set the PLATO_PROJECT_HOME environment variable. I was able to reproduce the segfault by just un-setting this env variable.

**Comment by rhuygen** [comment]
Further tests confirm the segfault originates from the getenv("PLATO_PROJECT_HOME") which returns NULL when the environment variable is not set. The test harness should add a test for this.

**todo**
- [x] Add checks for NULL after every getenv(..) in the test harnesses

**Comment by rhuygen** [comment]
Plkease check PR #338 and close if this solves your problem.

**Comment by jmccormac01** [comment]
Hi Rik, Sorry for the delay on this. I was working on something else urgent, then the break. I will grab the new code and test it this week and let you know/close this issue. Thanks!

**Comment by jmccormac01** [comment]
I fetched the latest version on the develop branch and I get a new error during install from the Camera.cpp code. See below. 

[errors.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/2732627/errors.txt)
[output.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/2732628/output.txt)

**Comment by rhuygen** [comment]
Hi James,

that looks like a compilation error outside of the current issue context. I'm surprised you get this error now and not before. What has changed in your system since the last successful compilation? Did you reinstall or upgrade? Did you installed the dev tools from Xcode?

Also, could you raise a new issue for this since it is not related IMO and that would provide better tracking in the future.

Thanks,
Rik

**Comment by jmccormac01** [comment]
I apolgise for the delay on getting back to this. I've cleaned my platosim installation and started over as I've seen a lot happening with commits recently. I've installed a fresh copy from source. It builds ok, then running the test harness I get the following report:

[test_fail.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/3083534/test_fail.txt)

**Comment by SaraRegibo** [comment]
Hi @jmccormac01 , thanks for getting back to us!  Could you check whether you have exported the required environment variables, please?  You can do this as follows:

```
echo $PLATO_PROJECT_HOME
echo $PLATO_WORKDIR
```

I think these are empty, is that correct?

For information on how to export the environment variables, have a look here: http://ivs-kuleuven.github.io/PlatoSim3/ReqsRun.html.

**Comment by jmccormac01** [comment]
They are indeed empty.

```sh
PLATO/PlatoSim3/build  develop ✔                                           5d   
▶ echo $PLATO_PROJECT_HOME                                                      
                                                                                
                                                                                
PLATO/PlatoSim3/build  develop ✔                                           5d   
▶ echo $PLATO_WORKDIR                                                           

```

Ah, I see, I did not get so far as setting the environment variables in the notes. I installed platosim and immediately ran the test harness. Maybe it would be nice to include a comment [on this page](http://ivs-kuleuven.github.io/PlatoSim3/Building.html) to say that the test harness requires these to be set before it can be run.

**Comment by jmccormac01** [comment]
After setting the correct environment variables I can confirm that the tests pass fine. Thanks for your help on this. It seems like the original segfault issue was solved during an update to the outputing from the test harness and my more recent failed tests were due to the environment variables not being set. I am happy for this to be closed.

**Comment by SaraRegibo** [comment]
Added some documentation as you suggested.  See Pull Requests #363, #364, and #365.

@jmccormac01 If you're happy with the documentation and no longer experience problems with running the test harnesses, you can close this issue.  Thanks!

**Comment by jmccormac01** [comment]
Thanks very much. Closing.
