### ISSUE TITLE
Output file includes unused/misleading input parameters

### ISSUE THREAD

**Issue by BertoltLang** [IvS-KULeuven/PlatoSim3#336]
When a simulation with variable distortion coefficients (fieldDistortionSoure == "FromFile") is conducted the static values from the input .yaml file are saved within the output .hdf5 file. This is true for some input parameters that can be static or variable and can lead to confusion, when the values from the output .hdf5 file are used for e.g. calibrations.
Maybe it would be better to save a mean value or to leave them out of the output file entirely, since no data is better than misleading data.

**Comment by SaraRegibo** [comment]
There are indeed unused variables included in the output file, but I think it is quite straightforward to work out which ones are used and which ones aren't (you only have to look at the values of the `Include<effect>` parameters and the keyword parameters).

Filtering out the unused parameters within the code, would mean that we would have to incorporate a lot of knowledge in the code at the moment the output is written to the file.  This would complicate the code a lot and make maintenance more difficult.

**Comment by SaraRegibo** [comment]
@BertoltLang Would you agree with the analysis?

**Comment by BertoltLang** [comment]
@SaraRegibo Yes I agree, the gain would probably not match the effort and you're correct, that one can always check the Include<effect> variables.
I just think that it would be beneficial for the future in general, to make the output file writing process slimmer and more customizable. For example for our specific purpose, I only need a fraction of the generated data, which I crop from the .hdf5 file with a python script, after the simulation is done. This is necessary to conserve space and is a bit tiresome. 
I completely understand, that this is a low priority request and just wanted to raise attention for future possibilities.
