### ISSUE TITLE
Open-shutter smearing not accounted for

### ISSUE THREAD

**Issue by SaraRegibo** [IvS-KULeuven/PlatoSim3#339]
The problem reported in #325 originated from the incorrect calculation of the readout times in `Simulation`.  This caused the contribution of the open-shutter smearing to be zero (even when open-shutter smearing had been enabled).

Solution:
* In `Simulation`, extract the number of rows in the parallel over-scan and the number of columns in the serial pre-scan from the configuration file (these variables were not initialised before).  This will yield correct values for the readout times, which are passed to `Detector` (and are used in the open-shutter smearing).
* In `Camera` (in the `exposeDetector` method): no longer add the contribution of the sky background (**during readout**), as this is now taken care of by the open-shutter smearing.
* No changes are required in the implementation of the open-shutter smearing in `Detector`.

**Comment by JorisDeRidder** [comment]
Why does the sky background contribution need to be moved?

**Comment by SaraRegibo** [comment]
The contribution of the sky background during exposure remains in `Camera` (in `exposeDetector`).  In the new implementation, the contribution of the sky background during readout should be properly accounted for in the open-shutter smearing (so we no longer have to do this in `Camera`).
