### ISSUE TITLE
A question concerning compressed .hdf5 files

### ISSUE THREAD

**Issue by BertoltLang** [IvS-KULeuven/PlatoSim3#342]
At the moment I'm working with a lot of new psf files which I save within the .hdf5 data format to use them in PlatoSim simulations. Since these input files are huge, I successfully compressed them using gzip compression when creating them. However, I noticed that PlatoSim's ability to deal with compressed .hdf5 data seems to be platform-dependent. On Ubuntu 18.04.1 there were no issues, but when used with Ubuntu 16.04.5 PlatoSim terminates "after throwing an instance of 'H5::DataSetIException'".

Have you too experienced this issue and/or know a solution by chance?

I think it would be great if PlatoSim would be able to deal with compressed .hdf5 data. Maybe the output .hdf5 files could be compressed too, since they also can become pretty large. However, if this really is a platform issue it might not be suitable for PlatoSim.

**Comment by JorisDeRidder** [comment]
Hi Bertolt, 
No experience with that here, I'm afraid. What was the compression ratio you got with gzip?
Our own thinking went along the lines to avoid storing the subimages all-together and do the photometry on the fly.

**Comment by BertoltLang** [comment]
Hi Joris,
thats understandable, especially since the compression ratios for output data wouldn't be that impressive (although this is an assumption, since I dind't test this yet).
For the input psf files I'm using right now, this is a different story. I have achieved conversion ratios around 60, since the psf maps almost excusively consist of zero values.
Anyway, thanks for the reply!
