### ISSUE TITLE
Strange light-curve

### ISSUE THREAD

**Issue by drsamadi** [IvS-KULeuven/PlatoSim3#345]
Dear all,

 I have generated a times-series of imagettes containing a constant star: constant flux, no jitter, no drift, no random noise.

I get the light-curve shown in the first plot.
After about 8500 exposures there is a gap in the light-curve, the gap has a relative amplitude of 3e-5

This is strange. Perhaps I did something wrong, but what?

![no_transit](https://user-images.githubusercontent.com/19569211/52471299-d9bf7900-2b90-11e9-9507-cfc436de8e69.png)

The simulate data set is available for download here: https://upload.obspm.fr/get?k=20DlYQ6cR0aGkQ9PfIo

Réza

**Comment by SaraRegibo** [comment]
Hi @drsamadi ,
could you, please, tell me whether you are using the `master` or `develop` branch?  I'll check whether I can reproduce (and - if so - solve) the issue.

**Comment by drsamadi** [comment]
I think this is 'master' but I'm not sure:

platosim --version
PlatoSim 3.3.4

git branch
  develop
* master

git log 

commit c6d99c6d7d8cbd343ffd3e95d88ca6851a78c080 (HEAD -> master)
Merge: 31f70b5 3f7024b
Author: Réza Samadi <rezouze@gmail.com>
Date:   Fri Feb 1 09:38:36 2019 +0100

    Merge branch 'master' of https://github.com/IvS-KULeuven/PlatoSim3

**Comment by SaraRegibo** [comment]
Ok, thanks.  I had a look at your configuration file and I still need some information from you:

* the star catalogue (`catalogues/rad_vert_intrapix_lv/psim/rad_vert_intrapix_lv000009500.coo`), though I can extract this information  from `000009502_starcoord.dat`
* the PSF file (`psf/June15_normal/white/psf_201506_V2.hdf5`)

**Comment by drsamadi** [comment]
Hi Sara,

you can download this package  (600Mo!) 
https://upload.obspm.fr/get?k=3YDGJeiajkUKE6IQYK0

**Comment by SaraRegibo** [comment]
Thanks for the  auxiliary data, Réza.  Looking into it!

**Comment by SaraRegibo** [comment]
I repeated Réza's simulations and plotted the fluxes of the individual pixels of the imagette. The problem is reproducible.  A few things strike the mind, though:

- when the reported problem arises, the flux drops in steps of exactly 1ADU
- the problem arises at different points in time for different pixels

This problem is likely to be caused by the combination of (to be investigated and confirmed):

- decreasing transmission efficiency over the course of the mission
- flooring the pixel values to integer values (you can only work with whole ADU's!)

Possibility to check this theory:
Make sure the transmission efficiency drops more rapidly (e.g. use 0.01 at EOL) and check:

- for the pixels that had the problem before: does the problem happen sooner now (and more often)?
- are there any additional pixels for which the problem arises now w.r.t. the simulations with the original values? (not necessarily on the timescale of the simulation...)

**Comment by SaraRegibo** [comment]
Flux for pixel (2, 2) with transmission efficiency of 0.01 at EOL:
![image](https://user-images.githubusercontent.com/10076088/52644212-b5400580-2ede-11e9-9e05-64baaee2ea56.png)

- the problem arises much earlier, and more than once

**Comment by SaraRegibo** [comment]
Global picture now (flux for the individual pixels with transmission efficiency of 0.01 at EOL):

![image](https://user-images.githubusercontent.com/10076088/52645544-44e6b380-2ee1-11e9-8bb1-78a16de21998.png)


* the problem arises much earlier, and more than once
* some pixels that didn't show the problem before, now do show it

**Comment by SaraRegibo** [comment]
Two additional tests:

1. In case the transmission efficiency is kept constant over the mission, the fluxes in all pixels are constant throughout the simulation.
2. In case the ADU values are not floored, you see a linear decrease in flux for all pixels.

**Comment by SaraRegibo** [comment]
Hi Réza,
as you can read in the comments above, I have performed a couple of tests that all point to the same cause.  As the transmission efficiency decreases linearly with time, you also expect to see such a trend for the flux of the pixels (given a constant background and/or source, as is the case here).  As long as you don't round down the fluxes, this is exactly what you get.
However, the outcome of the simulations is a bunch of images for which the fluxes are expressed in ADU.  As you cannot chop up ADUs into pieces, you have to round down the fluxes.  This turns the linear trend into a step pattern.  Depending on the exact (float) value and how fast the transmission efficiency decreases, such jumps occur sooner/later in time and more/less often.
I agree that these jumps look a bit strange in your time series, but it's normal you get these (always of 1ADU at a time).  I hope this explanation resolves the issue.

**Comment by drsamadi** [comment]
Hi Sara,
I just had a look to your investigations. Your explanation is convincing  indeed. 
This is then something one can except and there is nothing we can do against. We just have to be aware about it. 
Thanks for your help!

Réza
