### ISSUE TITLE
Conserving disc space by writing the images as int matrices into the .hdf5 files

### ISSUE THREAD

**Issue by BertoltLang** [IvS-KULeuven/PlatoSim3#348]
At the moment we are conducting many long simulations with larger subfield sizes. The size of the simulations on our hard drives has become an issue even after I delete everything from the .hdf5 output files what is not needed. 
To counter that, I check whether the created pixelMap only consists of values, which could be displayed by uint16_t (which is sufficient for our simulations) and than write it as an UINT16 array within the .hdf5 output file. Doing so, I could cut the disc space requirement in half.
Maybe this could help others as well.

**Comment by JorisDeRidder** [comment]
Seems like a good idea to conserve disk space. We'll discuss it here, to check whether this could have any adverse affects on other users. Did you implement the changes in a separate git branch that we could check out?

**Comment by manugr788** [comment]
The true image coming from FEE will be in ADU over 16bits. Therefore, no any pixel value within images may exceed 2^16-1 (ADC digital saturation). For PIS, image datasets within hdf5 file are encoded using uint16.
PIS hdf5 file example :
In [9]: f["Images/image000000"]
Out[9]: <HDF5 dataset "image000000": shape (41, 10), type "<**u2**">
In [12]: f["Images/image000000"][:,:]
Out[12]:
array([[1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000],
....
 [1020, 1020, 1020, 1020, 1020, 1020, 1020, 1020, 1020, 1020]], **dtype=uint16**)

**Comment by BertoltLang** [comment]
I'm currently traveling and will share my proposal as soon as I come back on wednesday.

**Comment by BertoltLang** [comment]
I uploaded my suggestion, which is very similar to yours, Joris. The main difference is, that I used the NATIVE_UINT16 data type from the HDF5 C++ library. NATIVE_UINT still uses 32 bit, which defeats the purpose of saving space.

**Comment by SaraRegibo** [comment]
I have written a version that makes use of templates.  I will incorporate the suggestion to use `NATIVE_UINT16` and test it before pushing it to GitHub.

**Comment by SaraRegibo** [comment]
Implemented (using templates) in Pull Request #352 

* quantisation switched on => pixel, bias register, and smearing map stored as `float`
* quantisation switched off => pixel, bias register, and smearing map stored as `uint16_t`
* for maps stored as `uint16_t` added safety check to see whether the values are in the correct range, i.e. [0, 2^16 -1] (if not, an exception is thrown)

Jenkins build (for `develop`) back to normal (for both Mac and Linux).

**Comment by SaraRegibo** [comment]
Assigning to @BertoltLang for checking and closure.

**Comment by BertoltLang** [comment]
@SaraRegibo that's an elegant solution, but shouldn't it be saved as an int16 array if quantisation is activated, since the applyQuantisation() function rounds down the array values?
At the moment it is the other way around, if I read the code correctly.

**Comment by JorisDeRidder** [comment]
Indeed, that was a bug. Fixed, committed, and pushed.
If you're happy with the result, you can close the issue.

**Comment by BertoltLang** [comment]
It seems to work as intended - thank you for looking into this!
