### ISSUE TITLE
Edge effects introduced by convolution with non-analytic PSF

### ISSUE THREAD

**Issue by SaraRegibo** [IvS-KULeuven/PlatoSim3#357]
As discussed in #325 the convolution of an image with a non-analytic PSF introduces edge effects: the first and last row and column in the sub-field have a value that is lower than expected.

* For all other pixels, the contribution of the sky background is as expected → it's really an EDGE effect
* Increasing the size of the sub-field (to at least 8 x 8 pixels) does not resolve the problem
* The problem does not occur when convolving with an analytic PSF

**Comment by SaraRegibo** [comment]
In order to (or at least in an attempt to) properly treat the edges of the image upon convolution, we zero-pad the image. My guess would be that too few zeroes have been added in the padding process...

**Comment by s-geiser** [comment]
The effect could originate from the constant background position in the code:

The background is added as constant value to every pixel in the image. The convolution with the PSF is then applied afterwards (to every single pixel).
This leads to every 'background pixel' giving part of its flux to the neighboring ones. As the pixels at the edge of the image have less neighbors/zeroPadded (i.e. zero flux neighbors), they receive less flux and therefore have a smaller count. (the range of the effect seems to match the PSF range)

A solution would be to separate the background from the 'exposeDetector' function into a separate one, to be applied after the convolution.

I tested this and do no longer observe any edge effect, all pixels having the same constant background value observed in the central pixels beforehand.

**Comment by SaraRegibo** [comment]
Solved in the develop branch in #468.
