### ISSUE TITLE
Input file of the photometry tutorial needs to be updated

### ISSUE THREAD

**Issue by astrobatty** [IvS-KULeuven/PlatoSim3#368]
This is not a major bug, but if somebody tries to use PlatoSim3 for the first time it will be a little bit annoying.

It seems that the input file located in the /docs/tutorials/Photometry directory is out of date. The related notebook, called PhotometryExample.ipynb, cannot be executed properly, because several error messages appear that say configuration parameters are missing in the configuration file.

**Comment by JorisDeRidder** [comment]
Hi Attila, thanks for reporting this. We'll update the notebook as soon as possible.

**Comment by SaraRegibo** [comment]
Sorry about that!  I will re-run all tutorials in the `develop` and `master` branch and update where needed.

**Comment by SaraRegibo** [comment]
Just re-ran the photometry notebook and I don't have issues with missing configuration parameters...  @astrobatty Could you check that you have the latest version of the software installed, please?

Nevertheless, there is a problem in the notebook, but that is related to the fact that we store the values in the different maps as integers when quantisation is switched on.  Solving that now...

**Comment by astrobatty** [comment]
I created a new conda environment and installed the latest PlatoSim. Now, everything works. However, I only installed the previous version ~2 weeks ago the same way as I did now. So, I cannot figure out the source of the problem...

Anyway, thanks for your help!

**Comment by SaraRegibo** [comment]
Glas it works now!  Closing the issue...
