### ISSUE TITLE
Dynamic frame transfer times

### ISSUE THREAD

**Issue by denisGrBach** [IvS-KULeuven/PlatoSim3#369]
Currently there is the parameter 'ExposureTime' which is fixed, e.g. 2.3 seconds for the FastCams. Together with the calculated (dynamic) frame transfer time, the cycle time of the camera also is dynamic, 'CycleTime=ExposureTime+FrameTransfer'.
This is bad because in reality, there is a fixed hardware sync signal which triggers the frame transfer and defines the cycle time, e.g. 2.5 seconds for the FastCams. Therefore, it should be 'ExposureTime=CycleTime-FrameTransfer', with a fixed CycleTime to be set in the yaml-File.

**Comment by SaraRegibo** [comment]
@denisGrBach 
- For the fast cameras, the image cycle time = exposure time + time to transfer the charges from the upper CCD to the lower CCD half, right?
- Does this work the same for the partial-readout mode?

**Comment by denisGrBach** [comment]
@SaraRegibo 

Right, but the important thing is that the cycle time is fixed (by a hardware trigger). Therefore it should be 'exposure time = cylce time - frame transfer'. This is true for all possible modes.

**Comment by SaraRegibo** [comment]
- [x] remove `ExposureTime` from all input files and use `CycleTime` instead
- [x] check test harnesses
- [x] re-run tutorials
- [x] in `Simulation` no longer  use `ExposureTime` but use `CycleTime` instead
- [x] update TN6
- [x] update documentation

**Comment by SaraRegibo** [comment]
This has been solved in the `develop` branch by Pull Request #390.  Assigning to @denisGrBach for closure.
