### ISSUE TITLE
Update HDF5 dependency to 1.10.5

### ISSUE THREAD

**Issue by JorisDeRidder** [IvS-KULeuven/PlatoSim3#375]
From Hugh's comment in issue #332:

The hdf5-1.10.2 doesn't install with gcc-8.1 ("H5detect.c:1363:1" throws an error due to, I think, a single line which is no longer compatible, see https://forum.hdfgroup.org/t/1-10-2-h5detect-compile-error-gcc-8-1-0-on-centos-7-2-solved/4441). I spent ages figuring this out. Installing hdf5-1.10.5 and replacing all lines with 1.10.2 to 1.10.5 fixed the problem.

**Comment by JorisDeRidder** [comment]
Need to check if hdf5-1.10.5 also installs with the current prerequisites of PlatoSim3 (gcc 5.1 or clang 3.3).

**Comment by SaraRegibo** [comment]
To do:
- [ ] Replace downloaded package `/dependencies/Downloads/hdf5-1.10.2.tar.gz` by most recent version (1.10.5)
- [ ] Update installation script `/dependencies/installscripts/install_hdf5.py`
- [ ] Update `CMakeLists.txt` (two occurrences of the version number of the HDF5 dependency)
- [ ] Check whether this still works with the current pre-requisites for PlatoSim (gcc 5.1 or clang 3.3) -> if not, assess whether it is feasible to update the pre-requisites (in that case, the [PlatoSim documentation pages](http://ivs-kuleuven.github.io/PlatoSim3/ReqsInstallUpdate.html) need to be updated)
- [ ] Update the[ PlatoSim build scripts ](https://github.com/IvS-KULeuven/PlatoSimBuildScripts)for the automatic builds with Jenkins

**Comment by JorisDeRidder** [comment]
Fixed in issue #565.
