### ISSUE TITLE
Input parameter update

### ISSUE THREAD

**Issue by BertoltLang** [IvS-KULeuven/PlatoSim3#377]
Hello,
we suspect that some of the input parameters in the input.yaml files are outdated by now. This seems to be especially true for the inputfgs.yaml file. Is it planned to update the files according to the newest version (1.7) of the "System parameter table" by Anko Boerner?
Greetings,
Bert

**Comment by SaraRegibo** [comment]
I was not aware of an update of the parameter tables.  Thanks for bringing this to our attention.  I'll have a look!

**Comment by SaraRegibo** [comment]
Action items (for me):
- [x] find updated version of the parameter tables (v1.7) -> stored under on Nextcloud under `Platoman/Documents/performanceParameters/issue_1.7`
- [x] re-calculate everything in the `Parameter Review` notebook (under `/docs/tutorials`)
- [x] update values in all configuration files for PlatoSim
- [x] re-run tests
- [x] re-run tutorials
- [x] update PLATO-KUL-PL-TN-0006 (Configuration Parameters for PlatoSim)
- [x] properly write down in the change log (and here) which parameter values have changed

**Comment by SaraRegibo** [comment]
Changes:
- wavelength range
- irradiance over the PLATO wavelength range (PIS only; nothing changes for PlatoSim)
- added: orientation angle of the solar panels
- transmission efficiency
- throughput bandwidth
- FEE readout noise
- gain + stability of the CCD gain
- QE
- digital saturation for fast cameras (this is now the same as for the normal cameras)

**Comment by SaraRegibo** [comment]
Updated version of TN0006 (Configuration Parameters for PlatoSim): draft rev. 3.

[PLATO-KUL-PL-TN006.pdf](https://github.com/IvS-KULeuven/PlatoSim3/files/3540608/PLATO-KUL-PL-TN006.pdf)

**Comment by SaraRegibo** [comment]
See Pull Request #378

**Comment by SaraRegibo** [comment]
Assigning to @BertoltLang for closure.

**Comment by BertoltLang** [comment]
Thank you, Sara!
