### ISSUE TITLE
Dump Analytical PSF within hdf5 output file

### ISSUE THREAD

**Issue by manugr788** [IvS-KULeuven/PlatoSim3#379]
Would it be possible to dump the PSF used for the simulation within the hdf5 output file when using AnalyticGaussian or AnalyticNonGaussian PSF ? Is there any technical difficulties which make it difficult to implement ?
Actually, when using PLATOSim whithout Platophot but our process "lightcurve" PSF are needed to derive the photometry mask.
Regards,
Emmanuel

**Comment by JorisDeRidder** [comment]
Hi Emmanuel, 
Could you clarify what you mean by dumping  "the"  PSF? The PSF is position dependent and thus differs from position to position in the subimage.

**Comment by JorisDeRidder** [comment]
From a private email by Réza, I understood that you would need only 1 PSF, namely the one corresponding to the center of subimage, with size 8x8 pixels, and resolution 1/128 of a pixel. Am I correct?

**Comment by manugr788** [comment]
Yes, It’s exactly what we need. 

Platosim computes the analytical PSF for each exposure, therefore the PSF may vary from one exposure to another regarding the displacement of the star, that’s why we need the PSF at the center of the subimage  which anyway should not be very different from the real PSFs (I mean the precision should be enough to build an optimal binary mask or to compute the L1/L2 norms of the PSF inversion).

 

 

De : Joris De Ridder [mailto:notifications@github.com] 
Envoyé : lundi 9 septembre 2019 17:52
À : IvS-KULeuven/PlatoSim3 <PlatoSim3@noreply.github.com>
Cc : manugr788 <emmanuel.grolleau@obspm.fr>; Author <author@noreply.github.com>
Objet : Re: [IvS-KULeuven/PlatoSim3] Dump Analytical PSF within hdf5 output file (#379)

 

From a private email by Réza, I understood that you would need only 1 PSF, namely the one corresponding to the center of subimage, with size 8x8 pixels, and resolution 1/128 of a pixel. Am I correct?

**Comment by JorisDeRidder** [comment]
In the current develop branch, in case of the analytic non-gaussian PSF, a high-resolution PSF (size = 8 * 128 square subpixels) corresponding to the center of the subfield, is now saved to the HDF5 file in the folder "/SubPixelImages/HighResPSFmapCenterSubfield".

Note that the appearance of this PSF depends on the charge diffusion, which you can switch on/off or configure in the input yaml file in the section   PSF : AnalyticNonGaussian.

Could you test whether this high-resolution PSF is what you expected?

**Comment by manugr788** [comment]
I got a strange error when compiling platosim for both develop and master branch. 
```
git checkout master
./install.sh
...
Install the project...
-- Install configuration: ""
-- Installing: /home/grolleau/git/PlatoSim3/dependencies/Downloads/Faddeeva/../../Installs/Faddeeva/lib/libFaddeeva.so
-- Installing: /home/grolleau/git/PlatoSim3/dependencies/Downloads/Faddeeva/../../Installs/Faddeeva/include/Faddeeva.hh
-- Git current branch: master
-- Git describe: 3.3.6-2-gb084a69
-- CMake source dir: /home/grolleau/git/PlatoSim3
-- CMake current source dir: /home/grolleau/git/PlatoSim3
-- CMake binary dir: /home/grolleau/git/PlatoSim3/build
-- Generating version.h
-- Configuring done
-- Generating done
-- Build files have been written to: /home/grolleau/git/PlatoSim3/build
Scanning dependencies of target platosimLibrary

Scanning dependencies of target platosimLibrary
[  2%] Building CXX object CMakeFiles/platosimLibrary.dir/source/ArrayOperations.cpp.o
[  4%] Building CXX object CMakeFiles/platosimLibrary.dir/source/Camera.cpp.o
[  6%] Building CXX object CMakeFiles/platosimLibrary.dir/source/ConfigurationParameters.cpp.o
[  9%] Building CXX object CMakeFiles/platosimLibrary.dir/source/Convolver.cpp.o
In file included from /home/grolleau/git/PlatoSim3/include/HDF5Writer.h:8,
                 from /home/grolleau/git/PlatoSim3/include/TemperatureGenerator.h:9,
                 from /home/grolleau/git/PlatoSim3/include/FrontEndElectronics.h:13,
                 from /home/grolleau/git/PlatoSim3/include/Detector.h:18,
                 from /home/grolleau/git/PlatoSim3/include/Camera.h:16,
                 from /home/grolleau/git/PlatoSim3/source/Camera.cpp:2:
/home/grolleau/git/PlatoSim3/include/HDF5File.h:10:10: fatal error: H5Cpp.h: Aucun fichier ou dossier de ce type
 #include "H5Cpp.h"
...
make[1]: *** [CMakeFiles/Makefile2:110: CMakeFiles/platosimLibrary.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```
However this file exists:
```
locate H5Cpp.h
/home/grolleau/git/PlatoSim3/dependencies/Installs/hdf5-1.8.16/include/H5Cpp.h
/usr/include/hdf5/serial/H5Cpp.h
```

Then I try with:
```
export CPATH=/home/grolleau/git/PlatoSim3/dependencies/Installs/hdf5-1.8.16/include/
export LD_LIBRARY_PATH=/home/grolleau/git/PlatoSim3/dependencies/Installs/hdf5-1.8.16/lib/
./install.sh
...

but I got an error:
`ld: unable to link -lhdf5`

Do you ahave any idea ?
PS: I don't use conda, I only compile the last github sources with ./install.sh

**Comment by manugr788** [comment]
I have succeeded to compile/run Platosim "develop" branch with conda install procedure. I guess conda install procedure is now the best way to compile/run platosim. I will only use github procedure to look on the code from now on. The dependency to hdf5 1.10.2 library is not easy to meet outside a conda environment.

Moreover, I confirm that the AnalyticNonGaussian PSFs are now dumped into the HDF5 file (/SubPixelImages/HighResPSFmapCenterSubfield). The resolution and position are exactly what we were expecting. 
Just one point, why this PSF is not dumped within /PSF/HighResPSFmapCenterSubfield like for MappedFromFile rotated PSF ?

**Comment by JorisDeRidder** [comment]
Good suggestion about saving the high-resolution image in PSF/ rather than in SubPixelImages/. I changed this in the latest version of the develop branch. So the image is now saved in PSF/ as for the MappedFromFile case.
