### ISSUE TITLE
Update YAML loader to new version of yaml library

### ISSUE THREAD

**Issue by JorisDeRidder** [IvS-KULeuven/PlatoSim3#381]
With the latest version of the python yaml library, line 209 of simulation.py leads to the following deprecation warning:

`
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
`

Our Python code therefore needs to be adapted to this new version.

**Comment by SaraRegibo** [comment]
@JorisDeRidder This line has been replaced by:

```
self.yamlDocument = yaml.safe_load(stream)
```

Could you verify whether this is sufficient, and then either close this issue or comment on this, please?
