### ISSUE TITLE
Update figure in tutorial "Structure of PlatoSim HDF5 output"

### ISSUE THREAD

**Issue by SaraRegibo** [IvS-KULeuven/PlatoSim3#387]
The figure in the tutorial "Structure of PlatoSim HDF5 output" shows a group `BiasMaps`, but this should be replaced by two separate groups: `BiasMapsLeft` and `BiasMapsRight`.

**Comment by rhuygen** [comment]
![Structure of PlatoSim HDF5](https://user-images.githubusercontent.com/6662864/65154995-c03ab580-da2c-11e9-9bea-60b0b7bbf058.png)

**Comment by SaraRegibo** [comment]
Thanks, Rik!  Incorporated the update figure in the tutorial and closing the issue.
