### ISSUE TITLE
BFE seems to increase total flux

### ISSUE THREAD

**Issue by s-geiser** [IvS-KULeuven/PlatoSim3#399]
When I try to use the Brighter-Fatter-Effect, it seems to increase the total amount of flux instead of redistributing it.

Both with and without convolution with a PSF, I find all pixel counts to be increased within a 3x3 mask around a singular star (including the central one), the sum by over 2% (nearly 3% when not using the PSF).

I obtained this while turning off all other effects (so only PSF and BFE used).

I am using the develop version in the state of the 04.10.2019.

**Comment by SaraRegibo** [comment]
My first idea is that it may be just a normalisation issue, but I need to look at it in more detail.  That will probably be for after the PW.

**Comment by JorisDeRidder** [comment]
@SaraRegibo Please check if the problem can indeed be quickly solved by a proper normalization. If not, we may need a more extensive re-implementation.

**Comment by SaraRegibo** [comment]
I see now that we calculate something (of which we thought it was the BFE itself) and **add** that to the pixel map, thus increasing the total flux (rather than re-distributing it over neighbouring pixels).  Under investigation...

**Comment by SaraRegibo** [comment]
@s-geiser I just pushed changes to https://github.com/SaraRegibo/PlatoSim3/tree/feature/feature-399-BFE.  Could you have a look and re-run your test on that branch, please?

Things to keep in mind:
* I have also incorporated the changes to the BFE algorithm, needed for issue #434 (the coefficients are now read from a file instead of being calculated by PlatoSim)
* I have only changed `inputfiles/inputfile.yaml` (not the other yaml files) and I have not re-run the tutorials yet (I will do that after you confirm that your tests now run successfully)

**Comment by SaraRegibo** [comment]
It occurred to me that I made a mistake in my previous commit.  Just pushed a new version, in the same branch as before.

**Comment by s-geiser** [comment]
Okay, I try to have a look as soon as possible.

**Comment by s-geiser** [comment]
@SaraRegibo I don't seem to be able to access the page you linked (https://github.com/SaraRegibo/PlatoSim3/tree/feature/feature-399-BFE) - I get a 404 in browser and also no cloning from git is possible.

**Comment by SaraRegibo** [comment]
@s-geiser I have granted you access now (since it's a fork of a private repository, this is private, too).  You should be able to access it now (as soon as you accept the invitation GitHub should send you via email).

**Comment by s-geiser** [comment]
I ran a short test and observe a small increase in footprint accompanied by a decrease of total flux in the central region when adding the BFE, so exactly the expected behavior.

**Comment by SaraRegibo** [comment]
@s-geiser If you are happy with the result, please, close the issue.  Thanks!
