### ISSUE TITLE
6.25s time-shift between CCDs

### ISSUE THREAD

**Issue by drsamadi** [IvS-KULeuven/PlatoSim3#401]
Unless I'm wrong, PLATOSim does not include the time shift existing between  the readout of the CCDs. This time shift is 6.25s.  Here attached a figure extracted from the TRD (PLATO-DLR-PL-RS-001) and related to the 6.25s time shift  (PL-SYS-189). 

![Screenshot from 2019-10-03 18-46-14](https://user-images.githubusercontent.com/19569211/67854908-9daeb880-fb11-11e9-9900-e91260b508d8.png)

**Comment by JorisDeRidder** [comment]
Hi Réza, you're right. We'll implement this as soon as possible.

**Comment by SaraRegibo** [comment]
- [ ] Introduce new parameter holding the value of the time shift
- [ ] Start time of first exposure of given CCD: `sim["ObservingParameters/BeginExposureNr"]` * `sim["ObservingParameters/CycleTime"]` + `sim["CCD/Position"]` * `timeShift`
- [ ] What to do if `sim["CCD/Position"] == "Custom"`?
- [ ] We must advance the jitter and drift!

**Comment by JorisDeRidder** [comment]
About advancing the jitter and drift, AFAIU this is automatically done. E.g. `JitterFromRedNoise ::getNextYawPitchRoll(time) ` fast-forwards the jitter in small jitter steps until `time`. This implies that if different simulations start with the same random seeds, the jitter experienced by a star on one CCD will be consistent with the jitter of a star on another CCD.

**Comment by JorisDeRidder** [comment]
Same feature requested by exoplanet community.  Looking into it.

**Comment by JorisDeRidder** [comment]
Implemented and pushed into the develop branch. Commit eb32006.
