### ISSUE TITLE
Default width of the AnalyticNonGaussian PSF

### ISSUE THREAD

**Issue by drsamadi** [IvS-KULeuven/PlatoSim3#408]
I compared a AnalyticNonGaussian PSF obtained when sigma=1 with the case when sigma=0.5 (default value).
Here attached two figures:
* first figure -> sigma =0.5
* second figure -> sigma = 1.0 

My star is at the upper right corner edge of the FoV, in CCD2 (upper right, but note that the name of the CCD have recently been changed),  at approximatively 18 deg from the camera center. Charge diffusion was not included here.  
The PSFs are here plotted in a window of 2x2 pixels (CCD pixels). The resolution is 1/128 pix.

Compared to the PSF plotted by Carsten in figure 2.1 in  PLATO-DLR-PL-RP-004 (Simulations and Performance Estimations, issue 1.0 , 18/02/2016 ; here attached a snapshot of this figure),
the PSF with sigma = 0.5 looks too compact. 
The one with sigma = 1.0 looks more similar than the PSF you can see around 18deg. 

For this reason I wonder if  sigma = 0.5 is a good choice. 
Since people in general use the default values, it is very important to be sure that the parameter controlling the PSF size is relevant.

Réza
ps: PlatoSim 3.3.6-181-ga79d056

![Figure_7](https://user-images.githubusercontent.com/19569211/70629443-4b8da680-1c2a-11ea-9f26-a8756c8c404a.png)
![Figure_6](https://user-images.githubusercontent.com/19569211/70629455-4fb9c400-1c2a-11ea-9223-7605f6af8a33.png)
![Screenshot from 2019-12-11 15-16-47](https://user-images.githubusercontent.com/19569211/70629457-51838780-1c2a-11ea-917a-580ccabc884b.png)

**Comment by carstenpaproth** [comment]
The default value for sigma should be 0.5. The analytical model was derived with that value. For comparison, the white PSF that was used for the fitting at 18.081 deg is quite compact in 2x2 pixels as well, first figure. The corresponding analytical PSF is shown in the second figure.

![plato_baseline_psf_6000-18081](https://user-images.githubusercontent.com/26323228/70703337-2eabae80-1cd0-11ea-9648-7d7a7fba4576.png)

![plato_baseline_apsf_6000-18081](https://user-images.githubusercontent.com/26323228/70703752-ff497180-1cd0-11ea-835b-4e534568062b.png)

**Comment by drsamadi** [comment]
Hi Casten,

the PSF returned by PLATOSim in the field 'PSF/HighResPSFmapCenterSubfield'  looks more compacted that in your plot. 
I have generated a microscanning simulation and applied Daniel's inversion technique. I get this inverted PSF:
![Figure_inverted_NODIFF](https://user-images.githubusercontent.com/19569211/71546261-6f284f00-2995-11ea-8939-69d1f73cba6f.png)

The second figure is the PSF returned in 'PSF/HighResPSFmapCenterSubfield'. The PSF looks similar but  it is wider.

![Figure_HighResPSFmapCenterSubfield_NODIFF](https://user-images.githubusercontent.com/19569211/71546263-72bbd600-2995-11ea-8ef6-e3691e60d580.png)

The simulation does not include diffusion.

Clearly it looks to me that the PSF returned in the output file does not reflect the actual shape of the PSF used by PLATOSim.

Réza

**Comment by carstenpaproth** [comment]
Hi Réza,

Indeed that looks weird.
Do both figure use the same number of subpixels per pixel?
I looked at the PLATOSim code that generates the highres analytic PSF (DetectorWithAnalyticNonGaussianPSF::makeHighResolutionPSF), and it looks good to me, but it seems to use always 128 subpixels per pixel.

Carsten

**Comment by JorisDeRidder** [comment]
@carstenpaproth PlatoSim is currently using the values that you recommended. Can you please verify if these are still adequate given the report by Réza above?

**Comment by carstenpaproth** [comment]
@JorisDeRidder 
I cannot reproduce the discrepancy reported by Réza. The default value for sigma is 0.5 which produces the best fit to the nominal white PSF. A larger sigma value increases the PSF size proportionally.

**Comment by drsamadi** [comment]
The inverted PSF is plotted with a resolution of 1/128 pixel. I assume that the PSF stored in 'PSF/HighResPSFmapCenterSubfield' has also a resolution off 1/128 pixel

**Comment by drsamadi** [comment]
Carsten, can you generate a plot showing the same PSF (at 18deg, sigma=0.5) with a resolution of 1/128 within a window of 6x6 pixels, i.e. exactly as I did above with the inverted PSF and the PSF returned in  'PSF/HighResPSFmapCenterSubfield' 
Thanks
Réza

**Comment by carstenpaproth** [comment]
@drsamadi 

Here you are, PSF with sigma=0.5 at 18° in 6x6 pixels with 128 subpixels per pixel:

![plato_apsf_18deg_6x6_128subpix](https://user-images.githubusercontent.com/26323228/75056849-18904a80-54d8-11ea-91cb-e92e97ac187a.png)

Can you provide the pointing time series you used for the microscanning?

**Comment by drsamadi** [comment]
Hi Carsten
thanks. Here is the requested file: https://upload.obspm.fr/get?k=oAxB494jHlf5Snxvzb6

The PSF shown in your figure has indeed the same size and shape than the one stored in 'PSF/HighResPSFmapCenterSubfield' 

My inverted PSF is clearly wider, this could be due to the jitter noise existing at  cadence lower than 2.5s (the inversion is made on the basis of  star positions averaged over 2.5s).

**Comment by drsamadi** [comment]
To check this I will perform a microscanning without the presence of jitter noise.

**Comment by carstenpaproth** [comment]
Hi Réza,

Thanks, I used your spiral with PLATOSim to make a microscanning simulation of a star at 18° with the analytical non-Gaussian PSF with sigma=0.5 and without any other noises. First, the spiral samples the pixel corners less well than other parts of the pixel:

![image](https://user-images.githubusercontent.com/26323228/76077605-504fc580-5fa1-11ea-9da6-bd0bd4d8c381.png)

Then I made a Delaunay triangulation for these subpixel positions which were combined with the corresponding imagette values. The resulting triangle mesh was resampled with 1/128 pixel resolution to get a subpixel PSF:

![plato_micropsf_18deg_6x6_128subpix](https://user-images.githubusercontent.com/26323228/76090890-bac22f00-5fbc-11ea-8613-94d210830fc9.png)

Finally, I used a maximum entropy deconvolution with 6000 iterations to deconvolve the optical PSF and the pixel PSF, so I got an inverted PSF, 6x6 pixels with 128x128 subpixels per pixel:

![plato_invertedpsf_18deg_6x6_128subpix](https://user-images.githubusercontent.com/26323228/76090919-cc0b3b80-5fbc-11ea-94c3-e9973ccec13b.png)

The inverted PSF looks quite similar to the used input PSF, so the jitter noise in the microscanning spiral didn't disturb my result that much.

**Comment by drsamadi** [comment]
Hi Carsten,
thanks for your investigation!
I finally found my error, a stupid one: I was always working with the simulation generated assuming  sigma=1 (and not 0.5....) . Now when I apply the  inversion on the right simulation data set,  I get an inverted PSF very similar to the one  stored in 'PSF/HighResPSFmapCenterSubfield'.
Sorry for this mistake and the time you waste. 
 I will close the issue.
Cheers,
Réza
