### ISSUE TITLE
Validation of differential stellar aberration

### ISSUE THREAD

**Issue by SaraRegibo** [IvS-KULeuven/PlatoSim3#411]
In my own repository, in the branch `validation-verification`, there are two Jupyter notebooks for the validation of the absolute and differential aberration.  The corresponding test cases are described in PLATO-KUL-PL-PLN-0002 (PlatoSim Verification & Validation Plan; see NextCloud).  The validation of the absolute aberration works fine and is described in PLATO-KUL-PL-RP-0004 (PlatoSim Verification & Validation Report; see NextCloud), but I don't manage to produce meaningful/correct plots for the differential aberration.  I could use some help here!

**Comment by SaraRegibo** [comment]
Goal date to finish up the first version of the report: end of January.

**Comment by denisGrBach** [comment]
Could you make the notebooks available for us? We already checked it on our side and it looked alright.

**Comment by SaraRegibo** [comment]
Just pushed the branch to `upstream`, so you should be able to see it now.  My goal is to produce a similar plot to this one for absolute stellar aberration:

![image](https://user-images.githubusercontent.com/10076088/71251331-5a5b1400-2322-11ea-83e4-bf3782a16f1f.png)

**Comment by nicholasjannsen** [comment]
@Dries-Seynaeve and @JorisDeRidder, do we have a validation test for this now? Can see we have one for the *absolute* aberration in `docs/validation/StellarAberration`.

One validation test that I think of, before closing this issue, is to simulate the amplitude of the KDA across the FPA for a few time instances of the orbit file. In that way we can confirm that the amplitudes agrees with our expectations. However, it is not super clear where to dig out the information about the KDA amplitude in the C++ code (would be great to have a Python function that could calculate it directly given the time, platform pointing, and focal plane coordinate of star).
