### ISSUE TITLE
Transmission variation as a function of FOV

### ISSUE THREAD

**Issue by s-geiser** [IvS-KULeuven/PlatoSim3#415]
The transmission efficiency is currently given as one value for the full FOV and then reduced radially by natural vignetting.

The transmission is additionally affected by other effects like edge impact from mechanical vignetting, shape of the lenses, coatings etc... This leads to the final transmission loss being higher than cos^2(r) as shown in fig 4-9 of the TOU Optical Performance Analysis Report (PLATO-LDO-PL-RP-0002).

So PlatoSim currently overestimates transmission towards increasing FOV radius.

**Comment by JorisDeRidder** [comment]
Update: request sent to author of the report to obtain the vignetting values as a function of radial distance.

**Comment by JorisDeRidder** [comment]
Update: data received from author, attached to this comment.
It concerns the vignetting (in %) as a function of the radial distance (degrees). The data of Fig 8 concerns the individual effects:
<img width="421" alt="PastedGraphic-1" src="https://user-images.githubusercontent.com/5747893/74029866-f661dd00-49ad-11ea-9edb-44cb5e32fae2.png">

The data for fig 9 concerns the combined effect:
<img width="445" alt="PastedGraphic-2" src="https://user-images.githubusercontent.com/5747893/74030030-5193cf80-49ae-11ea-9cec-808a03c6d261.png">

[Data Fig8.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/4170751/Data.Fig8.txt)
[Data Fig9.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/4170752/Data.Fig9.txt)

**Comment by SaraRegibo** [comment]
For completeness, copying the information from #435:

This issue came up during the review of PLATO-KUL-PL-TN-007 (Signal & Noise Model for PlatoSim). Comment by Martin.

Currently, mechanical vignetting is implemented as a blockage of incoming flux beyond the edge of the FOV. However, at smaller distances from the OA, we already see a decline in efficiency due to the following effects (gathered under the name "mechanical vignetting"):

* mask (kicking in at ~14°)
* shape of the lenses (in particular L6)
* coating inefficiency
* ...

**Comment by SaraRegibo** [comment]
Using a linear fit through (16, 0) for the mechanical vignetting, as in the plot below (in green).

![image](https://user-images.githubusercontent.com/10076088/82896172-c71fad80-9f55-11ea-82bc-c82a77411fd5.png)

Model for the mechanical vignetting (loss in efficiency 1 - E):
- θ <= 16°: 1 - E = 0 (no mechanical vignetting);
- 16° <= θ < edge of FOV: 1 - E = (θ - 16°) * slope;
- θ >= edge of FOV: 1 - E = 0 (total blockage of incoming light);

with θ the distance from the optical axis (in degrees)

**Comment by SaraRegibo** [comment]
Implemented (as described above) in #470.

Documentation:
<img width="1228" alt="Screenshot 2020-05-26 at 14 42 59" src="https://user-images.githubusercontent.com/10076088/82902101-3e0d7400-9f5f-11ea-8875-31f7b8aa3c58.png">

**Comment by SaraRegibo** [comment]
@s-geiser, assigning this issue to you for validation and closure.  Please, check the code in Pull Request #470.  If everything works as desired, I will merge the Pull Request into the develop branch.

**Comment by s-geiser** [comment]
Codewise it looks fine to me but I have two questions:

1) If both mechanical and natural vignetting are being used, the present implementation would multiply the effects: 
        Etot = Emech*Enat
 As far as I recall, the green curve (mechanical) has been obtained by 'differentiation' of the efficiency with and without (i.e. natural) vignetting mask, leading to the possibility of: 
        Etot = 1 - ((1-Emech) + (1-Enat)) = Emech + Enat - 1
This would maybe needed to be checked based on the numbers in the plot / with the authors from the TOU/CAM team.

2) This implementation takes care of the mechanical vignetting, but not the additional variation due to e.g. coating and lens thickness, as given e.g. in the following plot (right side):

![Capture2](https://user-images.githubusercontent.com/53929755/82912844-d579c380-9f6d-11ea-92a6-fed3aa8d0d04.PNG)

These effects make up the difference between the total in Fig8 (just vignetting) and Fig9 (all effects combined) of Joris' comment from the 07.02
I again do not have exact numbers for this, so they would need to be confirmed with the system performance/camera teams.

**Comment by SaraRegibo** [comment]
Hi @s-geiser, you are totally right about the combined effect, of course, I will update it in the code and then merge it into the develop branch.

Regarding your 2nd point: Who can we ask for the necessary numbers? Can we close this issue?

**Comment by SaraRegibo** [comment]
Just updated the code in Pull Request #470.
