### ISSUE TITLE
CCD Id new standard

### ISSUE THREAD

**Issue by manugr788** [IvS-KULeuven/PlatoSim3#416]
[PLATO-OHB-PL-LI-0009_04_Instrument_Coordinate_Systems.pdf](https://github.com/IvS-KULeuven/PlatoSim3/files/4180959/PLATO-OHB-PL-LI-0009_04_Instrument_Coordinate_Systems.pdf)
May you check that CCD Ids in Platosim match the latest standard for CCD Id defined in PLATO-OHB-PL-11-0009 i4.0, i.e. w.r.t. FP: 
- CCD Id 1 is top left
- CCD Id 2 is bottom left    
- CCD Id 3 is bottom right,
- CCD Id 4 is top right
It seems to me, but I may misunderstand something, that develop branch version of python/referenceFrames.py and inputfiles/inputfile.yaml used the previous CCD id standard.
It is very important that Platosim uses the new standard definition since all the on-board algorithms use this new definition and platosim simulations used to validate the on-board software use this definition too.
This is the critical line :
Orientation:         [0, 90, 180, 270]      # Orientation of CCD w.r.t. focal plane orientation, counter-clockwise [deg]

--  Current conversion in LESIA code
    if( starFPXmm_distor > 0 and starFPYmm_distor < 0 ):
        CCDID_old = 1  
        CCDID_new = 3
    elif( starFPXmm_distor > 0 and starFPYmm_distor > 0 ):
        CCDID_old = 2 
        CCDID_new = 4 
    elif( starFPXmm_distor < 0 and starFPYmm_distor > 0 ):
        CCDID_old = 3  
        CCDID_new = 1
    elif( starFPXmm_distor < 0 and starFPYmm_distor < 0):
        CCDID_old = 4 
        CCDID_new = 2

**Comment by JorisDeRidder** [comment]
This will require verifications and changes in:

- inputfile.yaml
- inputfgs.yaml
- referenceFrames.py
- PlatoSim test code
- all Python notebooks
- all Python example scripts
- the python plotting module that plots the CCDs
- the online documentation
- the Plato reference frames technical note
- the Plato input file specification technical note
- input and python files used by PlatoSim users (e.g. the exoplanet simulations)

**Comment by SaraRegibo** [comment]
@rhuygen We should also propagate these changes to `plato-common-egse`!

**Comment by SaraRegibo** [comment]
* In the configuration files the order of the orientation angles of the pre-defined CCD positions (`CCDPositions/Orientation`) must be changed to `[180, 270, 0, 90]`.
     - [x] `testData/input_DetectorTest.yaml`
     - [x] `testData/input_starCatalogTest.yaml`
     - [x] `inputfiles/inputfgs.yaml`
     - [x] `inputfiles/inputfile.yaml`
     - [x] `python/Examples/closedLoopTest/offlineInput.yaml`
     - [x] `python/Examples/closedLoopTest/onlineInput.yaml`
     - [x] ~`docs/tutorials/FineGuidanceStars/inputfgs`~
     - [x] `docs/tutorials/Photometry/inputphot.yaml`
* The following changes are needed for the on-line documentation:
     - [x] `docs/source/ConfigurationFile.md`: update section `CCD Positions`
     - [x] `docs/source/images/CCD Array Configuration - Fast Camera.png`: change CCD labels
     - [x] `docs/source/images/CCD Array Configuration - Normal Camera.png`: change CCD labels
     - [x] `docs/source/images/FocalPlaneCoordinateSystem.png`: change CCD labels
     - [x] render html files (do not push to the `gh-pages` branch before the changes are pushed to the `master` branch)
* The following changes must be performed in the Python code:
     - [x] `python/Examples/demoVariableStars.py` (line 54): change CCD position from `1` to `3`
     - [x] `python/inputForComparisonWithPIS.py` (line 255): change CCD position from `2` to `4`
     - [x] `python/referenceFrames.py` (line 29): change orientation angles for the CCDs
* Better re-run all tutorials:
     - [x] `docs/tutorials/ConfigurationParameters`
     - [ ] `docs/tutorials/FineGuidanceStars`
     - [x] `docs/tutorials/FOV`
     - [ ] `docs/tutorials/InspectHDF5`
     - [x] `docs/tutorials/MultiTelescopeConfiguration`
     - [x] `docs/tutorials/ParameterReview`
     - [ ] `docs/tutorials/Photometry`
     - [x] `docs/tutorials/ScriptingPlatoSimWithPython`
     - [x] `docs/tutorials/SpecifyStarsInPixelCoordinates`

**Comment by denisGrBach** [comment]
In this context, I like to point out that the CCD orientation angle is used counterintuitive. It transforms from CCD-RF to FP-RF whereas the CCD offset transforms from FP-RF to CCD-RF. Maybe the current changes can be used to align both transformation by inverting the CCD orientation angle (gamma_CCD). This would make it more straightforward to give an easy transformation from the CCD-RF used in PlatoSim to the CCD-RF as given in PLATO-OHB-PL-11-0009.

**Comment by SaraRegibo** [comment]
I can relate to your request for consistency, but I wonder whether it is worth taking the risk of breaking stuff...

**Comment by denisGrBach** [comment]
Since the CCD numbering and therefore also the pre-defined angles change anyway, it might be a good moment to do so. The angle should only be used where you transform from FP to CCD and vice versa.

**Comment by SaraRegibo** [comment]
Action items:

* @JorisDeRidder:
     - update the TN on reference frames (and include it in the repository)
     - update the orientation angles in the configuration files
     - update the coordinate transformations in the code (both C++ and Python)
     - check whether tutorials still work
     - update description of the angles in the documentation (don't push to the on-line documentation pages)
* @SaraRegibo:
     - move to new CCD naming convention (see comments above)
     - #447

**Comment by SaraRegibo** [comment]
Closed by #459.

The remaining tutorials that still need to be fixed, are listed in #462.

**Comment by SaraRegibo** [comment]
Assigning to @manugr788 for closure.

This has been implemented in the develop branch.  The documentation (esp. the figures) has been updated locally but has not been pushed to the on-line documentation pages (as these correspond to the master branch).

Once this change has been pushed to the master branch, we will update the on-line documentation pages.

**Comment by SaraRegibo** [comment]
Closing this issue. @manugr788, if you do not agree with the implementation, please, re-open this issue.
