### ISSUE TITLE
Photon noise applied after CTI

### ISSUE THREAD

**Issue by s-geiser** [IvS-KULeuven/PlatoSim3#431]
The photon noise (poisson shot noise) is currently applied after the CTI.

As this is an effect that arises the instance the light hits the detector (during exposure), I think it should be calculated prior to the CTI. This could be done by simply swapping the position in the readout() routine in Detector.cpp

**Comment by SaraRegibo** [comment]
@carstenpaproth I seem to remember that we discussed the order of the effects at the last PLATO Week.  Could you comment on this, please?  Thanks!

**Comment by carstenpaproth** [comment]
From a philosophical view, in the world of quantum physics it is not that clear whether the number of electrons can be already known after the photons excite them or only after they were actually counted.

CTI after photon noise seems to be the logical sequence, nevertheless I don't think it makes a big difference in which order photon noise and CTI are applied. And as the CTI effect is a random process as well and the current implementation spreads electrons non-randomly (?), it seems to be OK to apply the CTI before applying the shot noise, to get some randomness in the CTI as well.

To exaggerate, the simulation would be more accurate by using random numbers of photons which randomly excite electrons, transfer these electrons pixelwise and randomly to the readout, and then convert them to voltages with random fluctuations and quantize that with some uncertainty. But I think it is sufficient to use a simpler simulation approach by just estimating the mean number of electrons and applying Poisson distributed noise and some readout noises which captures the main properties of the physical processes involved and is much faster to simulate.
