### ISSUE TITLE
Charge diffusion dependence on Photon Noise

### ISSUE THREAD

**Issue by s-geiser** [IvS-KULeuven/PlatoSim3#432]
The charge diffusion is an effect on e- level. It currently is calculated based on the nominal expected photon flux, with photon noise being applied much later.

But as charge diffusion is depending on the amplitude of the flux, and the photon noise physically applies on photon level so before CD, is there a significant impact of doing it in the current order?

**Comment by carstenpaproth** [comment]
The charge diffusion ist currently simulated by a simple convolution of the PSF with a Gaussian and no dependency on the amplitude of the flux is regarded. The dependency on the amplitude of the flux is part of the brighter fatter effect (BFE) which is simulated separately.

**Comment by SaraRegibo** [comment]
@s-geiser Assigning it back to you for closure, as this is a non-issue, since charge diffusion is just a broadening of the PSF that is not dependent on flux level (on contrast to the BFE).
