### ISSUE TITLE
Mechanical vignetting < edge of FOV

### ISSUE THREAD

**Issue by SaraRegibo** [IvS-KULeuven/PlatoSim3#435]
This issue came up during the review of PLATO-KUL-PL-TN-007 (Signal & Noise Model for PlatoSim).  Comment by Martin.

Currently, mechanical vignetting is implemented as a blockage of incoming flux beyond the edge of the FOV.  However, at smaller distances from the OA, we already see a decline in efficiency due to the following effects (gathered under the name "mechanical vignetting"):
- mask (kicking in at ~14°)
- shape of the lenses (in particular L6)
- coating inefficiency
- ...

This is visualised in the plot below:

![image001](https://user-images.githubusercontent.com/10076088/75984322-78c8b880-5eea-11ea-853b-5327108f49e8.jpg)

These effects should be accounted for.  Already asked for the number that are behind the plot.

**Comment by s-geiser** [comment]
I think this is the same issue as the transmission variation discussed in issue 415.

**Comment by SaraRegibo** [comment]
Yes, you are right, @s-geiser.  Sorry I overlooked that.  Copying information from this issue to #415, and closing this issue.
