### ISSUE TITLE
Access methods for datasets at top level in HDF5 file (HDF5File.cpp)

### ISSUE THREAD

**Issue by SaraRegibo** [IvS-KULeuven/PlatoSim3#437]
I have an HDF5 file with the datasets directly at the top level (so no group at the top level).  I.e. `h5ls` gives:
```
[D] /1
[D] /10
[D] /100
    ...
```
I would like to have methods to check whether these datasets exists (directly at the top level) and to extract attributes from these dataset.  So, in `HDF5File`:

- `hasDataset(string datasetName)`
- `readDoubleDatasetAttribute(string dataset)`

This blocks #407.

**Comment by JorisDeRidder** [comment]
I guess the existing `hasDataset(groupName, datasetName)` and `readDoubleDatasetAttribute(groupName, datasetName, attributeName)` don't work with `"/"` or `""` as group name? Can you make the HDF5 file available for me to test new methods?

**Comment by SaraRegibo** [comment]
I only tried with group name `""` so far, but `"/"` seems to do the trick!  Closing the issue.

**Comment by SaraRegibo** [comment]
I spoke too soon...  Using `"/"` does not produce any errors (in contrast to `""`), but the attributes I read with the `readDoubleDatasetAttribute` method are zero (when in reality, they're not)...  Could you have a look, please, @JorisDeRidder?

**Comment by SaraRegibo** [comment]
@JorisDeRidder I sent you the file via Belnet.  You should receive an email soon (still uploading...)!

**Comment by JorisDeRidder** [comment]
Using "/" as group name, "1" as dataset name, and "starPointing1" as attribute name, I don't experience any problems. Can you give an concrete example that fails?

**Comment by SaraRegibo** [comment]
In the `select()` method in the `AsymmetricalPointSpreadFunction` class, I try to read the `centerCoordinates1` and `centerCoordinates2` attributes and they are zero for all datasets.

**Comment by JorisDeRidder** [comment]
The problem is that some attributes (like centerCoordinates1) are not stored as a double attribute in the HDF5 file but as a string attribute. I.e. `"-5.01475488E+01"` rather than `-5.01475488E+01`. I can not think of any good reason to do so. I implemented a function `readStringDatasetAttribute(string groupName, string datasetName, string attributeName)` in HDF5File.cpp. I adapted `AsymmetricalPointSpreadFunction::select()` accordingly. Can you test it?

**Comment by SaraRegibo** [comment]
Thanks!  I've tested it and it works!  Closing this issue.
