### ISSUE TITLE
question: EOL versus BOL

### ISSUE THREAD

**Issue by drsamadi** [IvS-KULeuven/PlatoSim3#441]
Hi,
I have a simple question: how the choice between EOL and BOL parameters is made  in PLATOSim ?

thanks
Réza

**Comment by JorisDeRidder** [comment]
Hi Réza, 
Could you be more specific? Is your question how the BOL/EOL transmission efficiencies in the input yaml file were derived? Or how the interpolation between BOL and EOL is done?

**Comment by SaraRegibo** [comment]
Hi @drsamadi!  If you start with the 1st exposure with `sim["ObservingParameters/BeginExposureNr"] = 0`, you will be using the values at BOL.  From then onwards, you will see a linear degradation of the parameters.  After `sim[ObservingParameters/MissionDuration]` (6.5yrs) the EOL values will be reached.  For each exposure the values of the degrading parameters are re-calculated (using linear interpolation) and used for that particular exposure.

If you are interested in using the parameters of, say, 2yrs into the mission, you will have to set the  `sim["ObservingParameters/BeginExposureNr"]` to the appropriate value, taking into account the image cycle time (`sim["ObservingParameters/CycleTime"]`) of 25s.

We are aware that, for some of the degrading parameters, linear interpolation will be too crude of an estimation, but this can be improved in a later stage (if needed).

Hope this helps!  Take care!

**Comment by drsamadi** [comment]
Hi Sara,
thanks  ! this is perfectly clear.  
Réza
