### ISSUE TITLE
CTI Short2013 model has no effect

### ISSUE THREAD

**Issue by carstenpaproth** [IvS-KULeuven/PlatoSim3#446]
Activating the Short2013 CTI model has no influence on the output.

**Comment by SaraRegibo** [comment]
Potentially also the cause of #403...

**Comment by SaraRegibo** [comment]
Hi @carstenpaproth, you mentioned to Joris that this used to work in the past.  Can you tell me when it definitely worked?  I'm trying to find changes going over the GitHub history, but the only change over the last year was changing the order of some of the effects (as reported in #394)...

**Comment by carstenpaproth** [comment]
@SaraRegibo 

No, I cannot remember when it worked. I made a quick test in the past with a single star and activated CTI. Depending on the brightness of the star, the CTI trail changed. So I think it worked, maybe one or two years ago.

**Comment by drsamadi** [comment]
Hi,
some news about this bug ?
I have noticed the same problem with my version (development branch): PlatoSim 3.3.6-181-ga79d056

**Comment by SaraRegibo** [comment]
Looking into it, but have not found the cause of the problem yet...

**Comment by SaraRegibo** [comment]
Fixed in the develop branch.  Assigning to @carstenpaproth for closure.

**Comment by carstenpaproth** [comment]
Thanks for fixing this bug!
I made a quick test, and now the Short2013 CTI model produces the expected behavior, it has a relatively stronger impact on fainter stars.
