### ISSUE TITLE
CCD origin offset/orientation

### ISSUE THREAD

**Issue by denisGrBach** [IvS-KULeuven/PlatoSim3#447]
Unlike, e.g. 'FocalLength', CCDOriginOffsets/Orientation are constant without 'FromFile' option to include a time series. To evaluate CameraLoop calibration data we would need this feature to change the entire camera geometry, including CCD positions/orientations.

**Comment by drsamadi** [comment]
Hi Denis,
do we foresee time variations of those quantities (CCDOriginOffsets/Orientation) ?  Until now we have supposed that they will remain constant at least at the time scale of the 3-months observation sequences. These parameters can be re-calibrated every 3 months (if needed). Otherwise if they change during the  3-month observation sequences, this may have an impact on the photometry performance (if the variations turn out to be significant) . Do you have some estimate of the anticipated amplitude of the changes ?
Réza

**Comment by denisGrBach** [comment]
Hi Réza,

yes, the camera geometry, including CCD positions, will change due to TED caused by environmental changes. You can see an example from CamLoop2a in PLATO-DLR-PL-TN-0016, figure 20, The amplitudes seen here are achieved when applying the prime environmental requirements. They will be smaller in real life, see table 9 of the same document. The goal of the latest CameraLoop #2b is to see the explicit influence of different thermal loads (TOU radiation, Bipod I/F, FEE radiation) to FGS bias stability. The N-Cams will see both, their own TED and the bias stability of the FGS.

**Comment by SaraRegibo** [comment]
Hi @denisGrBach, could you provide us with an example input file, please?  I guess this would consist of the following four columns (separated by a space):

* time [s];
* x-offset of the CCD origin from the centre of the focal plane [s];
* y-offset of the CCD origin from the centre of the focal plane [mm];
* orientation of the CCD w.r.t. the focal-plane orientation [degrees].

Unless you would want to split this up over two or three different files, which seems unnatural to me (as I expect all these things to change together, at the same time)...

We still have to decide on an optimal structure for the configuration file to enable this request.  I'd be happy to hear suggestions!

**Comment by denisGrBach** [comment]
@SaraRegibo, this is right, those 3 values are given for each CCD. Hence, it will be a 13 column table (1+4x3). I calculate the geometric camera calibration according to the CCD reference frames as given in PLATO-OHB-PL-LI-0009, see also #416. PlatoSim uses a different convention, the calibration parameters therefore need to be transformed.  Do you plan to updated the CCD numbering (#416)?

The attached file has the following structure:  [time [s], CCD1, CCD2, CCD3, CCD4], where CCD consists of [x-offset [mm], y-offset [mm], gamma [deg]].
[cl2bCcds.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/4451997/cl2bCcds.txt)

**Comment by SaraRegibo** [comment]
Hi @denisGrBach, thanks for the clarification!  Still have to think further about the structure of the configuration file...

So far, we have been a bit reluctant to make the changes to the CCD naming in PlatoSim (as reported in #416), as it feels like dangerous set of changes to perform...  I'll try to be courageous this week and just do it! :)  Best to implement issue #416 before implementing this one!

**Comment by SaraRegibo** [comment]
Any conversion from and to pixel coordinates will be affected.  This means that:

* In `Detector::addFlux(xFP, yFP, flux)`: the flux will fall on slightly different (sub-)pixels.
* In principle, we should re-calculate the throughput map (as some of the effects depend on the angular distance from the OA), each time the CCD position changes, but that would put a (too heavy) burden on the code, for an effect that is probably negligible, no?  So I would simply use the throughput map from t=0.

**Comment by denisGrBach** [comment]
That's right, the pixel coordinates and therefore the flux on each pixel will change with time. 
Also the throughput map would change. How is it done with a change in focal length or distortion?  This should be similar.

**Comment by SaraRegibo** [comment]
All time-dependent parameters (focal length, FP angle, distortion coefficients, telescope orientation, magnitude for variable sources, and now also the CCD origin offset and orientation angle) are updated at the same moment in `Camera::exposeDetectorWithStars`, i.c. at every jitter step.  For every time step, we re-evaluate the position of the stars on the detector and add flux to the appropriate (sub-)pixels.

**Comment by SaraRegibo** [comment]
@denisGrBach, In the code Bertolt wrote (ClosedLoopDetectorClasses), there’s a method setNewWindowPosition, which not only updates the dimensions and zeropoint of the sub-field but also the orientation of the CCD.  Since the latter will/can be read from a file, I guess we can leave this out of the signature.  Are there any objections against this?

**Comment by SaraRegibo** [comment]
Upon convolution, we must rotate the PSF to match the orientation of the CCD.  This is done after having processed all jitter steps for the current exposure.  As a simplification, I would propose to use the pre-defined values (180°/ 270°/0°/90°) when we read the CCD position from a file (instead of using the orientation angle at the start/middle/end/... of the exposure).  Would that be good enough to do the simulations you have in mind, @denisGrBach?

**Comment by denisGrBach** [comment]
The setNewWindowPosition() method should not need the orientation. And, if I'm not mistaken, it is not using it, except for logging. I'm not sure why it is send din the first place.

**Comment by denisGrBach** [comment]
Maybe an error angle can be applied during the exposure and the nominal orientation is used as it is now. On the other hand the thermal changes, I want to model, are very slow. sS it might be sufficient to apply the average orientation during the exposure in the end.

**Comment by SaraRegibo** [comment]
Do you mean that we would use (for the origin offset and the orientation angle):

> current value = (default value, as we used before) + (error thereon, read from the file,  for the current time)

Could you update the file then, please, @denisGrBach?

**Comment by denisGrBach** [comment]
To be transparent it is probably better to keep the absolute values in the file, like for the other calibration parameters (distortion, focal length). It might be beneficial to calculate and use the error values internally.

**Comment by SaraRegibo** [comment]
From this issue:

- [x] issue #495 was raised (geometric distortion model);
- [x] issue #496 was raised (quantisation);
- [x] When using the `FromFile` option, the Python script uses the constant values to calculate the window. The values in the file need to more or less agree to eventually have the star in the window. → documentation issue?

**Comment by SaraRegibo** [comment]
@denisGrBach I've updated the documentation in the Python code.  Any other issues before I merge?

**Comment by denisGrBach** [comment]
This new feature has been successfully tested and validated using camera loop data. Since the changes applied to the camera geometry are pretty subtle, the file has been updated to contain double precision values. 
[cl2bCcds.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/5073081/cl2bCcds.txt)

**Comment by SaraRegibo** [comment]
- Merged #489.
- Added file with double-precision values in #499 (already merged).
