### ISSUE TITLE
Fullimage smearing strange value for column 2254

### ISSUE THREAD

**Issue by manugr788** [IvS-KULeuven/PlatoSim3#450]
I ran a full image simulation (4510 * 4510) and I got a strange result for smearing map, column 2254 (see attached file). I don't know if it is right or not,  and maybe due to an effect that I didn't expect.

Platosim develop branch : b3.3.7-18

[1000000000.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/4449921/1000000000.txt)
![smearingmap](https://user-images.githubusercontent.com/12544881/78774699-5288b380-7995-11ea-9bd6-29e2a5bf4834.PNG)

**Comment by SaraRegibo** [comment]
It can't be a coincidence that this is the last column of the left detector half...  The only place where we distinguish between the two detector halves is in applying the gain, so I will look there first.

**Comment by SaraRegibo** [comment]
Should be solved in #464 (in the develop branch).  Assigning to @manugr788 for closure.

**Comment by SaraRegibo** [comment]
Closing this issue.  @manugr788, if you do not agree with the implementation, please, re-open this issue.
