### ISSUE TITLE
truncated StarPositions record

### ISSUE THREAD

**Issue by drsamadi** [IvS-KULeuven/PlatoSim3#456]
Hi,
I'm generating twos simulations with 1000 exposures and with a linear drift imposed from a file.
In one simulation I have as expected 1000 records in StarPositions while for the second they are only 561. The simulations only differ by the presence of optical distortion which is not activated in the second one (the one with a truncated StarPositions record).  Note also that the subfield positions are not the same.

Here  a package containing the two simulations: https://upload.obspm.fr/get?k=pDRJSFS9SbzACRc4xms

Below the difference in the configuration file. The simulation with the problem is named psffit116.

Réza

diff psffit114.yaml  psffit116.yaml 
19c19
<     StarCatalogFile:                 inputfiles/catalogues/psffit113.coo
---
>     StarCatalogFile:                 inputfiles/catalogues/psffit116.coo
41,42c41,42
<     IncludeFieldDistortion:          yes             # Whether or not to include field distortion
---
>     IncludeFieldDistortion:          no             # Whether or not to include field distortion
231c231
<     ZeroPointColumn:                 3090               # Column of the (0,0) pixel of the subfield [pixels]
---
>     ZeroPointColumn:                 1400               # Column of the (0,0) pixel of the subfield [pixels]

**Comment by JorisDeRidder** [comment]
Hi Réza, just to be sure, did you already verify whether in the 561-simulation, the star is not simply moving out of the subfield because of the linear drift? Depending on how small a subfield you took, the optical distortion may put the star closer to the edge of the subfield.

**Comment by drsamadi** [comment]
Hi Joris,
yes you are right, by error I put my target close to the imagette border and after the 560 exposures it probably goes out of the imagette. Thanks for your help!  
Réza
