### ISSUE TITLE
ccdCoordinates <--> Field angles

### ISSUE THREAD

**Issue by PierreRoyer** [IvS-KULeuven/PlatoSim3#460]
Could we please add these 2 functions to referenceFrames.py ? They convert back & forth between ccd coordinates and field angles (angles from opt. axis; azimuth from X_FP).

import referenceFrames as rf
import numpy as np

def pixel2FocalPlaneAngles(ccdx, ccdy, ccdCode='4', pixelSize=18, focalLength=247.52):
    """
    INPUT
      ccdx,ccdy : pixel coordinates on the CCD
      ccdCode   : in ['1','2','3','4','1F','2F','3F','4F']
      pixelSize   [microns]
      focalLength [mm]

    OUTPUT
      angleFromOpticalAxis : angle from the optical axis
      azimuthFromXAxis     : azimuth angle from the X-axis of the reference CCD
    """
    
    ccdZeroPointX = CCD[ccdCode]["zeroPointXmm"]
    ccdZeroPointY = CCD[ccdCode]["zeroPointYmm"]
    ccdAngle      = CCD[ccdCode]["angle"]

    # Translate pix coord on CCD to FPA coord in mm
    xmm, ymm = rf.pixelToFocalPlaneCoordinates(ccdx, ccdy, pixelSize, ccdZeroPointX, ccdZeroPointY, ccdAngle)
    #
    angleFromOpticalAxis = rf.gnomonicRadialDistanceFromOpticalAxis(xmm,ymm,focalLength)

    azimuthFromXAxis = np.arctan2(ymm,xmm)

    return angleFromOpticalAxis,azimuthFromXAxis

def focalPlaneAngles2pixel(angleFromOpticalAxis, azimuthFromXAxis, ccdCode='4', pixelSize=18, focalLength=247.52):
    """
    INPUT
      angleFromOpticalAxis  : angle from the optical [degrees]
      azimuthFromXAxis      : azimuth from the X-Axis of Ref. CCD [degrees]

      ccdCode   : in ['1','2','3','4','1F','2F','3F','4F']
      pixelSize   [microns]
      focalLength [mm]

    OUTPUT
      x,y : pixel coordinates on the CCD
    """
    ccdZeroPointX = CCD[ccdCode]["zeroPointXmm"]
    ccdZeroPointY = CCD[ccdCode]["zeroPointYmm"]
    ccdAngle      = CCD[ccdCode]["angle"]

    xFPmm, yFPmm = rf.focalPlaneCoordinatesFromGnomonicRadialDistance(angleFromOpticalAxis, focalLength, inPlaneRotation=azimuthFromXAxis)
    xCCD, yCCD = rf.focalPlaneToPixelCoordinates(xFPmm, yFPmm, pixelSize, ccdZeroPointX, ccdZeroPointY, ccdAngle)

    return xCCD,yCCD

#### TESTS

for ccd in range(1,5):
    orientation =  np.deg2rad([0, 180, 270, 0, 90][ccd])
    for x,y in [[0,0],[0,4510],[4510,0],[4510,4510]]:
            
            theta,phi = np.rad2deg(pixel2FocalPlaneAngles(x,y,str(ccd)))

            print(f"Func - x,y,ccd {x:4d} {y:4d} {ccd:4d} - theta {theta:7.2f} phi {phi:7.2f}")

for ccd,theta,phi in [[1,18.43,90.9], [1,0.43,135], [1,25.23,135], [1,18.43,179.1], [2,0.43,-135], [3,18.43,-0.9], [4,18.43,0.9], [4,18.43,89.1]]:
    
            angleFromOpticalAxis = np.deg2rad(theta)
            azimuthFromXAxis = np.deg2rad(phi)
            
            x,y = focalPlaneAngles2pixel(angleFromOpticalAxis, azimuthFromXAxis, str(ccd))
            
            x,y = np.round(x,0),np.round(y,0)
            print(f"x,y,ccd {x:5.0f} {y:5.0f} {ccd:2d} - theta {theta:7.2f} phi {phi:7.2f}")

**Comment by JorisDeRidder** [comment]
Done.
