### ISSUE TITLE
Tutorials need fixing after new CCD ID standard

### ISSUE THREAD

**Issue by SaraRegibo** [IvS-KULeuven/PlatoSim3#462]
See #459:
 - `FineGuidanceStars/FineGuidanceStarsExample.ipynb`
 - `Photometry/PhotometryExample.ipynb`
- `InspectHDF5/Inspect HDF5 using simFile.ipynb`

**Comment by SaraRegibo** [comment]
@JorisDeRidder Could you have a look at this, please?  I would like to have this fixed before making a new release.  Thanks!

**Comment by Dries-Seynaeve** [comment]
We removed the tutorials in future releases.
