### ISSUE TITLE
Focal plane coordinates mirrored

### ISSUE THREAD

**Issue by denisGrBach** [IvS-KULeuven/PlatoSim3#469]
Since one of the latest updates, the the focal plane coordinates seem to be the projection on the plane +f rather than -f. Hence the coordinates are mirrored about x/y. See also equ. 11 in PLATO-KUL-PL-TN-0001 which has been changed to the previous version. Do I miss something here?

**Comment by JorisDeRidder** [comment]
Adapted pinhole projection to z=-f in the latest version in the Develop branch. Adapted PLATO-KUL-PL-TN-0001 accordingly.
If approved, please close the issue.

**Comment by SaraRegibo** [comment]
Hi @denisGrBach, do the coordinates now behave as expected?  If so, could you close this issue, please?  If not, do comment on this issue and we will look into it.  Thanks!

**Comment by JorisDeRidder** [comment]
I'll close the issue to declutter our issue list, but @denisGrBach feel free to come back to it.
