### ISSUE TITLE
isnan ambiguous in Detector.cpp

### ISSUE THREAD

**Issue by aaron-birch** [IvS-KULeuven/PlatoSim3#492]
Line 1937 in Detector.cpp:

if(isnan(rowFOV))

gives the error:
error: call of overloaded \u2018isnan(double&)\u2019 is ambiguous

I am using these compilers:
export CC=gcc-5
export CXX=g++-5

Other info that would helpful?

To avoid the problem, I changed this line to 
if(std::isnan(rowFOV))
but perhaps this is not the intention?

**Comment by JorisDeRidder** [comment]
Which subversion of gcc are you using?  gcc 5.1?

**Comment by aaron-birch** [comment]
(base) birch@plato1:~/platosim/download/build> gcc-5 -v
Using built-in specs.
COLLECT_GCC=gcc-5
COLLECT_LTO_WRAPPER=/usr/lib64/gcc/x86_64-suse-linux/5/lto-wrapper
Target: x86_64-suse-linux
Configured with: ../configure --prefix=/usr --infodir=/usr/share/info --mandir=/usr/share/man --libdir=/usr/lib64 --libexecdir=/usr/lib64 --enable-languages=c,c++,fortran,ada,go --enable-checking=release --with-gxx-include-dir=/usr/include/c++/5 --enable-ssp --disable-libssp --disable-libvtv --enable-libmpx --disable-plugin --with-bugurl=http://bugs.opensuse.org/ --with-pkgversion='SUSE Linux' --disable-libgcj --with-slibdir=/lib64 --with-system-zlib --enable-__cxa_atexit --enable-libstdcxx-allocator=new --disable-libstdcxx-pch --with-default-libstdcxx-abi=gcc4-compatible --enable-version-specific-runtime-libs --enable-linker-build-id --enable-linux-futex --program-suffix=-5 --without-system-libunwind --enable-multilib --with-arch-32=i586 --with-tune=generic --build=x86_64-suse-linux --host=x86_64-suse-linux
Thread model: posix
gcc version 5.2.1 20150721 [gcc-5-branch revision 226027] (SUSE Linux)

**Comment by JorisDeRidder** [comment]
Implemented the workaround in Detector.cpp in the develop branch. Our own computer system does not have such an old compiler (gcc 10.1 has recently come out), so I will need your help to test it with gcc 5.2.
