### ISSUE TITLE
Geometric Distortion

### ISSUE THREAD

**Issue by denisGrBach** [IvS-KULeuven/PlatoSim3#495]
The distortion implementation seems to be different to the model described in PLATO-DLR-PL-TN-0016. It uses r^3,r^5,r^7 instead of r^2,r^4,r^6. I checked the referenceFrame python script and came up with the following slightly simplified version of the distortion function: 

_def undistortedToDistortedFocalPlaneCoordinates(xFPmm, yFPmm, distortionCoefficients, focalLength):
coefficients = [1, 0, distortionCoefficients[0], 0, distortionCoefficients[1], 0, distortionCoefficients[2]]
distortionPolynomial = Polynomial(coefficients)
rFP = sqrt(xFPmm**2 + yFPmm**2) / focalLength       # Undistorted radial distance [normalised pixels]
distortion = distortionPolynomial(rFP)       	# Distortion-factor
xFPdist = xFPmm * distortion
yFPdist = yFPmm * distortion
return xFPdist, yFPdist_
	
Also, the default ‘distortioncoefficients.txt’ file seems to be outdated as it contains 4 coefficients instead of 3. Since you only have to convert from sky --> CCD, would there be a way **not** to use the inverted distortion (undistort)? This would simplify the interface because the inverted coefficients are not necessary available.

**Comment by JorisDeRidder** [comment]
@SaraRegibo Could you also update Section 8.6 "Field distortion" in PLATO-KUL-PL-TN-0006. You mentioned there a distortion law with odd exponents, but did not give a reference for it.

**Comment by JorisDeRidder** [comment]
@denisGrBach We currently do need the inverted coefficients. PlatoSim expects an input catalog with the position of the stars in equatorial sky coordinates.  However, sometimes users want to specify the position of the stars in pixel coordinates. In order not to bloat the C++ code with too many if-then-else structures, we currently simply convert those pixel coordinates to equatorial coordinates in Python prior to the PlatoSim run. For this we need the inverted distortion.

When the distortion is well behaved the inverted coefficients should be available. I believe this is the case for Plato.

**Comment by denisGrBach** [comment]
To be in line with PLATO-DLR-PL-TN-0016, Equation (13) and (14) in PLATO-KUL-PL-TN-0006 should read: 
`r_d = r*(k1*r^2 + k2*r^4 + k3*r^6) `
This would also agree with the code snipped given in the initial comment.

**Comment by SaraRegibo** [comment]
_From PLATO-DLR-PL-TN-0016:_

`radial component of the distortion = r * (k1 * r^2 + k2 * r^4 + k3 * r^6)`

with `r` the normalised radial distance (i.e. divided by the focal length).

---

_In PLATO-KUL-PL-TN-0006:_

- `r` = nomalised radial distance without distortion;
- `r_d` = normalised radial distance incl. distortion;
- → `radial component of the distortion = r_d - r  = r * (k1 * r^2 + k2 * r^4 + k3 * r^6)` (which is exactly what Eq. (19) says)

---

So I don't think the formulae in TN0006 should be changed...  But I will include a reference to the DLR TN!

**Comment by denisGrBach** [comment]
yes, that's right. I guess my initial point was to simplify the actual calculation with:

```
r_d = r + r * (k1 * r^2 + k2 * r^4 + k3 * r^6)
r_d = r * (1 + k1 * r^2 + k2 * r^4 + k3 * r^6)
```
Hence:
```
x_d = x * (1 + k1 * r^2 + k2 * r^4 + k3 * r^6)
y_d = y * (1 + k1 * r^2 + k2 * r^4 + k3 * r^6)
```
