### ISSUE TITLE
Quantization

### ISSUE THREAD

**Issue by denisGrBach** [IvS-KULeuven/PlatoSim3#496]
The ‘includeQuantisation’-switch also seems to also eliminate gain and offset. I tried to get an error free (noise/bias) float output but didn’t succeed.

**Comment by SaraRegibo** [comment]
As documented on the website:

> ### **IncludeQuantisation**
> _Allowed values:_ "yes" and "no"
> 
> Indicates whether or not to apply quantisation. This includes:
> 
> - applying gain (FEE and CCD), hence converting from electrons to ADUs,
>  - adding electronic offset,
> - forcing the ADU values to be integers,
> - and applying digital saturation (can be switched off separately).

**Comment by SaraRegibo** [comment]
Assigning back to @denisGrBach for closure, as this is expected behaviour.
