### ISSUE TITLE
Need for new jitter file

### ISSUE THREAD

**Issue by SaraRegibo** [IvS-KULeuven/PlatoSim3#497]
Over the years, we have gathered a set of jitter files, but they are old (and probably outdated) and in the end we don't remember which file represents which data and where we got them from.  They idea is to throw them all away and replace them by one single file (which would have to be used for PlatoSim and PIS), and properly document that (in PLATO-KUL-PL-TN-006).

@denisGrBach, could you provide such a file, please, together with a short description for the TN?  This file should contain four columns, separated by a space, holding the following information:

- time [s];
- yaw [arcsec];
- pitch [arcsec];
- roll [arcsec].

---

To be investigated: are we allowed to distribute this file in the PlatoSim repository?

**Comment by nicholasjannsen** [comment]
I'm closing this issue since we have several deliveries from Prime. These are saved in our KUL Nextcloud with the appropriate TN.
