### ISSUE TITLE
problem with installing platosim

### ISSUE THREAD

**Issue by MessinaSergio** [IvS-KULeuven/PlatoSim3#504]
when running the following command

conda install -c https://jenkins.miricle.org/platosim.devel/ platosim

I get the following message

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                       

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

How di I resolve?
Thanks,
Sergio Messina

Info:
gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by crauterb** [comment]
You need to make sure that you use one of the supported Python Versions.
From the [documentation](https://ivs-kuleuven.github.io/PlatoSim3/user-prerequisites.html) you can see that "Supported Python versions are 3.5, 3.6, and 3.7".

So, when creating your Conda Environment, make sure that you use one of these version, e.g.
`conda create -n platosim python=3.7`

**Comment by MessinaSergio** [comment]
Thanks a lot. I used a later python version 3.8.3.

Now, I used 3.7 and it works.
Best regards,
Sergio Messina

Il giorno mar 6 ott 2020 alle ore 11:20 Christoph Rauterberg <
notifications@github.com> ha scritto:

**Comment by MessinaSergio** [comment]
Next step.

I like to be just user of Platosim.
 However, I did conda install and conda update as described in the
following.

develop

For the develop branch, these commands must be replaced by

$ conda install -c https://jenkins.miricle.org/platosim.devel/ platosim

and

$ conda update --force-reinstall -c
https://jenkins.miricle.org/platosim.devel/ platosim

respectively.

do I have to run

master

To install the latest successfully built version of the master branch,
type:

$ conda install -c https://jenkins.miricle.org/platosim/ platosim
?

Sergio



Il giorno mar 6 ott 2020 alle ore 12:10 Messina, Sergio <
sergio.messina@inaf.it> ha scritto:

**Comment by SaraRegibo** [comment]
To install the most recent release of PlatoSim (so that would be the master):

`conda install -c https://jenkins.miricle.org/platosim/ platosim`

**Comment by MessinaSergio** [comment]
after the command
conda install -c https://jenkins.miricle.org/platosim/ platosim

I get
Collecting package metadata (current_repodata.json): failed

CondaHTTPError: HTTP 401 UNAUTHORIZED for url <https://jenkins.miricle.org/platosim/osx-64/current_repodata.json>
Elapsed: 00:00.201435

The credentials you have provided for this URL are invalid.

You will need to modify your conda configuration to proceed.
Use `conda config --show` to view your configuration's current state.
Further configuration help can be found at <https://conda.io/docs/config.html>.

**Comment by SaraRegibo** [comment]
@MessinaSergio Does it work now with the provided credentials (in the `platosim-workshop` channel on Slack)?  If so, you can close this issue.  Thanks!
