### ISSUE TITLE
Some trouble with the routine createStarCatalogFileFromPixelCoordinates()

### ISSUE THREAD

**Issue by drsamadi** [IvS-KULeuven/PlatoSim3#506]
I've some trouble with the routine createStarCatalogFileFromPixelCoordinates(row, col, magnitude, starID, starCatalogFileName) provided by the module simulation.py  (-> see   this application https://github.com/IvS-KULeuven/PlatoSim3/blob/develop/python/Examples/demo_createStarCatalog.py )

When I run PSIM, the star is not present in my imagettes.  
This is clearly a distortion issue because when I turn off the distortion I find my star at the right place.
However, according to the source code, createStarCatalogFileFromPixelCoordinates() is supposed to takent the distortion  into account. 

I think the problem in createStarCatalogFileFromPixelCoordinates() comes from this following instruction:     
     if (includeFieldDistortion == "yes"):
            xFPmm,  yFPmm = rf.distortedToUndistortedFocalPlaneCoordinates(xFPmm,  yFPmm, inverseDistortionCoefficients, focalLength)

includeFieldDistortion is a boolean, accordingly I guess the correct instruction is:   
   if (includeFieldDistortion):
...

 Doing this change solves my problem: distortion is correctly taken into account and my star is present in the imagette.

**Comment by SaraRegibo** [comment]
Assigning to @drsamadi for closure.

**Comment by drsamadi** [comment]
Fixed ! thanks
