### ISSUE TITLE
Question: meaning of the parameter CCD/ Gain/AllowedDifference

### ISSUE THREAD

**Issue by drsamadi** [IvS-KULeuven/PlatoSim3#507]
The meaning of this parameter is not clear to me. 
Changing the value of this parameter (e.g CCD/ Gain/AllowedDifference = 100 [%]) has not impact at all  on the pixel intensity. Here attached an example of the configuration file I'm using. My simulation contains a single star and no background. 

This is the same also for the parameter named  FEE/ Gain/AllowedDifference: no impact at all. 

[11.yaml.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/5378998/11.yaml.txt)

**Comment by SaraRegibo** [comment]
The gain (for the FEE as well as for the CCD) is specified per detector half, but there are restrictions on how much they can differ.

PlatoSim will use `RefValueLeft` and `RefValueRight` (+ temperature dependency, if applicable) but will check whether the difference  in gain between both detector halves will not exceed the configured requirements (`AllowedDifference`).  A warning will be logged if the difference becomes too big.

**Comment by SaraRegibo** [comment]
@drsamadi Please, close this issue if my comment from above clarifies the issue for you.  Thanks!

**Comment by drsamadi** [comment]
OK thanks Sara!
