### ISSUE TITLE
Analytical Non Gaussian PSF: strange orientation of the PSF on the CCD

### ISSUE THREAD

**Issue by drsamadi** [IvS-KULeuven/PlatoSim3#511]
Hi,

I've run a microscanning simulation in order to test our PSF inversion technique with simulations made with PLATOSim. However, when  I use an Analytical Non Gaussian PSF, the inverse PSF I get   has an unexpected orientation w.r.t the PSF stored in the data set named "PSF/HighResPSFmapCenterSubfield".
Indeed, the PSF reconstructed by inversion looks like this: 
![sim06_2](https://user-images.githubusercontent.com/19569211/97471013-8e429500-1948-11eb-9b20-45bbfc049147.png)
whereas the 'true' PSF stored in "PSF/HighResPSFmapCenterSubfield" looks like this:
![sim06_1](https://user-images.githubusercontent.com/19569211/97471134-b3cf9e80-1948-11eb-82ab-977c5aa1322a.png)

I initially thought that this was a problem of convention regarding the orientation of the X axis and Y axis of the CCD. 
However, in the same condition of simulation, I get a consistent orientation when using instead a MappedFromFileSymmetrical PSF. 
Indeed the inverse PSF looks as: 
![sim07_2](https://user-images.githubusercontent.com/19569211/97471478-0f9a2780-1949-11eb-80cc-3fa21af1aee3.png)
while the 'true' PSF taken PSF/rotatedPSF" from looks as follow:
![sim07_1](https://user-images.githubusercontent.com/19569211/97472267-f2198d80-1949-11eb-8c63-867a7f9ef1c8.png)

My star is located in CCD 2 (new CCD label), at the focal plane position Xfp,Yfp = -57.1099 -3.2799 and CCD position Xccd,Yccd = 110,1410  (here X-> column , Y-> row).
According to the star location, the MappedFromFileSymmetrical  PSF is oriented as expected: almost vertically (i.e. along the Y axis of the CCD2) both for the inverse PSF and the "true" one taken from "PSF/rotatedPSF"  .
This is not the case for the reconstructed  PSF obtained when using an Analytical Non Gaussian PSF.
The two data sets can be downloaded here:  
https://zendto.obspm.fr/pickup?claimID=PoXcWwzor2kr843V&claimPasscode=oNV72XHJAphgaWQA&emailAddr=reza.samadi%40obspm.fr

My PlatoSim version: 3.3.7-350-g0175b39

**Comment by JorisDeRidder** [comment]
Surprising indeed. Must be the way we save the PSF image into the HDF5 file. We'll look into it.

**Comment by carstenpaproth** [comment]
There is a FIXME in the code which could be the cause of the problem:

[https://github.com/IvS-KULeuven/PlatoSim3/blob/387ef87dc8b26e820c8108cbf5ffcc290cd989e3/source/DetectorWithAnalyticNonGaussianPSF.cpp#L569](https://github.com/IvS-KULeuven/PlatoSim3/blob/387ef87dc8b26e820c8108cbf5ffcc290cd989e3/source/DetectorWithAnalyticNonGaussianPSF.cpp#L569)

**Comment by drsamadi** [comment]
> Surprising indeed. Must be the way we save the PSF image into the HDF5 file. We'll look into it.

OK Joris,  but note that in the case of the Analytical Non Gaussian PSF the reconstructed PSF is not correctly oriented given the star position in CCD#2.

**Comment by drsamadi** [comment]
Hi, 
here below an other example for a star falling on CCD1 at (Xfp, Yfp) =  (-60.257690998060475, 1.4505290352559383) and (X_CCD,Y_CCD) =  (3275.427277670027, 4501.6372758191155 )
The PSF reconstructed by inversion looks like this:
![Screenshot from 2020-11-02 21-18-33](https://user-images.githubusercontent.com/19569211/97915196-5b860b80-1d51-11eb-8f2d-c1e63aa6173e.png)
whereas the "true" PSF (stored "PSF/HighResPSFmapCenterSubfield") looks as:
![Screenshot from 2020-11-02 21-17-59](https://user-images.githubusercontent.com/19569211/97915218-693b9100-1d51-11eb-9807-4e25a74e0829.png)

The "true" PSF has a consistent orientation given the position of the star on CCD1. 
The reconstructed PSF is here rotated by 180 deg but here again it is not orientated as expected. .
In the previous example the reconstructed PSF was rotated by 270 deg w.r.t. the "true" one.
Apparently the rotation angle is associated with the orientation of the CCD.

**Comment by carstenpaproth** [comment]
@JorisDeRidder 

Why is the code which applies the CCD orientation to the analytical PSF commented out?
I think this explains the discrepancy Réza observed.

[https://github.com/IvS-KULeuven/PlatoSim3/blob/387ef87dc8b26e820c8108cbf5ffcc290cd989e3/source/DetectorWithAnalyticNonGaussianPSF.cpp#L565](https://github.com/IvS-KULeuven/PlatoSim3/blob/387ef87dc8b26e820c8108cbf5ffcc290cd989e3/source/DetectorWithAnalyticNonGaussianPSF.cpp#L565)


```
    // Construct the PSF around the central pixel coordinates

    IntegralOfAnalyticSignalResponse psf(size, diffusionKernelWidth);

    // FIXME
    // double ccdOrientation = getOrientationAngle();
    // p -= ccdOrientation;

    integrateAnalyticPSF(psf, column0, row0, r, p);
```

**Comment by JorisDeRidder** [comment]
@Reza: are you using the master or the develop version?

**Comment by drsamadi** [comment]
I'm using the develop version: PlatoSim 3.3.7-350-g0175b39

**Comment by SaraRegibo** [comment]
@drsamadi Hi Réza, sorry for the delay.  This issue was closed automatically when I merged the corresponding pull request (re-opening it now).  Could you, please, confirm that it works for you (in the latest version of the develop branch)?  If so, you can close the issue.  Thanks!

**Comment by drsamadi** [comment]
Hi Sara
I've updated platosim (now I have PlatoSim 3.3.7-368-g258ac69 ), however the orientation of the reconstructed PSF is unchanged, i.e. still rotated w.r.t the true PSF.

**Comment by drsamadi** [comment]
Hi Sara,
the current version PlatoSim 3.3.7-376-g19cf35e 
now solves this issue. Thanks
