### ISSUE TITLE
problem with building development version of PlatoSim

### ISSUE THREAD

**Issue by mammler** [IvS-KULeuven/PlatoSim3#525]
Building the developer version of PlatoSim with the following command fails:
make -j 4
Error log is attached:
[errors.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/5703186/errors.txt)

What I tried before:
a) Install everything in one go with ./install.sh ... failed.
b) Installed dependencies one by one ... ok, after removing conda-forge from .condarc following proposal by César in comment section of https://issues.cosmos.esa.int/platowiki/x/9AaFAQ
c) make -j 4 in environment with conda-forge channel ... failed.
d) make -j 4 in environment without conda-forge channel ... failed
e) installation of user version of PlatoSim with miniconda ... ok but I need the developer version for plato-test-prep.

PlatoSim version: v3.2.0-RC1-1353-gd8fad21
Operating system: Mac OS X 10.15.7
gcc (MacPorts gcc5 5.5.0_6) 5.5.0
Apple clang version 12.0.0 (clang-1200.0.32.27)
Python 3.7.7
cmake version 3.19.1
Installation procedure followed: http://ivs-kuleuven.github.io/PlatoSim3/dev-overview.html
and: https://issues.cosmos.esa.int/platowiki/x/9AaFAQ

Thank you!

**Comment by SaraRegibo** [comment]
Hi Matthias,

I cannot immediately see what is causing the problem, but in the meantime, let's try to get you started with the installation with Conda (see also http://ivs-kuleuven.github.io/PlatoSim3/user-install.html)!

Make a fresh Conda environment (with Python 3.5, 3.6. or 3.7) and install the develop version of PlatoSim with the following command:

`conda install -c https://jenkins.miricle.org/platosim.devel/ platosim`

To update it, use

`conda update --force-reinstall -c  https://jenkins.miricle.org/platosim.devel/ platosim`

Don't forget to activate your Conda environment before executing any of these commands (with `conda activate`).

Let me know whether that works for you.

Of course, the issue you report here needs to be looked into, but at least you are not blocked anymore.

**Comment by JorisDeRidder** [comment]
Could show the output of the `cmake` command when you do a fresh installation, as well as the **full** output of `make`? 
Also the full output of `gcc --version` and `clang --version`.

**Comment by mammler** [comment]
Thank you, @SaraRegibo ! I need credentials to execute the conda install. Could you please share?

UPDATE: credentials needed only for https://jenkins.miricle.org/platosim/

I'll use https://jenkins.miricle.org/platosim.devel/ anyway. No credentials needed there.

Installed successfully PlatoSim 3.3.7-435-g058efd0
testplatosim ok

Thank you very much!

**Comment by mammler** [comment]
> Could show the output of the `cmake` command when you do a fresh installation, as well as the **full** output of `make`?
> Also the full output of `gcc --version` and `clang --version`.

Outputs below created with > output.txt 2> errors.txt. Is this what you need, @JorisDeRidder ?
[cmake_errors.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/5707781/cmake_errors.txt)
[cmake_output.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/5707782/cmake_output.txt)
[make_output.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/5707786/make_output.txt)
[make_errors.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/5707783/make_errors.txt)

$ gcc --version:
gcc (MacPorts gcc5 5.5.0_6) 5.5.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ clang --version:
Apple clang version 12.0.0 (clang-1200.0.32.27)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Thank you!

**Comment by JorisDeRidder** [comment]
Could you retry from scratch with the latest version of the develop branch that I just adapted?

**Comment by mammler** [comment]
> Could you retry from scratch with the latest version of the develop branch that I just adapted?

Nice job! No need to tweak .condarc.

Installed successfully PlatoSim 3.3.7-437-g7b38148
testplatosim ok

Thank you very much!
