### ISSUE TITLE
Use of a MappedFromFileAsymmetrical PSF with sub-pixel resolution is 1/64 generates an error

### ISSUE THREAD

**Issue by drsamadi** [IvS-KULeuven/PlatoSim3#530]
Hi,

I'm trying to use the new sets of PSF calculated by Martin Pertenais. They have a  sub-pixel resolution of 1/64 and a physical size of 8 pixels.  However, I get the following message:

_2020-12-20 17:09:44 ERROR   ArrayOperations.rebin: rebinning currently only implemented to smaller dimensions.
terminate called after throwing an instance of 'IllegalArgumentException'
  what():  ArrayOperations.rebin: rebinning currently only implemented to smaller dimensions.
Aborted (core dumped)_

The message disappears when I set the parameter PSF/MappedFromFileAsymmetrical/NumberOfPixels  = 4
[instead of the physically correct value of 8]

A package containing the PSF, my configuration files and the  log file can be downloaded from:  
https://zendto.obspm.fr/pickup?claimID=pbgXtcHoC8vvjsYk&claimPasscode=UMyKswHoiXFz47YE&emailAddr=reza.samadi%40obspm.fr

I'm using PlatoSim 3.3.7-435-g058efd0
  
Réza

**Comment by SaraRegibo** [comment]
Hi Réza,

The problem arises when the PSF is re-binned to the sub-pixel resolution of the sub-field.  This can only succeed if the number of sub-pixels per pixels for the PSF is at least the number of sub-pixels per pixel for the sub-field.

- number of sub-pixels per pixel for the sub-field → `sim["SubField/SubPixels"]` → 128 in your case;
- number of sub-pixels per pixel for the PSF → calculated from the dimensions of the PSF maps (those are given in sub-pixels) and the dimensions of the PSF as in the configuration file (those are given in pixels in `sim["PSF/MappedFromFileAsymmetrical/NumberOfPixels"]`) → 64 in your case (512 / 8).

I'll implement a specific check on this and throw an exception with a proper message when this condition is not met.

**Comment by SaraRegibo** [comment]
@drsamadi Implemented as explained above, in PR #531 (develop branch only).  Assigning to you for closure.

**Comment by drsamadi** [comment]
Hi Sara
thanks for the feedback. I indeed forgot to adapt the working subpixel resolution of my simulation. Having a check is  by the way a good idea!
