### ISSUE TITLE
Time shift should not be applied when reading out the CCDs for the F-CAMs.

### ISSUE THREAD

**Issue by SaraRegibo** [IvS-KULeuven/PlatoSim3#540]
The time shift of 6.25s between the start of the readout of subsequent CCDs, should not be applied for the F-CAMs.  For those cameras, the CCDs are read out at the same time.  This requires changes in the code in the application of the jitter and the TED, and in the `Simulation` class.

The documentation must be updated accordingly.

**Comment by denisGrBach** [comment]
Hi Sara,

I noticed that it is set this way and changed the “TimeShift” parameter in the yaml-File. Its seemed to work that way. Did I miss something?

Cheers,
Denis



Von: Sara Regibo <notifications@github.com>
Gesendet: Donnerstag, 21. Januar 2021 14:23
An: IvS-KULeuven/PlatoSim3 <PlatoSim3@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [IvS-KULeuven/PlatoSim3] Time shift should not be applied when reading out the CCDs for the F-CAMs. (#540)


The time shift of 6.25s between the start of the readout of subsequent CCDs, should not be applied for the F-CAMs. For those cameras, the CCDs are read out at the same time. This requires changes in the code in the application of the jitter and the TED, and in the Simulation class.

The documentation must be updated accordingly.

**Comment by SaraRegibo** [comment]
If `sim["CCD/Position"] == "Custom"`, we use `sim["CCD/TimeShift"]` (which is set to 0s).

If you use a pre-defined CCD position (rather than a custom one), the time shift from `sim[CCDPositions/TimeShifts]` will be used instead (i.e. 0, 6.25, 12.5, and 18.75s), irrespectively of the type of camera that will be used.  So if you read out CCD 2/3/4 for an F-CAM (`sim["Telescope/GroupID"] == "Fast"`), you will also apply these time shifts (which should not happen).
