### ISSUE TITLE
An output PSF with NaN values

### ISSUE THREAD

**Issue by drsamadi** [IvS-KULeuven/PlatoSim3#543]
Hi,
depending on the input star catalogue, some simulations provide as output a  PSF that contains NaN values:

![Screenshot from 2021-02-02 10-31-06](https://user-images.githubusercontent.com/19569211/106616848-4bf3aa00-656e-11eb-9d9d-8adcf8c96a9e.png)

I'm using AnalyticNonGaussian PSF  and I'm trying to generate a full CCD image with an input  star catalogue that covers the full field of view of a camera. 

The simulation output,  the YAML file and the input catalogue can be downloaded from here:
https://zendto.obspm.fr/pickup?claimID=hituPtmhzKx2rvpw&claimPasscode=eNvxBVDehjQorEXW  

This is a strange bug since changing only the input star catalogue and the pointing direction of the camera provides the expected PSF. The corresponding data package is available here 
https://zendto.obspm.fr/pickup?claimID=23P8XjWF6wxWgzK4&claimPasscode=rBzHQ8aqQ7ZkqbKs  

Réza

 platosim -version
PlatoSim 3.3.7-435-g058efd0

**Comment by carstenpaproth** [comment]
@drsamadi 
If you make a simulation with multiple stars and the AnalyticNonGaussian PSF, then every star uses a different PSF for the flux distribution. But there is only a single highres PSF in the hdf5 files which seems to be created for the middle of the subfield, so it is weird that you get different results with the same subfield parameters. The full CCD images look ok to me, so there seems to be no "nan" problem in the analytical PSF itself.

**Comment by carstenpaproth** [comment]
I think I found the cause of the bug: The highresmap seems to contain some garbage sometimes and there is an unnecessary plus in
https://github.com/IvS-KULeuven/PlatoSim3/blob/014a3df536eda6934bf117f42a078d3952a28356/source/DetectorWithAnalyticNonGaussianPSF.cpp#L748

This should solve the problem:
`highResMap.at(y, x) = psf(x - sx, y - sy) * 1000.0;`

**Comment by drsamadi** [comment]
Hi Carsten,
thanks for your feedback. Two questions:
Why should the PSF contain some "garbage" ? why  the resulting PSF depends on the input star catalogue ?

**Comment by carstenpaproth** [comment]
Hi Réza,
No the PSF doesn't contain garbage, but the highresmap seems to contain garbage before the PSF is added. I don't know why, it seems to be not initiallized with zeros. Actually there is no need to add the PSF to the highresmap, it is sufficient to replace the highresmap with the PSF, that solves the problem. I think it is a random coincidence that it depends on the input catalog.

**Comment by Dries-Seynaeve** [comment]
Hi Réza and Carsten, 

The bug should have been fixed in the latest version of the develop branch. The problem was that the highResMap matrix was not properly initialized and contained NaN values.

**Comment by Dries-Seynaeve** [comment]
If this fixes it, you can close the issue. :)

**Comment by drsamadi** [comment]
Problem fixed in PlatoSim 3.3.7-462-g8177ec0, thanks!
