### ISSUE TITLE
Record cosmic particle hits in output HDF5 file

### ISSUE THREAD

**Issue by reneheller** [IvS-KULeuven/PlatoSim3#553]
As far as I can see, cosmic particle hits on the CCD are not currently recorded in PLATOSim's HDF5 output file. Such a recording would be very helpful to develop our outlier detection algorithms (e.g. I'd like to know which cosmic particles my algorithms fail to detect). Would it be possible to store the CCD pixels (x and y coordinates) of a subfield that are affected by cosmics? If there is no cosmic in a given exposure, then the value could just be COSMICS = ''. And if there are pixels affected, the value could be something like COSMICS = '(2,1), (2,2), (2,3)', as an example, for a a short vertical trail.

I'm using PLATOSim v3.3.6.

**Comment by JorisDeRidder** [comment]
Hi Rene, OK, we'll look into this. One thing that crosses my mind: the far end of a cosmic trail will still appear in the list of pixels affected, but the impact will likely be well below the noise.

**Comment by reneheller** [comment]
Hi Joris! As long as the contribution in the trail is of the order of parts per million in a given pixel, I think it could be relevant to the algorithm. But you're right, in the far trail the numerical contribution by the cosmic can formally be > 0 although insignificant to the measurements. Maybe you introduce a low cut and set the contribution of the cosmic to zero whenever it really contributes < 1e-9 to the readout of that pixel?

**Comment by Dries-Seynaeve** [comment]
Hi Rene, I have implemented this feature. It is now possible to see the columns, rows and flux values of the Cosmics in the output HDF5 file. This can be switched on/off though the input.yaml file using the `WriteCosmics` parameter. 

The row, column and flux values can also be obtained from the python method `getCosmicsCoordinates(imageNr, field)` of the `SimFile` class. The field variable is an (optional) parameter that determines on what field you are looking for the cosmics. The allowed values are: `"SubField"`, `"BiasMapLeft"`, `"BiasMapRight"` or `"SmearingMap"`, where `"SubField"` is the default value. 
For example:      

  ```
file = SimFile("output.hdf5")
row, col, flux = file.getCosmicsCoordinates(4, "SmearingMap) 
```

**Comment by reneheller** [comment]
Hi Dries!

Awesome!

– I've just upgraded my PLATOSim installation (v. 3.3.7-6-g05ec691)
– then added the following line to my YAML input file
      `WriteCosmics:                  yes             # write cosmics`
– then ran PLATOSim with this modified YAML file
– and then tried to retrieve the cosmics from within my python environment as you suggested:

```
from simfile import *
file = SimFile("myOutputfile.hdf5")
row, col, flux = file.getCosmicsCoordinates(4, "SubField")

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-b40ee0fad883> in <module>
----> 1 row, col, flux = file.getCosmicsCoordinates(4, "SubField")

AttributeError: 'SimFile' object has no attribute 'getCosmicsCoordinates'
```

I looked at the simfile that I'm using at

`/opt/miniconda3/envs/platosim/python/simfile.py`

and I found that it still belongs to my old PLATOSim installation. This is weird, I did an upgrade today via

`conda install -c https://jenkins.miricle.org/platosim/ platosim`

as described on the PLATOSim github website (cheers to Sara for great support!). Can you tell how I can retrieve the latest version of the simfile.py that includes the python function `getCosmicsCoordinates(imageNr, field)`?

**Comment by Dries-Seynaeve** [comment]
Hello Rene. 

I have implemented this feature in the develop branch but not yet in our master branch. We will update the master branch soon, and then this feature will also be accessible from there. For now, the develop branch is the only way to use this.

**Comment by JorisDeRidder** [comment]
Hi René, if you're happy with the current implementation (now both in the master as well as in the develop branch), can you close this issue? Thanks!

**Comment by reneheller** [comment]
Hey Joris! I've upgraded my PLATOSim installation to PlatoSim version 3.3.7-521-g9d41e0a1 (← as per the log file of a new simulation). But it seems the input yaml file needs a new input parameter:

```
2021-04-07 10:29:57 ERROR   ConfigurationParameters: The sub-field "TimeShift" of field "CCD" is not available in the configuration file (/Users/heller/Astronomy/programming/PLATOSim_data/inputfiles/inputfile.yaml).
libc++abi.dylib: terminating with uncaught exception of type IllegalArgumentException: ConfigurationParameters: The sub-field "TimeShift" of field "CCD" is not available in the configuration file (/Users/heller/Astronomy/programming/PLATOSim_data/inputfiles/inputfile.yaml).
Abort trap: 6
```

I can't find the `TimeShift`sub-field explained at [https://ivs-kuleuven.github.io/PlatoSim3/ConfigurationParameters.html](https://ivs-kuleuven.github.io/PlatoSim3/ConfigurationParameters.html). Could you please let me know how I need to modify my yaml configuration file to make it compatible with the latest PLATOSim version?

**Comment by Dries-Seynaeve** [comment]
Hello Rene. You can find an up-to-date input file at the location: /PlatoSim3/inputfiles/inputfile.yaml.

**Comment by reneheller** [comment]
Hi Dries! Cheers – I found the new inputfile.yaml and modified it according to my needs. I then drilled into the data structure of the resulting HDF5 file to find the new information about the cosmics.

```
In [1]: import h5py

In [2]: HDF5_IMAGETTES = h5py.File('myOutputfile.hdf5', 'r')

In [3]: HDF5_IMAGETTES.keys()
Out[3]: <KeysViewHDF5 ['ACS', 'Background', 'BiasMapsLeft', 'BiasMapsRight', 'Cosmics', 'ExtendedGhostPositions', 'Flatfield', 'Images', 'InputParameters', 'PSF', 'Photometry', 'PointLikeGhostPositions', 'SmearingMaps', 'StarCatalog', 'StarPositions', 'Telescope', 'ThroughputMaps', 'TransmissionEfficiency', 'Version']>

In [4]: HDF5_IMAGETTES['Cosmics'].keys()
Out[4]: <KeysViewHDF5 ['BiasMapLeft', 'BiasMapRight', 'SmearingMap', 'SubField']>

In [5]: HDF5_IMAGETTES['Cosmics']['SubField'].keys()
Out[5]: <KeysViewHDF5 ['exposure000000', 'exposure000001', 'exposure000002', 'exposure000003', 'exposure000004', 'exposure000005', 'exposure000006', 'exposure000007', 'exposure000008', 'exposure000009', 'exposure000010', 'exposure000011', 'exposure000012', 'exposure000013', 'exposure000014', 'exposure000015', 'exposure000016', 'exposure000017', 'exposure000018', 'exposure000019', 'exposure000020', 'exposure000021', 'exposure000022', 'exposure000023', 'exposure000024', 'exposure000025', 'exposure000026', 'exposure000027', 'exposure000028', 'exposure000029', 'exposure000030', 'exposure000031', 'exposure000032', 'exposure000033', 'exposure000034', 'exposure000035', 'exposure000036', 'exposure000037', 'exposure000038', 'exposure000039', 'exposure000040', 'exposure000041', 'exposure000042', 'exposure000043', 'exposure000044', 'exposure000045', 'exposure000046', 'exposure000047', 'exposure000048', 'exposure000049', 'exposure000050', 'exposure000051', 'exposure000052', 'exposure000053', 'exposure000054', 'exposure000055', 'exposure000056', 'exposure000057', 'exposure000058', 'exposure000059', 'exposure000060', 'exposure000061', 'exposure000062', 'exposure000063', 'exposure000064', 'exposure000065', 'exposure000066', 'exposure000067', 'exposure000068', 'exposure000069', 'exposure000070', 'exposure000071', 'exposure000072', 'exposure000073', 'exposure000074', 'exposure000075', 'exposure000076', 'exposure000077', 'exposure000078', 'exposure000079', 'exposure000080', 'exposure000081', 'exposure000082', 'exposure000083', 'exposure000084', 'exposure000085', 'exposure000086', 'exposure000087', 'exposure000088', 'exposure000089', 'exposure000090', 'exposure000091', 'exposure000092', 'exposure000093', 'exposure000094', 'exposure000095', 'exposure000096', 'exposure000097', 'exposure000098', 'exposure000099']>

In [6]: HDF5_IMAGETTES['Cosmics']['SubField']['exposure000000'].keys()
Out[6]: <KeysViewHDF5 ['Columns', 'Flux', 'Rows']>

In [7]: HDF5_IMAGETTES['Cosmics']['SubField']['exposure000000']['Flux'][...]
Out[7]: array([-1], dtype=int32)
```
All the 'Flux' entries I looked at have a value of -1. Is this the default value if there is no cosmic? What are the other possible values? 0 and 1? What would the other values signify?

Moreover, what does a value of -1 actually mean for 'Columns' in a specific exposure?

```
In [8]: HDF5_IMAGETTES['Cosmics']['SubField']['exposure000000']['Columns'][...]
Out[8]: array([-1], dtype=int32)
```

**Comment by Dries-Seynaeve** [comment]
If the flux has a value -1, that means that there were no cosmics recorded. If that is the case, than the value for the columns and rows will also be -1. So you should only see a value of -1 in 'Columns' if there was no cosmic added to the subfied.

**Comment by reneheller** [comment]
So I produced a simulation that contains an outlier in the 33. exposure of the extracted flux (I can see it in the light curve). Doing the above exercise with this exposure gives me

```
In [1]: HDF5_IMAGETTES['Cosmics']['SubField']['exposure000033']['Flux'][...]
Out[1]: array([ 6635.62092371, 17355.9027275 ,  3029.31075498,  6642.04872904])
```
which shows that there is indeed an outlier. Yeehaw! But what do those numbers tell me? The flux value of the outlier is 240898.47119141. But this number does not correspond to any of the numbers in the output above.

**Comment by Dries-Seynaeve** [comment]
The values in this array correspond to the flux in a pixel that is added due to cosmics.  To know which pixel has the cosmic flux added, one can use the corresponding "Columns" and "Rows" values.   E.g. the second "flux" values correspond to the second "Rows" and "Columns" value. 

I suspect that the outlier flux value you mentioned also takes other effects into account, as the sky background. If you would like, I would be happy to take a look at your output hdf5 file.
