### ISSUE TITLE
Brighter-fatter effect (BFE) doesn't effect photon transfer curve (PTC)

### ISSUE THREAD

**Issue by carstenpaproth** [IvS-KULeuven/PlatoSim3#555]
I tried to derive a PTC from PLATOSim simulations by varying the sky background to mimic different flatfield intensities. Unfortunately, the resulting PTC is just linear, but actually it is expected that the BFE causes a deviation from linearity in the PTC. Réza can simulate the correct behavior with PIS which uses the same BFE-model and -parameters as PLATOSim, so there seems to be a bug in PLATOSim that the BFE is not applied correctly.

Here is what I get from PLATOSim (latest version from develop branch):
[platosim_ptc.pdf](https://github.com/IvS-KULeuven/PlatoSim3/files/6091282/platosim_ptc.pdf)

And here is what I get from real CCD measurements:
[plato_ccd_ptc.pdf](https://github.com/IvS-KULeuven/PlatoSim3/files/6091298/plato_ccd_ptc.pdf)

**Comment by JorisDeRidder** [comment]
Thanks, Carsten, for the report. We're looking into this.

**Comment by BartVandenbussche** [comment]
I think the BFE is applied correctly, isn't the problem that the photon noise is added very late in platosim ?  You start with a flat illumination without noise (by setting the sky background high).  If you apply a convolution of the BFE kernel on a perfectly flat, image without noise you just get another perfectly flat image without noise.  The covariance has not changed.  The variance deviation from the linear PTC is the covariance introduced by the BFE kernel.  Is there a reason why we don't apply the shot noise when we are no longer dealing with photons, e.g. after the PSF convolution ?

**Comment by drsamadi** [comment]
Bart, 
yes your are right this is perhaps because the BFE is applied before shot noise.
Actually without out random noise BFE has not impact on the PTC and covariance btw adjacent pixels as this is well explained for instance in Astier et al 2019 (A&A).
Accordingly, shot noise shall be applied before BFE.
This is so in my simulator PIS and I get consistent results for the PTC and the correlation btw adjacent pixels.
cheers,
Réza

**Comment by JorisDeRidder** [comment]
Thanks, Bart, for taking the time to look at this. Meanwhile we can confirm that this indeed caused the bug. The corrected version plus an automated test of the BFE will soon be in the develop version. Dries, Carsten and I took the opportunity to review the order of _all_ effects in the entire PlatoSim chain, and made some adjustments.

**Comment by Dries-Seynaeve** [comment]
Hello, as Joris already said, Bart was right on the money with this issue. We have changed the order in which the effects are applied. I believe this should fix the problem. Let us know if this works.

**Comment by carstenpaproth** [comment]
Thanks for fixing this issue. I rerun my script and now the PTC shows the expected deviation from linearity.

[platosim_ptc.pdf](https://github.com/IvS-KULeuven/PlatoSim3/files/6242726/platosim_ptc.pdf)

**Comment by drsamadi** [comment]
Hi all,
it must be made clear in the documentation that the model implemented, 
Guyonnet et al, is only valid for a flat field or when the PSF is wide 
w.r.t the pixel size, which is not the case for PLATO.
For an alternative approach please see "Brighter Fatter Effect: impacts 
on mask-based light-curves and correction algorithm" 
(PLATO-LESIA-PDC-TN-0068, i1.0), document part of the Justification 
Package C:
https://issues.cosmos.esa.int/platowiki/display/PPDWS/Justification+documents

Réza

**Comment by JorisDeRidder** [comment]
Thanks, Réza, for bringing this to our attention!
