### ISSUE TITLE
PlatoSim 3.3 not compatible with gcc/g++ > 5

### ISSUE THREAD

**Issue by nicholasjannsen** [IvS-KULeuven/PlatoSim3#562]
For a Ubuntu 20.x user with following default compiler versions of gcc and g++ versin 9.x (by this writing 9.3.0) the HDF5 library doesn't seem o be compatible with these compiler version, since the first install script is calling the HDF5 library (`install_hdf5.py`) ends in errors. After some investigation the problem is "In the GCC 5.1 release libstdc++ introduced a new library ABI that includes new implementations of std::string and std::list." Hence, as mentioned in the [gcc (using dual ABI) documentation](https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html), in short this is a syntax change for gcc versions > 5.1. 

Ultimately, if the newest compiler versions are to be used, the workaround is to avoid using `std::string` (and similar) in the interface to the HDF5 library. However, for the c++ code used of PlatoSim3 we cannot escape the use of `catch`, `pop`, `push`, etc. (for more detail see this [problem](https://stackoverflow.com/questions/51431246/undefined-symbol-for-hdf5-when-using-g)).

Funny enough a related (opposite) error happens for the std:: construct is to avoid a gcc & libstdc++ bug with older gcc versions. Cf: issue #492 - see this [bug1](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=48891) and [bug2]( https://stackoverflow.com/questions/33770374/why-is-isnan-ambiguous-and-how-to-avoid-it).

**Comment by JorisDeRidder** [comment]
Thanks for looking into this. I can understand that ABI compatibility problems can occur when you mix linking with libc++ of LLVM vs libstdc++ of GNU. But in this case you're compiling/building HDF5 as well as PlatoSim from scratch using only the g++ compiler. Where exactly could the ABI incompatibility occur? For completeness, could you copy-paste the error message you got during the HDF5 install procedure?

**Comment by nicholasjannsen** [comment]
No agree to me it seems very strange that this happens when you build from scratch. So far I get the same errors with HDF5 unless I use a compiler version < 5. Here is where the first error occurs during the build:

    H5detect.c:1363:1: error: attributes should be specified before the declarator in a function definition
     1363 | static void
          | ^~~~~~
    In file included from H5private.h:27,
                     from H5detect.c:53:
    H5public.h:83:38: error: expected end of line before ‘push’
       83 |     #define H5_GCC_DIAG_DO_PRAGMA(x) _Pragma (#x)

I have sent you an email with the output text file with the error code.

**Comment by carstenpaproth** [comment]
I used the following workaround to get PLATOSim running on Ubuntu 20.04:
- install the hdf5 library directly from the Ubuntu repositories: sudo apt install libhdf5-dev
- add a line to include_directories in the CMakeLists.txt of PLATOSim: /usr/include/hdf5/serial
- add a line to link_directories in the CMakeLists.txt of PLATOSim: /usr/lib/x86_64-linux-gnu/hdf5/serial
- comment "#python ./dependencies/installscripts/install_hdf5.py" in install.sh
- run install.sh

**Comment by nicholasjannsen** [comment]
Thank you Carsten for your fix, that is also a good work-around. Although for a future version of PlatoSim I guess it would be preferable for the user to install with as little effort as possible, hence,  depending on the exact type of bug, your solution could indeed be a suggestive update of the linux installation for PlatoSim.

**Comment by JorisDeRidder** [comment]
Nich confirmed that the new HDF5 version fixed the issue for him on Ubuntu.
