### ISSUE TITLE
Installation fails with zmq.cpp missing.

### ISSUE THREAD

**Issue by mammler** [IvS-KULeuven/PlatoSim3#563]
PlatoSim v3.2.0-RC1-1436-g1bd4bd1

Installation following instructions with: make -j 4

This produces an error stating that zmq.cpp does not exist (error log below).

Mac OS 10.15.7

gcc (MacPorts gcc5 5.5.0_6) 5.5.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

cmake version 3.19.7
CMake suite maintained and supported by Kitware (kitware.com/cmake).

Error log:
[errors.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/6172777/errors.txt)

**Comment by JorisDeRidder** [comment]
Hi Matthias, could you verify if by any chance zeromq was already installed through MacPorts?

**Comment by mammler** [comment]
Hi Joris,
I do not think so. I checked with 'port installed' and it's not there.
Thanks,
Matthias

**Comment by JorisDeRidder** [comment]
Hi Matthias, could you try to reinstall zeromq using `python ./dependencies/installscripts/install_zeromq.py` in the main PlatoSim folder, and attach the error log?

**Comment by mammler** [comment]
Hi Joris,
thank you! This helped! zeromq installed without error. Then, PlatoSim installed as well. I do not know why zeromq was missing. I am pretty sure that I followed all steps of the installation instructions.
Best regards,
Matthias

**Comment by JorisDeRidder** [comment]
Good to hear that it is solved!
