### ISSUE TITLE
MappedFromFileSymmetrical and CCD diffusion

### ISSUE THREAD

**Issue by drsamadi** [IvS-KULeuven/PlatoSim3#564]
When I turn on/off charge diffusion with MappedFromFileSymmetrical, I do not see differences in the PSF returned in the output file (in PSF/rotatedPSF). 

However we would like to compare our inverted PSF with the CCD PSF, i.e. the optical PSF as it is changed by the charge diffusion inside the CCD. This way we can assess the quality of the PSF inversion. 

The same holds when we want to test the focus calibration algorithms: indeed the later consist in measuring the Ensquared Energy (EE-> the PSF energy within a square of  2.2 pixel large for instance) and we want to compare our measured EE values with the "true" values. However, since the optical PSF is smeared out by CCD charge diffusion so should change the EE. 

Accordingly, would it be possible to have in the output file the PSF after having applied the diffusion kernel to the optical PSF ? 

Réza

**Comment by JorisDeRidder** [comment]
Thanks for the report, we'll look into this.

**Comment by Dries-Seynaeve** [comment]
Hello, this is now implemented in the develop branch.

It is now possible for PlatoSim to record the PSF for a Symmetric or Asymmetric mapped PSF. This can be switched on/off though the input.yaml file using the ` WriteDiffusedPSF`  parameter. The diffused PSF can then be found in the output file PSF/diffusedPSF. Remarkt that this might take a while to caluclate (around 15min for me).
