### ISSUE TITLE
Noise value of a pixel does not change in a time series.

### ISSUE THREAD

**Issue by mammler** [IvS-KULeuven/PlatoSim3#580]
In order to simulate the noise levels from background subtraction, I'd like to run two simulations, one for the science image and one for the background image. Then, my plan was to subtract the images and check the noise of the residual, to confirm analytical calculations of the noise level. This did not work for the reasons explained below.

I'am using a modified version of plato-test-prep/ghosts.py: [ghosts.py.zip](https://github.com/IvS-KULeuven/PlatoSim3/files/6356078/ghosts.py.zip)

Findings in detail: I used different random seeds in the science and the background image so that the noise pattern would vary and give a realistic noise level in the residual. This did not work as the residual is zero in each pixel. I also compared background images with random seeds incremented by 1 and 10, resp. Pixel values are still the same. I confirmed in the .yaml files for the separate simulations/images that the new seed values have been written correctly before running the simulation.  I also tried with setting seeds to -1 so that the clock would be used. No change either.

Could you please help? Thank you very much!

PlatoSim version: v3.2.0-RC1-1436-g1bd4bd1

gcc (MacPorts gcc5 5.5.0_6) 5.5.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

cmake version 3.19.7
CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by Dries-Seynaeve** [comment]
Hello, in the included file all the noise effects are switched off (line 98-124). Is this also the case in your modified code? If not could you include the modified code you use?

**Comment by mammler** [comment]
Yes, sure, I should have seen that... Thank you for pointing me to this location! I activated some noise effects and it works.
Many thanks again!
