### ISSUE TITLE
Include a method that centers the subfield around a CCD pixel row

### ISSUE THREAD

**Issue by Dries-Seynaeve** [IvS-KULeuven/PlatoSim3#587]
This is a method that would mimic the behaviour of the existing method setSubfieldAroundPixelCoordinates() but only for an input row and the number of lines of the subfield. This would be useful to simulate partial readout where the subfield would consist out of a few hundred lines, but all the 4510 rows. 

Another difference with setSubfieldAroundPixelCoordinates() is that if it will not be possible to centre the subfield around the input row (because it is too close to the edge with respect to the number of lines of the subfield), the centre of the subfield will be shifted so that the subfield still falls onto the CCD with the correct number of lines.

**Comment by PierreRoyer** [comment]
setSubfieldAroundRow() or a an approaching name... To be exact the request is entire rows (4510 columns + pre/overscan), being nRows centered around 'row' (unless border effects kick in as described).

This feature is necessary to whoever wants to simulate representative datasets in view of the coming TVAC tests.

**Comment by Dries-Seynaeve** [comment]
This method is now added to the simulation.py file and is named `setSubfieldAroundPixelRow`. 
The method takes as input the ccdCode, ccdRow pixel and number of lines of the subfield.
