### ISSUE TITLE
There is no link to the notebooks or how to use them

### ISSUE THREAD

**Issue by pablogm1024** [IvS-KULeuven/PlatoSim3#59]
There is no link to the notebooks or how to use them. There is also no mention of Jupyter. It would be great if the documentation would include links to the notebooks so that user can follow the tutorials on their own.

**Comment by SaraRegibo** [comment]
Hi Pablo,
I've added a documentation page with some explanation about the notebook: [http://ivs-kuleuven.github.io/PlatoSim3/Tutorials.html](http://ivs-kuleuven.github.io/PlatoSim3/Tutorials.html).  Could you have a look, please?

**Comment by pablogm1024** [comment]
Looks fine for me.
