### ISSUE TITLE
Questions about Platosim outliers parameters

### ISSUE THREAD

**Issue by manugr788** [IvS-KULeuven/PlatoSim3#638]
Dear all,
In order to validate the on-board software the N-DPU  team (P. Plasson) will use PLATOSim to build a nominal and "worst case" simulations (and inject results into the on-board software to measure CPU performance and so on).

We asked René Heller about which parameters values should be put into the Platosim configuration file to simulate a outliers.
FIY, hereafter his answer,

Nevertheless, René has 2 remaining questions:
– I'm not sure **how PLATOSim' TrailLength parameter uses the lower and upper limit to generate cosmic particle trails.** Does PLATOSim assume a Gaussian distribution with the lower and upper limits referring to the standard deviation intervals?
– Also not sure about **PLATOSim's usage of the upper and lower values of the Intensity parameter**.

```
Nominal case

(1) At the beginning, it's good to keep in mind that for PLATO we may observe rates that are substantially different from those measured with Kepler. As Jenkins+ (2004, PDF attached) put it: "The actual flux experienced by a device depends a great deal on the exact orbit, that is, is the spacecraft in low Earth orbit (LEO), or is it in deep space?. In their Sect. 3.1, Jenkins+ (2004) give more details about the expected/simulated charge deposition into the Kepler CCDs, but I'm not sure to which extent this is directly applicable to PLATO because these simulations took into account the shielding properties and the orbit of Kepler.

(2) The Kepler Instrument Handbook (Caldwell & Van Cleve 2006)* says that C = 5 / s / cm² was assumed for Kepler based on earlier measurements from the SOHO mission. Note that SOHO's orbit was at L1, just like PLATO's will be: "SOHO's final operational orbit is a so-called Class II orbit, with an anticlockwise rotation (when looking at the Sun), at a distance of about 1.5 million kilometres from Earth. The period of this halo orbit around the L1 Lagrangian point is approximately 178 days." (esa.int/esapub/bulletin/bullet88/vande88.htm).

(3) The actual 6σ outlier rate from Kepler was a little bit higher than expected, namely C = 10 / s / cm² (Kepler Instrument Handbook, Caldwell & Van Cleve 2006, Sect. 4.16). See also their Fig. 31, which shows an interesting charge-per-pixel histogram.

In conclusion, the value from SOHO (C = 5 / s / cm²) might be more comparable to PLATO than the C value from Kepler (C = 10 / s / cm²) from a space environment point of view. That said, the two spacecraft were very different in terms of their specific instrument design incl. shielding, orientation etc. and the difference in C might not only reflect differences in their exposure to cosmics. Moreover, the methods used to measure cosmics are not the same, so there is another unknown systematic effect. So I'd say C = 10 / s / cm² is more towards the higher end of what we should use as a nominal case but still plausible and absolutely realistic.

Worst case
This one is harder to characterize. I found some helpful information in the attached PLATO Environmental Specification document (ESA-PLATO-ESTEC-MIS-SP-001.pdf). In their Fig. 4-6, the dark blue line shows the background galactic cosmic ray activity histogram (the quiet case). The other lines show the solar activity under various elevated activity levels. These histograms are all about a factor of 100 higher than the quiet scenario. This is why in my previous simulations, I used C = 1000 / s / cm² as a worst case (100 times the nominal case), which "might occur occasionally or under unforeseen circumstances (e.g. enhanced solar activity)" (PLATO-MPSSR-PDC-TN-0001, Issue: 2.5.4).

Intensity

The Kepler Data Processing Handbook (KSCI-19081-002, Fig. 6.3 therein)** shows a Poisson-like distribution with a peak at a few times 1000 electrons (as deposited charge) with a trail reaching out to about 10 000.

Trail length

The Kepler Instrument Handbook (Caldwell & Van Cleve 2006, Sect. 4.16, Figure 32) says: "A cosmic ray typically deposits charge in about 4 pixels, depending on its angle of incidence on the CCD." Kepler's pixel size is (27 µm)² (online reference), which means the nominal trail length for Kepler was 108 µm. PLATO's pixel edge length will be 18 µm, which translates into a nominal trail length of 108 µm / (18 µm) = 6.

– I'm not sure how PLATOSim' TrailLength parameter uses the lower and upper limit to generate cosmic particle trails. Does PLATOSim assume a Gaussian distribution with the lower and upper limits referring to the standard deviation intervals?
– Also not sure about PLATOSim's usage of the upper and lower values of the Intensity parameter.

So subject to my understanding of PLATOSim's definition/usage of the input parameters, I'd summarize my discussion in the following:

#Nominal case
CosmicHitRate: 10
TrailLength: [3, 9]
Intensity: [2000, 10000] ?

#Worst case
CosmicHitRate: 1000
TrailLength: [3, 12]
Intensity: [1000, 10000] ?
```

**Comment by JorisDeRidder** [comment]
Hi Emmanuel & René, 
Currently PlatoSim draws both the intensity as well as the trail length of the cosmics from a uniform distribution, where the interval boundaries are given in the input yaml file.

**Comment by reneheller** [comment]
Hi Joris, Emmanuel!

I've done a little research into the intensity distribution of the outliers. Panel (a) below, which is Figure 6-3 from the Kepler Data Processing Handbook (KSCI-19081-002), shows the estimated cosmic ray noise for Kepler (predicted prior to launch). Panel (b) shows a histogram of 6σ outliers from Kepler.  Obviously, these distributions are not flat but they look more like skewed normal distributions.

![KSCI-19081-002 Fig6-3](https://user-images.githubusercontent.com/7735050/137153647-0557c31d-0f8d-43da-b6b6-afbee0fe8b5b.jpg)

I played a bit with skewed distributions today in trying to find a more realistic mathematical model for the expected intensity distribution. I used the following parameterizations (described [here](https://en.wikipedia.org/wiki/Skew_normal_distribution) in more detail) in gnuplot:

```
phi(x) = 1. / sqrt(2*pi) * exp(-x**2 / 2.)
psi(x) = 0.5*(1+erf(x/sqrt(2)))
f(alpha,omega,xi,x) = 2. / omega * phi((x-xi)/omega) * psi(alpha*(x-xi)/omega)
```
where `f(alpha,omega,xi,x)` is the skewed normal distribution. Note that for `alpha=0` the function collapses to a normal distribution and then `omega` becomes the well-known standard deviation.

The next two plots show a flat, normal, and skewed normal distribution for the e- intensity probability density (left: linear x axis; right: logarithmic x axis). I've chosen the parameterization to ensure the area under each curve is 1. And the parameterization of `f(alpha,omega,xi,x) = f(30,2000,2500,x)` is chosen to roughly reproduce the histogram from Kepler.

![outliers](https://user-images.githubusercontent.com/7735050/137156414-df5cf877-4ee9-40a7-b718-27fa262f1f75.jpg)

Details of the 'most realistic' parameterization aside, do you think it would be possible, Joris, to implement such a skewed normal distribution for the outlier intensity histogram?

PS: The gnuplot script that I used is [here](https://github.com/IvS-KULeuven/PlatoSim3/files/7339171/outliers_Rene.txt). Just rename it to 'outliers.gp' and then run `call "outliers.gp" pdf` from inside your gnuplot environment.

**Comment by JorisDeRidder** [comment]
Hi René, thanks, we'll look into this!

**Comment by JorisDeRidder** [comment]
Hi @reneheller, in the develop branch I implemented the skew-normal distribution for the cosmics intensity. In the inputfile.yaml you will need to specify in Sky/Cosmics/Intensity 3 numbers which are the location (xi), the scale (omega) and the shape (alpha). The default values are the ones you mentioned above for Kepler. Let me know if you're OK with this.

**Comment by reneheller** [comment]
Hi Joris! This really is a nice update for PLATOSim! I've had a look at the new [input.yaml](https://github.com/IvS-KULeuven/PlatoSim3/blob/develop/inputfiles/inputfile.yaml) file and it looks all good to me. Do you want me to look at any other file, e.g. the one in which you implemented the distribution of the cosmics?

**Comment by JorisDeRidder** [comment]
Not particularly no. Would it be useful for you if the (total) intensities of the cosmics would be saved to the HDF5 file?

**Comment by reneheller** [comment]
It would be helpful if for each cosmic the intensity could be stored, if this is what you mean? Then we could examine in detail which of the cosmics can still be detected with our algorithms and it could help us to adapt the detection thresholds.

**Comment by JorisDeRidder** [comment]
Hi René, in the develop branch the entry rows, the entry columns, the entry angle, the total intensity and the trail lengths for all cosmics are now stored in the HDF5 file. If you use Python (i.e. simfile.py) to extract information from the HDF5 file, then you can use the function getCosmicsInfo(). For example:
```
>>> file = SimFile("Simul01.hdf5")
>>> imageNr = 4
>>> entryRows, entryColumns, entryAngles, intensities, trailLengths = file.getCosmicsInfo(imageNr, "SubField")
```  

Note that to avoid potential confusion I had to change the name of an older Python function in simfile.py: getCosmicsCoordinates() has now been renamed to getCosmicsAffectedPixels(). The latter function still gives all the rows and columns that have been affected by a cosmic. 

Could you try out the new functionality?

**Comment by reneheller** [comment]
Hi Joris! I've downloaded PLATOSim from the develop branch as per
```
conda install -c https://jenkins.miricle.org/platosim.devel/ platosim
conda update --force-reinstall -c  https://jenkins.miricle.org/platosim.devel/ platosim
```
and then found the new PLATOSim version at ```/opt/miniconda3/bin/platosim``` on my MacBook. The new yaml input file is at ```/opt/miniconda3/inputfiles/inputfile.yaml```. When I ran PLATOSim using

```
fin=/opt/miniconda3/inputfiles/inputfile.yaml
fout=/Users/heller/Astronomy/programming/PLATOSim_data/outputfiles/outputfile_develop.hdf5
flog=/Users/heller/Astronomy/programming/PLATOSim_data/outputfiles/logfile_develop.txt
/opt/miniconda3/bin/platosim $fin $fout $flog
```

I got the error message

```
2021-10-20 13:49:22 ERROR   Sky: Cannot open orbit file /opt/miniconda3/envs/platosim//inputfiles/orbit.txt
```

Obviously PLATOsim was still using files from the directory ```/opt/miniconda3/envs/platosim//inputfiles``` although my input file was defined at ```/opt/miniconda3/inputfiles/```. Anyways, I changed all the paths in the inputfile.yaml manually (e.g. ```inputfiles/orbit.txt``` to ```/opt/miniconda3/inputfiles/orbit.txt```) and then it worked.

Then I downloaded the latest simfile.py from the develop branch at ```https://github.com/IvS-KULeuven/PlatoSim3/blob/develop/python/platosim/simfile.py```, opened my iPython environment, and did as per your suggestions:

```
>cd /opt/miniconda3/python/platosim
>from simfile import *
>file = SimFile("/Users/heller/Astronomy/programming/PLATOSim_data/outputfiles/outputfile_develop.hdf5")
>imageNr = 4
>entryRows, entryColumns, entryAngles, intensities, trailLengths = file.getCosmicsInfo(imageNr, "SubField")
```

and received the error message

```
KeyError                                  Traceback (most recent call last)
<ipython-input-13-613e7e49bf54> in <module>
----> 1 entryRows, entryColumns, entryAngles, intensities, trailLengths = file.getCosmicsInfo(imageNr, "SubField")

/opt/miniconda3/python/platosim/simfile.py in getCosmicsInfo(self, imageNr, field)
    819         # Extract the arrays from the HDF5 file
    820 
--> 821         dataset = self.hdf5file["Cosmics"][field][exposureGroupName]["EntryRows"]
    822         entryRows = np.zeros(dataset.shape, dataset.dtype)
    823         dataset.read_direct(entryRows)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

/usr/local/lib/python3.8/site-packages/h5py/_hl/group.py in __getitem__(self, name)
    262                 raise ValueError("Invalid HDF5 object reference")
    263         else:
--> 264             oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
    265 
    266         otype = h5i.get_type(oid)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5o.pyx in h5py.h5o.open()

KeyError: "Unable to open object (object 'EntryRows' doesn't exist)"
```

Here is where I couldn't move on. So I decided to check in the develop branch if there is any HDF5 file that I could download and try the simfile.py script on this one, but there doesn't seem to be any. Can you help?

**Comment by JorisDeRidder** [comment]
Hi @reneheller , sorry for the bad experience. Your extensive report is very helpful for us to make the installation procedure more user-friendly and more plug-and-play. I suspect that the environment variable `PLATO_PROJECT_HOME` on your system was not set correctly, hence the trouble. Could you please email your input yaml file to me?

**Comment by nicholasjannsen** [comment]
Confirmed through multiple simulations so far since 2021, this feature is implemented successfully. Thanks a lot for the description @reneheller. If you still experience installation problems feel free to open a new issue with the appropriate tag.
