### ISSUE TITLE
CTI: inhomogenous trap density

### ISSUE THREAD

**Issue by drsamadi** [IvS-KULeuven/PlatoSim3#639]
Hi,
unless I'm wrong, currently when CTI is activated, the user can only consider a constant value for the trap density across the CCD.
After a while, the parallel over-scan pixels will be affected by CTI. As explained in PLATO-LESIA-PDC-TN-0030, i0.2, in order to measure correctly the smearing on-board it will be necessary at some time to correct the parallel over-scan pixels  for the impact of the CTI.
The algorithm to correct (on-board) for its impact is described in the justification document  PLATO-LESIA-PDC-TN-0030 as well as in the ATBD PLATO-LESIA-PDC-DD-006 (i2.3). I attach also the presentation I gave during the CCD-WG 23.

The on-board correction of the CTI relies on a model which introduces a couple of free parameters, which will be obtained by calibration using the Extended Pixel Edge Response method and the partial read out images (the latter will be acquired during the calibration phase, at the beginning of each quarter).
As shown in the presentation here attached, I have started to work on the calibration algorithm using PIS, which allows the use as input of a map that describes how the trap density varies across the CCD (see  here attached an example of such trap density map). On the other hand PIS is not able to generate partial read-out image.

In order to develop further this algorithm and to write the corresponding ATBD using  platosim, an equivalent feature needs to be implemented in platosim: in other words  the generatation of the CTI effect needs to take into account that the trap density is going to vary across the CCD (because the exposure of the focal plane to radiation will be inhomogeneous).

CCD-WG 23:
[Samadi_indirect_CTI_calibration.pdf](https://github.com/IvS-KULeuven/PlatoSim3/files/7336689/Samadi_indirect_CTI_calibration.pdf)

A trap density map:

![Screenshot from 2021-10-13 11-25-55](https://user-images.githubusercontent.com/19569211/137106286-4642ecb0-57a1-46b7-a31b-c06f79d1589e.png)

Réza

**Comment by Dries-Seynaeve** [comment]
Hello Réza

Thank you, I will look into this. 

Kind regards 
Dries

**Comment by JorisDeRidder** [comment]
Hi Réza, what would be the most convenient way to specify such a spatially varying trap density map? Through an HDF5 file? Do you foresee a variation in time as well in the future?

**Comment by drsamadi** [comment]
Hi Joris
yes as for the other inputs I think that this would be convenient to use an HDF5 file although for the moment in PIS I'm using a simple numpy binary file (.npy), which I have generated myself from two text files that were given to me by Anko. 
These text files actually describe the level of radiation as a function of  the camera fov angular directions (a grid of  801x801 angles wit a step of 0.05°).
I have projected this grid to the focal plane and then transformed focal plane position to CCD. I then get the level of radiation for each CCD pixel. 
Then at the level PIS, the user has to specify the level of mean radiation he want (for instance the level expected at the end of life: 6.5e9 p+/cm^2). 
Then PIS rescales the radiation map such that for the CCD column passing by the middle of the imagette , the mean level of the radiation map matches the value requested by the user.
This way I can rescale the radiation to a given level (for instance the level expected at the end of life).
Once the radiation map rescaled this way, PIS assumes that the trap density scale as a function of the radiation level, and the density of each trap species are rescaled by the radiation map to matches the trap density one expect at EOL for the reference radiation level at EOL (6.5e9 p+/cm^2). 

However,  there is perhaps another smart way to proceed and I'm not sure to explain well my procedure!
In any case I can share my little python program that interpolates Anko's and generate the radiation map (one value for each CCD pixel).
From here you can decide to scale the trap density from the radiation map the way you think this is the more relevant.

Réza

**Comment by drsamadi** [comment]
here attached the material associated with my explanations below
[CTI-map-generation.zip](https://github.com/IvS-KULeuven/PlatoSim3/files/7353954/CTI-map-generation.zip)

**Comment by drsamadi** [comment]
other remarks:
* Anko provided me two radiation maps (origin OHB): one for a camera near the edge and the other in the middle of the bench.  
* here I assume that the cumulated number of proton received at a given time scales as the radiation map (which I think corresponds to the instantaneous exposition of the camera to radiation - but I've to check this with Anko) 
*  I further assume that the number of traps we have at a given instance in turns scale as the cumulated number of protons received at these instant.
Therefore concerning your question about the time variation, I think you may want to proceed as you already do with platosim: i.e. to assume that the trap density (and hence the  cumulated number of protons) increases lineary with the time  (but perhaps I'm wrong about the way platosim handle the variation of the CTI with time).
In fact I think the problem is   that when the satellite will be rotated  each 3 month ,  the  instantaneous radiation map will obviously turns also by 90 degrees, and this will change the cumulated trap density map. However so far I have not introduced this complexity in PIS.

**Comment by drsamadi** [comment]
Hi Joris,
 just to correct a mistake: the two files provided by Anko are binary files (not text files). The two asciii files were provided by OHB.  Anko applied a conversion from the x-/y- FPA coordinate system to an angular coordinate system including distortion and generated the two following binary files:
 * rad_edge_template_N_EOL_801_ab.float
 * rad_mid_template_N_EOL_801_ab.float
I then converted these files into numy files:
rad_edge_template_N_EOL_801_ab.npy
rad_mid_template_N_EOL_801_ab.npy
however, unfortunately I have not recorded the python procedure to read the .float files.

Réza

**Comment by JorisDeRidder** [comment]
Hi Réza, thanks for all the info. Can the same radiation map be used for all trap species?

**Comment by drsamadi** [comment]
Hi Joris,
to my understanding this is a reasonable approximation (TBC by CCD experts): as soon as the energy distribution of the charged particles does not  change much during the time, it is then reasonable to assume that each trap spicy will have its density linearly increasing with the cumulated amount of radiation collected during the missing life time. Of course, sudden and intense solar irruption breaks the hypothesis that the trap density will increase with time.

**Comment by Dries-Seynaeve** [comment]
Hello Réza, 

This feature is now added to the develop version of PlatoSim. It is possible to specify in the input file `CCD/CTI/Model` as `Short2013FromFile` and to specify the CTI file in `CCD/CTI/Short2013FromFile/CTIFileName`. 

We also added  a python method in `python/platosim/CTImap.py` called `createCTIinputFile` to create an CTI input file. This method takes as input the parameters for the Short2013 model, a 4510 x 4510 numpy array as a radiation map, and the path to where the hdf5 file should be saved. 

Kind regards 
Dries

**Comment by JorisDeRidder** [comment]
One important difference with the PIS implementation, is that PlatoSim rescales the radiation map to a trap density map so that mean of the entire CCD (not just the mean of the imagette) is the user-given trapdensity. The reason for this is to avoid inconsistencies in CTI when simulations are made for a large number of stars of which the imagettes may share the same column coordinates.

**Comment by drsamadi** [comment]
Hi 
I do no see the parameter CCD/CTI/Short2013FromFile/CTIFileName in the input file ?
I'm' using  PlatoSim 3.5.3-19-g18d87597
compiled from the version in the develop branch

thanks
Réza

**Comment by Dries-Seynaeve** [comment]
Hi Réza, 

Do you mean that is not in the input file that is generated when running platosim from python? 

Kind regards 
Dries

**Comment by drsamadi** [comment]
Hi Dries,
I mean that I do not see this parameter in the YAML file named inputfiles.yaml stored in the folder 'inputfiles'

**Comment by drsamadi** [comment]
oups very sorry I see the parameter  !

**Comment by drsamadi** [comment]
do you have a file "ctiInput.hdf5" already generated ?  I do not see such file available in the folder 'inputfiles'

**Comment by Dries-Seynaeve** [comment]
No, this is not included in the PlatoSim input files. 

However, there is a function in python/platosim/CTImap.py where it is possible to create such a file. You need as parameters the usual parameters for the Short2013 model and a radiation Map that has the average amount of protons per second that fall on the CCD as input. This function should then generate a hdf5 file that can be used.

**Comment by drsamadi** [comment]
OK thanks ! 
I'm going to use it
