### ISSUE TITLE
Jitter file used in tutorials is not available

### ISSUE THREAD

**Issue by pablogm1024** [IvS-KULeuven/PlatoSim3#64]
Several of the tutorials refer to a jitter file called PlatoJitter_Airbus.txt, which is not available in the repository, making the tutorials unusable. Please add the file to the repository or, if the file cannot be distributed, use a simplified version instead that can be distributed, so that the tutorials run.

**Comment by JorisDeRidder** [comment]
You can find the jitter file on ftp://ftp.ster.kuleuven.be/dist/joris/plato/platosim  (login as guest).
