### ISSUE TITLE
MappedFromFile PSF simulation

### ISSUE THREAD

**Issue by manugr788** [IvS-KULeuven/PlatoSim3#640]
Dear,
I am a little bit confused with the result of the simulation when I enable MappedFromFile model for PSF.
See enclosed the result of two simulations, one with AnalyticNonGaussian and the other one with MappedFromFile.
PSF model is the only parameter which has been changed between this 2 simulation (yaml file included).
I know that MappedFromFile now includes distortion but the position of all stars in the resulting image seems to be very weird
Maybe I miss something with MappedFromFile PSF model ?
Platosim : 3.5.0-44-g3fc70bdb

**AnalyticNonGaussian:** 
![AnalyticNonGaussian](https://user-images.githubusercontent.com/12544881/137325319-f642053d-b93e-4972-86a5-742f45c8057c.PNG)
**MappedFromFile:**
![MappedFromFile](https://user-images.githubusercontent.com/12544881/137325326-0ea4d74b-796b-4abe-8069-abd398bd365b.PNG)
[0000032165.yaml.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/7346287/0000032165.yaml.txt)

**Comment by Dries-Seynaeve** [comment]
Hello 

Thank you for bringing this to our attention. I will look into what the problem could be. 
Could you also share the star catalog file that you used? 

Kind regards 
Dries

**Comment by manugr788** [comment]
I used the one in 
PlatoSim3/inputfiles
[starcatalog.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/7346585/starcatalog.txt)

**Comment by manugr788** [comment]
And I used PSF_Focus_0mu.hdf5 from ftp.ster.kuleuven.be

**Comment by Dries-Seynaeve** [comment]
Hello 

The problem was that the previously mapped distortion approximation was too inaccurate. I have implemented a more continuous interpolation (in the develop version) of the distortion for the mapped distortion. Let me know if this helps. 

Kind regards 
Dries

**Comment by manugr788** [comment]
ok, I will test this asap.
Thanks

**Comment by manugr788** [comment]
Issue fixed
Thank you very much.
Platosim : 3.5.0-73

**MappedFromFile PSF:**
![mappedPSF](https://user-images.githubusercontent.com/12544881/138488158-7f7eca49-c0c0-44df-a32d-337f51145d0a.PNG)
