### ISSUE TITLE
compilation issue with libfftw3f

### ISSUE THREAD

**Issue by drsamadi** [IvS-KULeuven/PlatoSim3#645]
Hi 
I've a new compilation issue, whih I don't know how to solve. Any idea ? 

/usr/bin/ld: /home/reza/plato/PlatoSim3/dependencies/Installs/fftw-3.3.4/lib/libfftw3f.a(direct.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: /home/reza/plato/PlatoSim3/dependencies/Installs/fftw-3.3.4/lib/libfftw3f.a(ct-hc2c-direct.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: /home/reza/plato/PlatoSim3/dependencies/Installs/fftw-3.3.4/lib/libfftw3f.a(ct-hc2c.o): relocation R_X86_64_32S against `.text' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: /home/reza/plato/PlatoSim3/dependencies/Installs/fftw-3.3.4/lib/libfftw3f.a(direct-r2c.o): relocation R_X86_64_32 against `.text' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: /home/reza/plato/PlatoSim3/dependencies/Installs/fftw-3.3.4/lib/libfftw3f.a(direct-r2r.o): relocation R_X86_64_32 against `.text' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: /home/reza/plato/PlatoSim3/dependencies/Installs/fftw-3.3.4/lib/libfftw3f.a(direct2.o): relocation R_X86_64_32 against `.text' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: /home/reza/plato/PlatoSim3/dependencies/Installs/fftw-3.3.4/lib/libfftw3f.a(hc2hc-direct.o): relocation R_X86_64_32 against `.text' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: /home/reza/plato/PlatoSim3/dependencies/Installs/fftw-3.3.4/lib/libfftw3f.a(ct.o): relocation R_X86_64_32 against `.text' can not be used when making a PIE object; recompile with -fPIE
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/platosim.dir/build.make:85: platosim] Error 1
make[1]: *** [CMakeFiles/Makefile2:136: CMakeFiles/platosim.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
At global scope:

**Comment by Dries-Seynaeve** [comment]
Hello 

Could you tell me which C++ compiler you are using? Maybe this could be the problem 

Kind regards 
Dries

**Comment by drsamadi** [comment]
Hi Dries,
I'm using g++ under linux/ubuntu:

g++ -v
Using built-in specs.
COLLECT_GCC=/home/reza/seism/mesa/mesasdk/bin/g++.exec
COLLECT_LTO_WRAPPER=/home/reza/seism/mesa/mesasdk/bin/../libexec/gcc/x86_64-pc-linux-gnu/8.3.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /root/sdk2/build/gcc/configure CC= --build=x86_64-pc-linux-gnu --prefix=/root/mesasdk --with-gmp=/root/mesasdk --with-mpfr=/root/mesasdk --with-mpc=/root/mesasdk --enable-languages=c,c++,fortran --disable-multilib --disable-nls --disable-libsanitizer --enable-clocale=generic
Thread model: posix
gcc version 8.3.0 (GCC)

**Comment by Dries-Seynaeve** [comment]
Hello Reza, 

Maybe this could be a solution: 

Could you try to add `-fPIC` to the `CMAKE_CXX_FLAGS` in the `CMakeList.txt` file? 

This should be at line 161 in the `CMakeList.txt`, and the line should become 
`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O3 -Wall -Wno-deprecated-register -Wno-unused-variable -Wno-return-type -fPIC")`

After that, save the file and go to the build directory and run `cmake ..` to generate a new makefile, then compile again.

**Comment by drsamadi** [comment]
I get the following error. May by I should re-compile all the associated libraries by running install.sh ?

 95%] Linking CXX executable testplatosim
/usr/bin/ld: /home/reza/plato/PlatoSim3/dependencies/Installs/googletest/lib/libgtest.a(gtest-all.cc.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIE
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/testplatosim.dir/build.make:85: testplatosim] Error 1
make[1]: *** [CMakeFiles/Makefile2:109: CMakeFiles/testplatosim.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by drsamadi** [comment]
could my problem comes from the fact that i my setup the GCC/G++ compiler is linked to the one installed by the MESA code:
/home/reza/seism/mesa/mesasdk/bin/gcc

**Comment by JorisDeRidder** [comment]
That is probably indeed the case. I suspect that in your .bashrc or .zshrc your gcc compiler path is pointing to the MESA one. Could you (temporarily) let it point to your Linux system one, remove everything in dependencies/Installs/, and run install.sh again?

**Comment by drsamadi** [comment]
Indeed, this was at the origin of my problem. For the time being I have commented in my .bah_profile  the MESA setup. 
I have returned to the original CMakeList.txt file
The compilation succeeds and platosim works perfectly !
 Sorry  for having bother you.
