### ISSUE TITLE
Non-radial distortion model

### ISSUE THREAD

**Issue by drsamadi** [IvS-KULeuven/PlatoSim3#652]
Hi,
unless I'm wrong, when an AnalyticalNonGaussianPSF is used,  Platosim only considers a radial distortion formula.
However as shown in PLATO-DLR-PL-TN-0016 and in PLATO-UOL-PDC-TN-0003, the distortion cannot be accurately characterised with a radial  distortion formula.
This is the reason a non-radial distortion model has been adopted in PLATO-UOL-PDC-TN-0003 ; the latter is used on-board by the N-DPU (see PLATO-UOL-PDC-DD-0002 ATBD) to compute the target position and infer its associated window. The same will be used on-ground to determine the star position (this is much more accurate that the Center Of Brightness measurements).
Among the various non-radial distortion models  investigated in  PLATO-DLR-PL-TN-0016 and in PLATO-UOL-PDC-TN-0003,  the Wang et al (2008, Pattern Recognition, 41,  607 ) has been adopted for implementation in the N-DPU S/W as well as in the L1 pipeline.
Would it possible to implement such model into Platosim ? 
Below are representatives values  for the  Wang et al  model.

Réza

Direct distortion coefficients:
k1 = 0.32419  (0.000909221)
k2 = 0.0232909 (0.01546)
k3 = 0.407979 (0.0813934)
q1 = 0.00022463  (9.65277e-05)
q2 =  0.000217599 (9.66289e-05)
p1 = 0.000381958 (0.000477361)
p2 =  0.000963902 (0.000477882)

Inverse distortion coefficients:
k1 =  -0.323487 (0.00079334)
k2 = 0.268344 (0.0129341)
k3 = -0.435473 ( 0.0638285)
q1 =  -0.00019304 (1.52229e-05)
q2 =  -0.000176961 (1.51666e-05)
p1 = -0.000321713  (1.56086e-05)
p2 = -0.000827654 (1.55612e-05)

Values in parenthesis correspond to the formal 1-sigma uncertainty.

**Comment by Dries-Seynaeve** [comment]
Hello Réza

I have implemented this in the develop branch. Let me know if this works. 

Kind regards 
Dries

**Comment by drsamadi** [comment]
Hi Dries,
ok thanks !
I will test this when doing my new simulations.
Réza
