### ISSUE TITLE
AnalyticNonGaussian and centroid shift

### ISSUE THREAD

**Issue by drsamadi** [IvS-KULeuven/PlatoSim3#657]
Hi,
we are running full CCD images using AnalyticNonGaussian PSFs (file apsf_N6000K_v2.txt) .
For a sample of bright stars (P=8 to 9.), we compute their Center Of Brightness (COB) and compare them with the CCD positions given in the output HDF5 (the quantities named 'colpix' and 'rowpix' ). 
We get such histogram: 

![Screenshot from 2021-12-06 09-55-22](https://user-images.githubusercontent.com/19569211/145722169-9d8ee380-7999-4bec-baf3-bb9a494c81ad.png)

I'm potting here the difference btw the COB and the position given in the output HDF5 (red is for one axis, and the black for the second axis).

In this simulation we have turned-off the flatfield (PRNU), the BFE and the CTI. 

As can bee seen the errors are not centred around zero, we see two to three points of accumulation ;  this could perhaps  suggest that there is some rounding errors when placing the stars at the positions they should be (when projecting their sky positions into the focal plane and then into the CCD frame).

Réza

**Comment by denisGrBach** [comment]
Hi Réza,

the COBs of the non-Gausian PSFs are shifted due to optical abberation. This can be improved by doing a geometric calibration. I'm not sure about the two peaks though. Is this from just one CCD? In which RF do you evaluate the error?

**Comment by drsamadi** [comment]
Hi Denis
in the CCD frame. The plot shows the results for the 4 CCDs. 
I did the same comparison when using MappeFromFile PSFs (using the latest PSFs computed by Martin and downloaded the Platosim web site, file named PSF_Focus_0mu.hdf5).

I get the following histogram:
![Screenshot from 2021-12-13 08-35-33](https://user-images.githubusercontent.com/19569211/145771046-8dcefb09-b0eb-4ff0-84a6-3d27fcaa022d.png)
The histogram is not centered around zero, I guess because of the chromatic aberration, however the histogram has a nice 'bell' shape and does not show points of accumulation.

However note that in the first figure the COB were calculated using the “Gaussian Analytic Centroiding method" (Wang et al, 2015), which was shown by Elena to be more accurate than the classical COB. 

I'm going to applying this method to the full images generated with the MappeFromFile PSFs.

However, the following histogram shows the shifts I get when applying the  classical COB on the full images generated with the AnalyticNonGaussian PSFs (file named apsf_N6000K_v2.txt) .

![Screenshot from 2021-12-13 08-42-12](https://user-images.githubusercontent.com/19569211/145771974-98507583-23cd-4bd8-98a2-be55e7d4ee62.png)

We do see two  points of accumulation, although they are less  detached to each other compared to the first histogram  obtained with “Gaussian Analytic Centroiding method" .

Réza

**Comment by denisGrBach** [comment]
I'm only using the mapped PSFs and basically get the same as you. The COB method usually behaves differently in terms of noise but similar for bias. Maybe the analytic PSFs are not rotated properly. Do you get the same if you just plot one CCD?

**Comment by drsamadi** [comment]
yes you are perfectly right, the points of accumulation depends on the CCD ID as this is shown here:
CCD1 and 2 overlap: red and  blue
CCD3 and 4 overlap: green and magenta

![Screenshot from 2021-12-13 09-33-37](https://user-images.githubusercontent.com/19569211/145778375-7f52d316-3573-4363-a893-7d680ece09ef.png)

and yes this is very likely an issue related to the PSF rotation.

Réza

**Comment by carstenpaproth** [comment]
Indeed, the centroid seems to be not transformed correctly for the CCD rotation. I try to correct this in the analytic PSF code and push it to PLATOSim.
@drsamadi Do you have a script which can simply reproduce your 2 peak?

**Comment by drsamadi** [comment]
Hi Carsten, 
thanks for your reply.
for the classical COB , I use the classical definition of the barycenter. The file here attached contains the corresponding python code. Note that the COB is computed on a window of 7x7 centred around the  star and all pixels in the window are used.

My python implementation of the “Gaussian Analytic Centroiding method" (Wang et al, 2015) is in the file attached.

Note that applying the  “Gaussian Analytic Centroiding method" (GAC) on the full images generated using MappeFromFile PSFs also reveal the presence of points of accumulation, as this is shown in the figure below. 

![Screenshot from 2021-12-14 15-20-03](https://user-images.githubusercontent.com/19569211/146016416-286dbae0-7194-4093-b43c-690d4206e5b1.png)

The GAC method applied on imagettes simulated with PIS does not show such features (points of accumulation) as this is shown in this figure:
 
![Screenshot from 2021-12-14 16-14-45](https://user-images.githubusercontent.com/19569211/146026058-c92f2ae4-c14d-459e-9fa9-56547063236a.png)

Could you test the GAC method on image/imagettes generated with your own  simulator ? 
I would like to be sure that the features obtained with  the PLATOSim images are not  artefacts of the GAC method  or of my implementation .  

[centroid_methods.py.TXT](https://github.com/IvS-KULeuven/PlatoSim3/files/7712543/centroid_methods.py.TXT)

**Comment by drsamadi** [comment]
I have plotted the histogram above (obtained with the full images generated with PLATOSim using mapped PSFs)  by  differentiating the CCD:

![Screenshot from 2021-12-14 16-25-19](https://user-images.githubusercontent.com/19569211/146027805-931a78c5-4d6e-4ac9-a6d4-f0c3c015470f.png)

As for the AnalyticNonGaussian PSFs, we see that the points of accumulation are related to the  CCDs. Could this not be simply  explained by the chromatic aberration ? In the focal plane I guess the chromatic aberration increases with the distance from the center and is oriented in the radial direction. However, because of the different orientation of the CCD, the direction of  chromatic aberration change form one CCD to another.

**Comment by denisGrBach** [comment]
Maybe a few additions: 

- when using the 'psfallv3.txt' non-Gaussian (nominal case) with PlatoSim V3.4.1. it looks fine for me. All centroids are shiftet (radial-symmetric) by about 0.05 px per axis. 
- the latest analytic non-Gaussian (apsf_N6000K_v2.txt) is a worst case scenario, thus the centroid shifts (~0.1 px) are less systematic.
- a way to check the implementation would be to do parallel tests with 'apsf_N6000K_v2' and the corresponding mapped PSFs

**Comment by carstenpaproth** [comment]
Hi Réza,
I tried to reproduce your results with my simple analytic PSF simulator and I don't get two points of accumulation. The differences between the centroids and the input star positions are all over the place, but on average there is a bias of about 0.1 pixel in x and y.

![grafik](https://user-images.githubusercontent.com/26323228/146164928-c19db9af-67b9-4f9e-a948-1d50aa9547dd.png)

I think your plots show just this bias. Due to the CCD rotation in PLATOSim the centroid bias is visible on different axis and directions for different CCDs in the corresponding CCD coordinate systems. And as the bias is about the same for x and y, you get only two peaks in your plots.

**Comment by drsamadi** [comment]
Hi Casten
your plot is for only one CCD ? or your are plotting the centroid difference in the focal frame ?
How did you compute the centroid ? using the classical 'COB' or the  GAC method?

Nevertheless I have the impression  we converge toward the same explanation:  if I would have plotted the centroid difference  in the focal frame I would have a single point of accumulation corresponding to the bias of  0.1 pixel your are talking about.
This is no longer the same when we look at the centroid difference in the CCD frame.
Because in the CCD frame, the centroid shift induced by the chromatic aberration does not go toward the same direction.

Do we agree ?

Réza

**Comment by carstenpaproth** [comment]
Hi Réza,
I agree with your explanation.
My plot shows the centroid differences in the focal frame. I used a Gaussian fit to get the centroid.
Cheers,
Carsten

**Comment by drsamadi** [comment]
Ok thanks Casten for your fast reply ! 

Would it be possible for you to  apply on your own simulated image/imagettes, the two centroid calculation  methods (COB and GAC) ? 
This  would indeed  be interesting for us to (double) check the performance of the GAC method (see justification document JP-A: PLATO-UOL-PDC-TN-0002, i4.0).

Since we have converged on the explanation I think that this is a non-issue therefore I close it.
