### ISSUE TITLE
Strange full CCD image

### ISSUE THREAD

**Issue by drsamadi** [IvS-KULeuven/PlatoSim3#658]
Hi,
when using a MappedFromFile PSF file corresponding to defocused PSF (file named PSF_Focus_80mu.hdf5), I get this strange full CCD image.
![Screenshot from 2021-12-13 09-00-44](https://user-images.githubusercontent.com/19569211/145774286-5fc00ba8-859c-4cef-88aa-0a56d128c88c.png)

Using the in-focus PSFs (file named PSF_Focus_0mu.hdf5) give coherent results:
![Screenshot from 2021-12-13 09-09-12](https://user-images.githubusercontent.com/19569211/145775066-1245fd64-b4d8-483e-8ec3-e93bebd52c4a.png)

The only change I made on my YAML file (here attached) is the MappedFromFile PSF.

[reference0.yaml.TXT](https://github.com/IvS-KULeuven/PlatoSim3/files/7701992/reference0.yaml.TXT)

Réza

**Comment by drsamadi** [comment]
Additional information:
* PlatoSim 3.5.0-73-g94fa4614
* PSFs file taken from here:  http://ivs-kuleuven.github.io/PlatoSim3/_reqs_run.html

**Comment by Dries-Seynaeve** [comment]
Hi Réza

The issue was due to an error in the distortion table of the PSF file.  I have changed the PSF files on the ftp server, so normally this should work fine now after downloading the corrected PSF file. 

Kind regards 
Dries

**Comment by drsamadi** [comment]
Hi Dries,

great and thanks a lot ! I will test soon the new PSF file associated with a defocus of +80 micron. 
The one associated with a defocus of -80 micron results in the same bug. 
Could all the other focus be affected as well ?

Réza

**Comment by Dries-Seynaeve** [comment]
If this is an older file (so not downloaded today), this is normal. All the unfocussed PSF files had this issue.

**Comment by drsamadi** [comment]
Hi Dries,
this is to let you know that the problem is now fixed (at least for -80 and +80 micro, I have not tested the other files).
Beside I have a question: I have generated  full images using one of those Mapped PSF file.
 I want to determine  the PSF associated with a given star.
For  in this purpose, I search in the   Mapped PSF the PSF that is the closest to my star. I consider the focal plane position of the star and the distorted focal plane positions stored in the PSF file ('Coordinates map/Distorted/' ). I then compute the en-squared energy (EE, the energy in 2x2 pixel) associated with the corresponding PSF, which I compare to the EE computed using an imagettes extracted arround the star.
However, I get incoherent results because very often  EE(PSF)  is found to be lower than EE(star). This suggests that the star - PSF association is not correct.   
How should I proceed in order to find the correct PSF for each given star ?

It seams to me that there is no consistency between the information in 'Coordinates map/Distorted/' 
and the attributes associated with each PSF:
for exemple for the file PSF_Focus_0mu.hdf5
the attributes associated with the PSF with label '1' (the first in the HDF ) are the following:


![Screenshot from 2021-12-16 15-44-41](https://user-images.githubusercontent.com/19569211/146392948-5f9ea297-7c25-4f0f-b935-7a130454396b.png)

while the first values in 'Coordinates map/Distorted/'  are 
x = +59.24
y = -5.4981...

According to the PSF attirbutes, the PSF should be located at
(- centerCoordinates1 , + centerCoordinates2) = (-1.084321 , -1.084427)













Here below the piece of code I'm using to do the associatation:
`PSFdata = h5py.File(PSFfile,'r')
Xfp_psf = np.array(PSFdata['Coordinates map/Distorted/x'])
Yfp_psf = np.array(PSFdata['Coordinates map/Distorted/y'])
psf_keys = list(PSFdata.keys())

   j = np.argmin( (Xfp_psf-Xfp_k)**2 +  (Yfp_psf-Yfp_k)**2)
    print('PSF ID %s at Xfp = %f, Yfp = %f and at dXfp = %f, dYfp = %f from the target' %  (psf_keys[j],Xfp_psf[j],Yfp_psf[j],Xfp_psf[j]-Xfp_k,Yfp_psf[j]-Yfp_k))
    psfobj = PSFdata[psf_keys[j]]
    psf = np.array(psfobj)
    print( psfobj.attrs["centerCoordinates1"],psfobj.attrs["centerCoordinates2"] ) 
    psf = psf[::-1,::-1] # psf rotated by -180deg




`
here (Xfp_k, Yfp_k) is the focal plane position of my star (in mm)
For a star at  (Xfp_k, Yfp_k) = (-66.719258 2.656613)
I have the following print:
PSF ID 2895 at Xfp = -66.492048, Yfp = 3.296723 and at dXfp = 0.227210, dYfp = 0.640109 from the target
b'-2.326202E+01' b'6.666035E+01'






Thanks for your help
Réza

**Comment by carstenpaproth** [comment]
Hi Réza,
I think, if you use the mapped PSFs, then only a single PSF is used for the convolution of the whole image, so it is not surprising that you get incoherent results, because every star uses the same PSF.

**Comment by Dries-Seynaeve** [comment]
Yes, exactly. 

PlatoSim selects the PSF based on the focal plane coordinates of the centre of the subfield. For all the stars in the subfield we then assume this PSF.

**Comment by drsamadi** [comment]
ok, then this is a strong limitation if we want to simulate realistic full images, in particular to test the focus calibration algorithm

**Comment by carstenpaproth** [comment]
@drsamadi Either you split the full image simulation into simulations of several subfields, so that every subfield uses a different PSF, or you use an analytical PSF model, because that applys different PSFs to different stars. Unfortunately there is no analytical PSF for the defocused cases yet. So currently only the option to split the full image is feasible. Actually Denis makes something similar for the FGS, every guide star is simulated seperately, so that different mapped PSFs are used.

**Comment by drsamadi** [comment]
yes this is that I did at first place but since I have ~ 2,000 targets to simulate for testing the focus calibration algorithm, the calculation  takes a very long time using a single CPU
Probably I will have to parallelize my python code to make the calculation faster

**Comment by drsamadi** [comment]
Hi @Dries-Seynaeve 
I think that this issue has been solved however I do not have reply about my questions about the link between the information given in  'Coordinates map/Distorted/' and the PSF attributes.  
Do you know how to make the link between a (distorted) position in 'Coordinates map/Distorted/' and the corresponding PSF ?
thanks
Réza

**Comment by Dries-Seynaeve** [comment]
Hi Reza, 

Platosim does this as follows: 
1. It selects the PSF that is closest to the centre of the subfield. This PSF is used for all the stars that are in the subfield. So for this selection, the distortionmap is not used. 
2. We then add one-by-one the stars from the starcatalog onto the subfield. During this step the star coordinates are transformed into pixel coordinates. For this transformation, we do use the distortionmap.

So the PSF that is selected by Platosim is "uncorrelated" to the distortionmap in 'Coordinate map/Distorted/', while the positions of the stars on the subfield are determined by (among other things) the distortionmap. 

Kind regards
Dries
