### ISSUE TITLE
Orientation angle is not propagated through PlatoSim

### ISSUE THREAD

**Issue by YgabrielsY** [IvS-KULeuven/PlatoSim3#660]
Due to the changes in commit https://github.com/IvS-KULeuven/PlatoSim3/commit/2f7e49df91d5daa49caee145e2ae4e3d36eecbc5 , changes in the orientation angle are not propagated throughout PlatoSim. The change was based on Issue #447 (mostly discussed by @denisGrBach and @SaraRegibo) and merged into PlatoSim with PR #489 .
However, during testing with the DLR setup, setting the Orientation was required. PlatoSim was used in conjunction with the ImageGeneratorWrapper (DLR software) which executes 1 instance of PlatoSim per window which is configured (normally 30 windows). Consequently, not a single configuration file can be provided to PlatoSim since it is different for each window/instance. Therefore it is necessary to keep the orientation angle as an input parameter for the online PlatoSim feature. At DLR, we are using the `ClosedLoopDetectorClasses.cpp` with modifications already in our test setup. I propose that I'll create a PR with our changes to include this feature again in PlatoSim.

_Additional info_: For online PlatoSim the CCD position parameter is set to Custom (most likely to provide flexibility since at least the CCD number would need to be transmitted anyway with the window configuration and it is not much more effort to send the OriginOffsets and Orientation instead). Consequently, the Orientation parameter needs to be set by the window position packet in the `ClosedLoopDetectorClasses.cpp`.

**Comment by JorisDeRidder** [comment]
OK, we're awaiting your pull request.
