### ISSUE TITLE
When is the next release expected?

### ISSUE THREAD

**Issue by YgabrielsY** [IvS-KULeuven/PlatoSim3#667]
Is was unable to find when the next release of PlatoSim is expected (i.e. v3.5.2 or v3.6.0, I assume).

**Comment by Dries-Seynaeve** [comment]
Hi 

I am aiming to get a new release of PlatoSim by Monday (31/01/2022). 

Kind regards 
Dries

**Comment by YgabrielsY** [comment]
Hi Dries,

awesome, thanks for the quick reply!

Kind regards,
Gabriel
