### ISSUE TITLE
no CTI in the parallel overscan rows ? (SmearingMaps)

### ISSUE THREAD

**Issue by drsamadi** [IvS-KULeuven/PlatoSim3#676]
Hi,
I'm generating some simulations with a large number of  overscan rows (300) in order to use these measurements to calibrate  some  CTI parameters.
To have an appreciable level of CTI, I have imposed EOL values for the BOL. Here attached my YAML file.
However, when I look to the  parallel overscan rows  (SmearingMaps), I see a flat signal along each  column whereas due to the presence of CTI  the intensity in the parallel overscan  pixels  should  decrease along the column (see for instance PLATO-LESIA-PDC-TN-0030 or Prod’homme et al 2016, volume 9915 of
Proceedings of the SPIE). 
 

PlatoSim 3.5.2-8-g79e66d1
[00.yaml.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/8115497/00.yaml.txt)
f

**Comment by Dries-Seynaeve** [comment]
Hello Reza, 

We have not yet implemented CTI in the smearing maps. Thank you for bringing this to our attention, we will implement this. 

Kind regards 
Dries

**Comment by Dries-Seynaeve** [comment]
Hello Reza 

I have implemented the CTI in the smearingMap for the Short2013 model. It is not yet obvious to me how this should be done for the "Simple" CTI model, but once I figure it out I will implement this as well. 

Kind regards 
Dries

**Comment by drsamadi** [comment]
Hi Dries,
ok thanks a lot!
I'm going to test this new feature soon.
Réza

**Comment by drsamadi** [comment]
Hi
feature tested (3.5.3-19-g18d87597)  -> see issue #692
