### ISSUE TITLE
Offset of 1 pixel when using an uneven number of pixels for the subfield extension 

### ISSUE THREAD

**Issue by nicholasjannsen** [IvS-KULeuven/PlatoSim3#678]
There seems to a be a small bug when selecting the extension of subfield/imagette with an uneven number of pixels and then using the simulation object function `setSubfieldAroundCoordinates2()`. This offset is of 1 pixel in addition to whatever intra-pixel position the function has selected to be the center of the subfield. I have attached a simulation showing a subfield of 9x9 pixels.
[outputfiles.zip](https://github.com/IvS-KULeuven/PlatoSim3/files/8186527/outputfiles.zip)

**Comment by Dries-Seynaeve** [comment]
This should be fixed with the latest PR.
