### ISSUE TITLE
Aberration correction is always activated?

### ISSUE THREAD

**Issue by nicholasjannsen** [IvS-KULeuven/PlatoSim3#682]
From the output YAML file of any simulation, it looks like that the aberration correction is always applied. The name space called `IncludeAberrationCorrection` is missing from this file, while for e.g. the jitter and drift show a name space for their inclusion. The question whether the aberration correction is always applied, was first noticed in some simulations where a warning from PlatoSim was returned about no stars detected onto the CCDs. In these simulations the aberration correction was turned off. Given the relative path `inputfiles/orbit.txt` the above warning was seen, however, given the absolute path to the `orbit.txt` solved the issue, even though the this correction was turned off. 

Given the attached PlatoSim simulation examples, there is no pixel offset detected for the target star (index 1) for when turning the aberration correction on and off. Both simulations returns that the target star is detected on CCD 2 with (xpix, ypix) = (867.874982,  2991.625581) pixel coordinates.

[sim1-KDA-on.zip](https://github.com/IvS-KULeuven/PlatoSim3/files/8251823/sim1-KDA-on.zip)
[sim1-KDA-off.zip](https://github.com/IvS-KULeuven/PlatoSim3/files/8251824/sim1-KDA-off.zip)

**Comment by Dries-Seynaeve** [comment]
The issue was not caused by PlatoSim.
