### ISSUE TITLE
Problem with no information about detected stars to write to HDF5 while using a custom jitter file

### ISSUE THREAD

**Issue by nicholasjannsen** [IvS-KULeuven/PlatoSim3#686]
DESCRIPTION:
------------

A very perculiar problem happens when running PlatoSim using a custom input jitter file. While running simulations with PlatoSim and using the module `setSubfieldAroundCoordinates()` I got the following warning for certain stars, all of which were detected on a CCD as reported by PlatoSim itself: 
```
2022-03-21 13:06:47 WARNING Simulation: no information about detected stars to write to HDF5
2022-03-21 13:06:47 WARNING Camera: No star positions to write to HDF5 file.
```

KNOWN CASE:
-----------

The following are information gathered from `platosim.refereceFrames` and `platosim.simfile` while determining if the star falls on a CCD:
```
PIC ID           ra        dec       mag CCD         xCCD         yCCD        rOA        xFP        yFP
14504157  87.231886 -40.847874  9.982977   3  1842.077215  4316.06822    7.950299  34.238237  -4.761496
14504157  87.231886 -40.847874  9.982977   4  2905.579559  2605.072073  14.276313  34.837586  52.471063
```
In this example I have tested for Q1 and only changing the camera-group 1, 2, 3, and 4. For group 1 and 4 the above warning shows up when including jitter from the file `spiral_8Hz_airbus_3h.txt`. Attached is single example of running a simulation of quarter 1 (i.e. BOL of the mission so the time starts at t=0s) with and without jitter from a file with a duration of 430 exposures and a cadence of 0.125s. After both simulations I double checked that the YAML output file where identical when including and excluding jitter, respectively, except for the relative path to the star catalog file and the jitter file of course (I used `$ diff <file1> <file2>`). I also tested setting the jitter to Red Noise which was successful, hence, it must be because of the jitter file.  

Now while simulating only 40 exposures for group 1 and 4 the warning did not appear, however, using 41 exposures it again showed up. At least PlatoSim is consistent by raising a warning when using >40 exposures for both group 1 and 4. I have tested that I get the same results when testing all 6 cameras within each group (which should exactly be the same as no pointing- or alignment errors are included).

It turns out that by placing the jitter file in the same folder as where the output of PlatoSim is placed solved the non-detection of stars in subfield for the attached example (star ID 503) for camera-group 1, however, not for camera group 4. This fix is very strange because the file can indeed by located and used by PlatoSim for 40 exposures. I validated this by creating an animation (attached) where the jitter pattern is clearly visible.   

Since I was using the functionality `setSubfieldAroundCoordinates()`, or utilities of it, the proper CCD time-shift is automatically applied. Thus, I was thinking that perhaps the jitter time series was too short for PlatoSim to simulate, but decreasing the number of exposures didn't help (and effectively 1 exposure of 25 s should be sufficient because the maximum time shift of CCD 4 is 18.75 s). Nevertheless, by adjusting the jitter time column such that the first time point matches the start of the first exposure, together with saving the jitter file to the same output folder, solved the issue completely. Although I solved the issue, the behavior of PlatoSim seems very strange. If the problem was indeed because of a too short time column for the jitter file, PlatoSim usually exit with an error telling this. I was wondering if it could be because of an interplay between the short cadence and the CCD time shift, and that PlatoSim could not find an average time point for which to evaluate the jitter values (yaw, pitch, and roll). 

VALIDATION TEST:
----------------

Test data: [data.zip](https://github.com/IvS-KULeuven/PlatoSim3/files/8319583/data.zip)

Simply run PlatoSim from the command line to produce a simulation:
```
platosim 000000503.yaml output.hdf5
```

Before doing this change the star catalogue path with the yaml file.

The jitter file used is called `spiral_8Hz_airbus_3h.txt` and the star catalogue `starcat.txt`.

Simply turn jitter on and off to make the simulations.

**Comment by Dries-Seynaeve** [comment]
Hello 

I believe the issue was caused by not initialization a variable in the code which (sometimes) made it seem as if the CCD was covered off. This should be fixed with the latest push, let me know if this fixes the issue for you. 

Kind regards 
Dries

**Comment by nicholasjannsen** [comment]
From a validation test using the exact same files as mentioned above, I can confirm that the new update makes PlatoSim run successfully with stars detected on the subfield.
