### ISSUE TITLE
Sharp velocity gradient calculated from the `orbit.txt`

### ISSUE THREAD

**Issue by nicholasjannsen** [IvS-KULeuven/PlatoSim3#689]
I'm raising this issue on behalf of Réza Samadi. The attached plot show the spacecraft speed [km/s] as function of time [days]. As Réza mentioned in the DPA WG chat this rapid increase in speed (for <0.3 days) is perhaps not very representative for a "stationary" orbit around the L2 point. A simple solution could be to avoid the first day (or so) of the time series provided in the file `orbit.txt`
![speed-of-spacecraft-time-in-days](https://user-images.githubusercontent.com/36379445/161788237-142dbdca-4c69-41f3-9c70-69f97e275165.png)
.

**Comment by Dries-Seynaeve** [comment]
Hello Nich 

Thanks for flagging this. I changed the default startTime parameter in the input file. This means that PlatoSim will start using values from that time onward and ignore the values before. 

Kind regards 
Dries
