### ISSUE TITLE
Performance issue due to HDF5 structure

### ISSUE THREAD

**Issue by nicholasjannsen** [IvS-KULeuven/PlatoSim3#697]
The following issue was mentioned Steven, a system supporter from the VSC. He had a look into why the PlatoSim performance efficiency becomes very low when running simulations in parallel while also writing a large amount of the possible parameters to the HDF5 output file. The course is that it creates many subgroups (for every single exposure) inside one group in an HDF5 file. For a single quarter simulation at a cadence of 25 s this creates ~300k exposure subgroups. For example, this is true for the groups:

`/Cosmics/BiasMapLeft/exposureXXXXXX`
`/StarPositions/exposureXXXXXX`
etc.

This is apparently problematic in HDF5, see for instance:
https://forum.hdfgroup.org/t/limit-on-the-number-of-datasets-in-one-group/5892 

Steven did a test where he just kept adding subgroups to a group and he found that the performance (how many datasets that are created per unit of time) goes down fast as the number of datasets increases (the orange curve below). 

![platosim_hdf5_efficiency](https://user-images.githubusercontent.com/36379445/166432755-281c3868-52f0-48d8-9e0c-9e65ea6fc439.png)

A simple solution is to introduce more hierarchy. By simply storing the groups as follows:

`/Cosmics/BiasMapLeft/exposure6/842/880`

we can ensure that at most 1000 subgroups are present inside a group. Doing this the performance remains constant as the total number of subgroups increases (this is the blue curve in the above plot).

Regarding the group structure, as a user I think a better way to is if we save each of the parameters in example `/Cosmics/BiasMapLeft/` into the subgroups which already exist within each `/exposureXXXX/` subgroup (i.e. `Columns`, `EntryAngles`, `Flux`, etc.) and rename these according to the exposure. Then each column can directly be fetched, instead of invoking a for-loop to extract say the `Flux` value located within each exposure subgroup (which takes a very long time for 300k values!).

**Comment by nicholasjannsen** [comment]
Here is a small report about the increased efficiency while grouping the information about the star, the point-like ghost, the extended ghost, and cosmics as "per star" and not "per exposure" as it is done by default currently. @Dries-Seynaeve developed a new feature that allows to change this "grouping" from the YAML input file.

[PlatoSim_resources.pdf](https://github.com/IvS-KULeuven/PlatoSim3/files/10722924/PlatoSim_resources.pdf)

Overall a significant overhead and storage memory are reduced by the new grouping. However, saving all outputs while simulating a full mission quarter is dis-adviced from these tests. 

TODO
- The extended ghost HDF5 group needs to be updated as "per star" basis.
- The corresponding `SimFile` functions are now being updated by myself.

**Comment by nicholasjannsen** [comment]
All functions within `simfile.py` have now been adapted to this new feature. This was tested against the general test harness and through the tutorial notebook (no. 02) that calls all these simfile functionalities. @Dries-Seynaeve, you can merge whenever you like. Cheers

**Comment by Dries-Seynaeve** [comment]
This is merged now with the develop branch
