### ISSUE TITLE
Take field distortion into account when generating vignetting map

### ISSUE THREAD

**Issue by rhuygen** [IvS-KULeuven/PlatoSim3#7]
When generating the vignetting map (at pixel level) field distortion is currently not taken into account. 

When calculating the gnomonic radial distance for each pixel, the distorted coordinates should be calculated from the planar focal plane coordinates before transforming to angular focal plane coordinates.

**Comment by SaraRegibo** [comment]
The vignetting map as such no longer exist.  It is now replaced by a "throughput map", which combines the following effects:
- vignetting
- polarisation
- particulate & molecular contamination
- quantum efficiency

**Comment by SaraRegibo** [comment]
We realised that this is in fact not a bug but just the way we want it to be.  Closing.
