### ISSUE TITLE
strange smearing pattern

### ISSUE THREAD

**Issue by drsamadi** [IvS-KULeuven/PlatoSim3#702]
Hi,
I'am generating some full images and get strange images. Here attached two examples for two different stellar fields:
![Screenshot from 2022-05-30 14-02-17](https://user-images.githubusercontent.com/19569211/170991154-12142176-d2f3-491f-8c05-1aa07bd2d3c8.png)

![Screenshot from 2022-05-30 14-02-25](https://user-images.githubusercontent.com/19569211/170991169-b91faac7-fc80-454a-94f8-73894088051f.png)

Around the columns ~ 1345 , we see a pronounced and large vertical band. 
We see the same structure in the smearing map (over-scan rows). Subtracting the smearing pattern from the full image removes the presence of these  vertical bands.  This suggests that this structure is due to the smearing, however,  it is rather large (10 pixels width) and remains at the same location when we change the input stellar catalogue (as shown above) or when we change the pointing direction of the camera.  So a priori the presence of this structure can not be explained by the presence of a couple of bright stars in these columns. 

Réza

PlatoSim 3.5.3-19-g18d87597
[30.yaml.TXT](https://github.com/IvS-KULeuven/PlatoSim3/files/8798264/30.yaml.TXT)
[00.yaml.TXT](https://github.com/IvS-KULeuven/PlatoSim3/files/8798265/00.yaml.TXT)

**Comment by Dries-Seynaeve** [comment]
Hello Réza

I believe I have found the issue. There was a problem when we wanted to apply open shutter smearing when we also included relative transmissivity. This should now have been solved with the most recent commit. Let me know if this solves it for you. 

Kind regards 
Dries

**Comment by drsamadi** [comment]
Hi Dries,
ok, problem fixed with this update. Thanks!
Réza
