### ISSUE TITLE
In-code documentation: "Write ACS" in YAML inputfile

### ISSUE THREAD

**Issue by nicholasjannsen** [IvS-KULeuven/PlatoSim3#713]
This is just a small note that the in-code documentation may be wrong about the `WriteACS` and `WriteTelescopeACS`.  Currently the in-code documentation mention that the `WriteACS` is the telescope ACS, and that `WriteTelescopeACS` is the platform ACS. We should solve this inconsistency and perhaps a more intuitively structure is to use `WritePlatoformACS` for the Platform ACS and keep the `WriteTelescopeACS` for the telescope/camera ACS.

**Comment by Dries-Seynaeve** [comment]
I have changed this in the input.yaml file
