### ISSUE TITLE
Discontinuity in the smearing pattern

### ISSUE THREAD

**Issue by drsamadi** [IvS-KULeuven/PlatoSim3#714]
Hi,
we are currently simulating some full images, however we see a discontinuity in the smearing pattern, which reflect in the full images.

This plot shows the first row of SmearingMaps/smearingMap000000
the values are given in e-:

![Screenshot from 2022-09-12 16-03-01](https://user-images.githubusercontent.com/19569211/189674483-3a1a1dfb-7002-4593-8a64-e2bfd241843d.png)

here is the (raw) full image:

![Screenshot from 2022-09-12 15-57-43](https://user-images.githubusercontent.com/19569211/189674617-14fdc2cf-5666-4641-9826-1d2142f2fde7.png)

the discontinuity seen in the smearing pattern (around x~1350) can be seen in the full image.

Réza

  PlatoSim 3.5.3-37-g61f395c9

[010000001.yaml.TXT](https://github.com/IvS-KULeuven/PlatoSim3/files/9548733/010000001.yaml.TXT)

[010000001.log](https://github.com/IvS-KULeuven/PlatoSim3/files/9548735/010000001.log)

**Comment by Dries-Seynaeve** [comment]
Hi Réza, 

I seem to have trouble recreating your plots. Can you share how you created your first plot. (I have included how my plots look like) 

Kind regards 
Dries
![Figure_1](https://user-images.githubusercontent.com/74176898/190394837-0f6c28c0-1d2c-48ad-9420-53163b44f6a1.png)
![Figure_2](https://user-images.githubusercontent.com/74176898/190394843-46216bfa-b5bb-47d4-9413-f7b48dbaebb2.png)

**Comment by drsamadi** [comment]
Hi Dries,
I'm just doing this:

a=h5py.File('010000001.hdf5','r')
S=np.array(a['SmearingMaps/smearingMap000000'])
plot( (S[0,:]-1e3)*25 )

**Comment by drsamadi** [comment]
for the second plot I did this:
I=np.array(a['Images/image000000'])
imshow(I-1e3,origin='lower',vmax=200.,vmin=-10)

and with this link you can download our full image:


https://zendto.obspm.fr/pickup?claimID=o9sbRUSDYCxpQwaW&claimPasscode=cDt2Umf9AJsRdpbc&emailAddr=17743

**Comment by Dries-Seynaeve** [comment]
Thanks a lot, that is what I thought. However, I still am not able to recreate your results. 

For my simulations I used a different sky catalog and no jitter file, so probably this is causing this behavior. (I am guessing the star catalog). 
Could you send the jitter file and the star catalog that you use?  

Kind regards 
Dries

**Comment by Dries-Seynaeve** [comment]
Thank you for the files. I have been able to recreate the behavior, but only after I roll back my version of PlatoSim to 3.5.3. Can you try doing the simulations again with the most recent version 3.5.4. 

Kind regards 
Dries

**Comment by drsamadi** [comment]
ok, actually I forgot to tell you that this full image was generated by Emmanuel (with his version PlatoSim 3.5.3-37-g61f395c9)  however I have just checked with my own version (PlatoSim 3.5.3-47-g27cbaa3e) and I do not have this problem.

**Comment by Dries-Seynaeve** [comment]
Ok, that is great news. This probably is an issue that has already been solved then. :) 

I will close this issue then. If this still doesn't work for Emmanuel after upgrading PlatoSim feel free to reopen. 

Kind regards 
Dries

**Comment by Dries-Seynaeve** [comment]
Note: I believe the cause might be related to issue #702.

**Comment by drsamadi** [comment]
Hi Dries,
ok thanks for your feedback !
