### ISSUE TITLE
Distortion and vignetting

### ISSUE THREAD

**Issue by drsamadi** [IvS-KULeuven/PlatoSim3#716]
Hi, 
we want to determine the size of the camera fov, i.e. the radius of the circle (in the focal plane and centered at the position of the principal point) above which the vignetting is close to zero.

First of all, given the relation for the (total) vignetting:
( k[0] * thetadeg**2 + k[1] * thetadeg**4 + k[2] *  thetadeg**6 ) / 100
with k = [4.18e-2, -5.65e-5, 2.37e-7]
we have estimated the incidence angle (thetadeg) for which the vignetting is around 18% (i.e. the flux is reduced by about 82% )
This angle is thetadeg=18.9 deg.

Now given the gnomonic projection, this angle represents:
R =  tan(thetadeg)*f
where f is the focal length (f=*247.732 mm)

This gives in pixel unit:
R   = tan(18.9/180.*math.pi)*247.732/18e-3 ~ 4712 pixels

However, I believe that one has to account for the distortion since the latter deviates the ray that enters into the camera with incidence angle thetadeg. 
For radial distortion we have 
R' = R* (k1*v^2+k2*v^4+k3*v^6)
with  k1,k2,k3 are the distortion  coefficients ( k1=0.30 ; k2 = 0.5 ; k3= -2.56)
and v = R [mm] /f [mm] = R[pixel]/ (f [mm] / 18e-3)
This final gives:
R' ~ 4890 pixels 

The following figure shows a full image simulated with platosim where we have represented a circle (centererd at the principal point) with radius R' ) 4890 pixels 
![fig_4890pix_PP](https://user-images.githubusercontent.com/19569211/190190233-bd6a32cb-5263-4cfd-aff7-d0eef285e777.png)
Obviously the circle is to large.
On the other hand a circle of radius R = 4712 pixels  better matches the camera fov:
![fig_4712pix_PP](https://user-images.githubusercontent.com/19569211/190190762-59b7d318-8585-4ebb-acb3-219ea38af02e.png)

From this I interpret that platosim does not apply the distortion when applying the vignetting. Is my understanding correct ? 
Alternatively this may signify that in the formula:
 ( k[0] * thetadeg**2 + k[1] * thetadeg**4 + k[2] *  thetadeg**6 ) / 100

the angle thetadeg is NOT the incidence angle but rather the **refracted** angle. 
In that case  this would not be common since in general vignetting is given as a function of the incidence angle.

Réza
PlatoSim 3.5.3-37-g61f395c9

**Comment by drsamadi** [comment]
Hi,
in order to check my hypothesis, I have plotted the values in 'ThroughputMaps' as a function of  refracted angle and I get this:

![Screenshot from 2022-09-22 14-31-00](https://user-images.githubusercontent.com/19569211/191749962-99877587-2a61-4a9e-a513-42076a0c1a8c.png)

the red curve is the formula used for the vignetting (see previous message). We have a perfect match, this means that in the formula the angle  'thetadeg' must be interpreted as the refracted angle and not the incidence angle; 
However, we have checked this with Martin Pertenais: the vignetting is commonly given as a function of the incidence angle.

 
import h5py
a=h5py.File('010000001.hdf5','r')
Thp= (a['ThroughputMaps/throughputMap000000'])
x=np.arange(4510)*18e-3
y=x.copy()
x,y=np.meshgrid(x,y)
yp=(4510*18e-3+1.3)-y
xp=xp+1.3
r=np.sqrt(xp**2+yp**2)
r=r.flatten()
f=247.52
theta=np.arctan(r/f)*180./math.pi
plot(theta[0:-1:100],Thp[0:-1:100],'k+')
 k = [4.18e-2, -5.65e-5, 2.37e-7]
thetai=np.linspace(0,20,500)
v= ( k[0] * thetai ** 2 + k[1] * thetai ** 4 + k[2] * thetai ** 6 ) / 100
j=np.argsort(r)
v0 = np.interp(0,r[j],Thp[j])
plot(thetai,(1-v)*v0,'r')

**Comment by JorisDeRidder** [comment]
Hi Réza, 
Thanks for the report. PlatoSim currently does indeed not take into account the distortion when computing the vignetting.
Given the pixel coordinates of a point on the CCD we first compute the focal plane coordinates, and then
the gnomonic radial distance from the optical axis, which we call `thetadeg`. From what I understand from your post above, we should take into account that the rays have been distorted, and that we thus have to undistort the focal plane coordinates, before computing `thetadeg`. Correct?  I'll quickly implement this in PlatoSim.

**Comment by drsamadi** [comment]
Hi Joris,
yes indeed, one must convert distorted focal plane position to  undistorted one to derive the incidence angel 'thetadeg', then you can apply the formula.

Réza

**Comment by JorisDeRidder** [comment]
The latest version of the develop branch contains the fix for the problem reported above. Can you please confirm?

**Comment by drsamadi** [comment]
thanks, @manugr788 is going to generate new full images, and then @dianeberard will check whether or not  the FoV  becomes larger and  matches approximately my radius estimate R' ~ 4890 pixels (see above).

**Comment by drsamadi** [comment]
Hi Joris, 
we have checked and now the FoV has the expected size. I then close the issue
