### ISSUE TITLE
Inconsistent notation in YAML file

### ISSUE THREAD

**Issue by nicholasjannsen** [IvS-KULeuven/PlatoSim3#725]
From a user's perspective it is currently possible to include AOCS jitter and camera drift both from a file or a red noise model. In that case it would be less confusing for the user to have the same structural layout of the YAML blocks that deal with the inclusion of these. For example the jitter block looks like
```
    UseJitter:                       yes             # yes or no. If no, ignore everything below.                                                                                                           
    JitterSource:                    FromRedNoise    # FromFile, FromRedNoise or FromNetwork                                                                                                               
```
and the camera drift block is currently
```
    UseDrift:                        yes             # yes or no. If no, ignore everything below.                                                                                                           
    UseDriftFromFile:                yes              # yes or no. If yes: ignore RMS and timescale below                                                                                                    
```
Instead for consistency the camera drift block should be (the same as for the jitter) 
```
    UseDrift:                        yes              # yes or no. If no, ignore everything below.                                                                                                           
    DriftSource:                FromRedNoise              # FromFile or FromRedNoise                                                                                                     
```

**Comment by JorisDeRidder** [comment]
We should be conscious about the fact that this is a backward-incompatible change that may break the scripts of some of the PlatoSim users. I don't think it's actually confusing. The YAML parameters are quite clear and the doc string makes it even more so. You're absolutely right that it's indeed inconsistent and therefore inelegant, but is this sufficient reason to introduce a breaking change to the input file?

What we could do is to work in stages:
1) Accept both YAML options, but show a deprecation warning on the screen when the old version is still used.
2) In a later release, only accept the new YAML option.

**Comment by nicholasjannsen** [comment]
Indeed I fully agree with your statement. I think that such changes to the YAML file (or in general any other change that is not backward compatible should be kept for (2) a later release. I could make a new tag that specifically target code improvements that should be gathered for a future release, like `future release`. This would be for us to keep track of these inconsistencies without forgetting about them.
