### ISSUE TITLE
No zodiacal flux for some of the guide stars

### ISSUE THREAD

**Issue by BertoltLang** [IvS-KULeuven/PlatoSim3#76]
When using the python script fgs.py with the given parameters from the unchanged inputfgs.yaml file there are warnings like this:

2016-06-16 09:03:12 WARNING Sky::zodiacalFlux(): No data for (alpha, delta) = (75.570762, -56.077658)

for the guide stars #6, #15, #18, #24 and #31.

The corresponding output data is attached.

[zodiacalfluxerror.zip](https://github.com/IvS-KULeuven/PlatoSim3/files/317841/zodiacalfluxerror.zip)

**Comment by JorisDeRidder** [comment]
I noticed that you use azimuth and tilt = 1 degree, in your simulation. The platform pointing coordinates for the FGS simulation assume, however, both angle to be zero. Could you please rerun the simulation where you put both of these angles to 0 degrees?

**Comment by BertoltLang** [comment]
I ran the simulation with the proposed changes. Unfortunately, I got the same result for the stars in question.

[zodiacalfluxerror2.zip](https://github.com/IvS-KULeuven/PlatoSim3/files/325689/zodiacalfluxerror2.zip)

**Comment by JorisDeRidder** [comment]
OK, could you please also attach the exact python script (I guess a modified version of python/fgs.py) that you used to run PlatoSim?

**Comment by BertoltLang** [comment]
I'm afraid, this will not really help, since I used an unmodified version of the simulator. The only adjustment I made, was the change of the save-location of the simulation files. Nevertheless I submit the files.

[python_script.zip](https://github.com/IvS-KULeuven/PlatoSim3/files/325802/python_script.zip)

**Comment by JorisDeRidder** [comment]
I looked deeper into this, and the behaviour looks normal. PlatoSim3 currently has Zodiacal background information for ecliptic latitudes |beta| <= 75 degrees. Some of the guide stars are close to this border, and may jitter just above it. The coordinates you gave in the very first example have an ecliptic latitude of beta = -77 degrees, hence the warning.

**Comment by BertoltLang** [comment]
Yes, this issue still occurs, but you're right, for all stars in question, the ecliptic latitude is over 75 degrees. If you say that this is the anticipated behaviour of the program, the issue can be closed.
