### ISSUE TITLE
varsim does not run due to import error

### ISSUE THREAD

**Issue by Nagromancer** [IvS-KULeuven/PlatoSim3#776]
varsim fails due to the import errors in modules "python/platosim/varsim/models.py" and "python/platosim/varsim/phoenix.py". Currently, there are imports: 
`from platonium.var.utilities import find_nearest`
that should read
`from platosim.varsim.utilities import find_nearest`
Cheers!

**Comment by nicholasjannsen** [comment]
Thanks for this issue! I think that this happened through a git merge since I already updated this several months back. I just tested `varsim -h` and everything seems to work again.
