### ISSUE TITLE
Smearing values in PlatoSim 3

### ISSUE THREAD

**Issue by manugr788** [IvS-KULeuven/PlatoSim3#82]
Dear all,

I am a bit confused about the smearing values generated by PLATOSim.

My parameters :
Bkg = 134 e-/s
Offset : 1000 ADU
Gain : 20
If you try this simulation, you can disable the jitter.

The smearing values for columns without any stars are **OK** :
1000 ADU + 134 / 20 \* 3 = **1020 ADU**

However, the values for the 2 columns containing the unique star are very 
strange (in my point of view) and differ from what we get with PIS.

I have only one 10 magnitude star. The total flux of this star is :
FluxM0 \* TransmissionEfficiency \* QuantumEffciency \* LightCollectingArea \* 
10^(- mag \* 0.4)
Thus : 
`6.39e6 * 0.7191 * 0.5985 * 113.1 * 10 ** (- 10  /2.5)   = 31 104 e-/s`
To make things simpler, if I suppose that all the flux fall down a unique 
pixel, the flux brought by the star to the smearing is :
Flux \* time over one pixel = `31104 * 3 / (4510 + 30)  = 20 e-`
20e- => **1 ADU** 
But I get about 1250 ADU within PlatoSim result file
if I subtract the smearing background : 1250 - 1020 = **230 ADU** coming from the 
smearing star flux !
Using PIS for this simulation I got exactly 1 ADU coming from the smearing star flux.

May you check how PlatoSim computes this smearing value. Maybe PIS computation is false ?

Find enclose my parameter file.

Best regards,

Emmanuel Grolleau

[psim_smearing.zip](https://github.com/IvS-KULeuven/PlatoSim3/files/338822/psim_smearing.zip)

**Comment by SaraRegibo** [comment]
Hi Emmanuel,

the problem in the calculation of the open-shutter smearing has been identified and will be solved right away.

Nevertheless, I wonder whether the "+30" is necessary to calculate the contribution of the star flux to the smearing.  These 3s are the time to read out the whole CCD (i.e. 4510 rows).  Those 30 extra rows, coming from the over-scan, are not exposed and therefore the "+30" is not needed in the calculation (in my opinion).

**Comment by manugr788** [comment]
Hi Sara,

> the problem in the calculation of the open-shutter smearing has been identified and will be solved right away.

Great,

> Nevertheless, I wonder whether the "+30" is necessary to calculate the contribution of the star flux to the smearing. These 3s are the time to read out the whole CCD (i.e. 4510 rows). Those 30 extra rows, coming from the over-scan, are not exposed and therefore the "+30" is not needed in the calculation (in my opinion).

This 30 seconds are used within the formula to figure out the readout time of one pixel (3s / (4510 +30)), each pixel will be exposed (3s / (4510 +30)) seconds because during the readout time we read 4510 + 30 rows.

For example, with SkyBackground=134 e-/s, the true formula to compute the background smearing is :

4510 rows \* background(e-/s)  \* 3 / (4510 + 30) 

4510 \* 134 \* 3 / (4510+30) =  399 ADU

QED

De : Sara Regibo [mailto:notifications@github.com] 
Envoyé : mercredi 29 juin 2016 14:48
À : IvS-KULeuven/PlatoSim3 PlatoSim3@noreply.github.com
Cc : manugr788 emmanuel.grolleau@obspm.fr; Author author@noreply.github.com
Objet : [SPAM] Re: [IvS-KULeuven/PlatoSim3] Smearing values in PlatoSim 3 (#82)

Hi Emmanuel,

the problem in the calculation of the open-shutter smearing has been identified and will be solved right away.

Nevertheless, I wonder whether the "+30" is necessary to calculate the contribution of the star flux to the smearing. These 3s are the time to read out the whole CCD (i.e. 4510 rows). Those 30 extra rows, coming from the over-scan, are not exposed and therefore the "+30" is not needed in the calculation (in my opinion).

**Comment by SaraRegibo** [comment]
I understand, but I was actually convinced that it took 3s to read out the CCD rows (without pre- and over-scan rows).

Nevertheless, I can understand that those 3s would account for the readout of (1) the CCD rows, (2) the pre-scan strip, and (3) the over-scan strip, which would mean that you have to use 4510 + 30 + 1 in the formulae.  You seem to suggest that the readout of the pre-scan strip is not included in those 3s.  Isn't that a bit weird?

**Comment by manugr788** [comment]
Dear Sara,

You are right, the correct formula should be : 4510 + 30 + 1

Moreover, I suppose 3 seconds is the readout upper limit time, actually, it will probably take less than 3s to read Imagette+ Overscan + prescan but it’s not very important for us, PlatoSim and PIS will simulate a worst case.

De : Sara Regibo [mailto:notifications@github.com] 
Envoyé : jeudi 30 juin 2016 12:05
À : IvS-KULeuven/PlatoSim3 PlatoSim3@noreply.github.com
Cc : manugr788 emmanuel.grolleau@obspm.fr; Author author@noreply.github.com
Objet : [SPAM] Re: [IvS-KULeuven/PlatoSim3] Smearing values in PlatoSim 3 (#82)

I understand, but I was actually convinced that it took 3s to read out the CCD rows (without pre- and over-scan rows).

Nevertheless, I can understand that those 3s would account for the readout of (1) the CCD rows, (2) the pre-scan strip, and (3) the over-scan strip, which would mean that you have to use 4510 + 30 + 1 in the formulae. You seem to suggest that the readout of the pre-scan strip is not included in those 3s. Isn't that a bit weird?

**Comment by SaraRegibo** [comment]
I will update the code of the open-shutter smearing (and the corresponding test harness), assuming that we have to use 4510 + 30 + 1 and update the documentation (so it is clear what is included in the readout time).
