### ISSUE TITLE
AOCS output

### ISSUE THREAD

**Issue by manugr788** [IvS-KULeuven/PlatoSim3#84]
We need a small change of PLATOSIM AOCS output in order to have the same output as PIS.

In the AOCS dataset, Yaw["] Pitch["] Roll["] values should be the next displacement values, I mean we don't want to have a fist line with 0 values but we want a first line with the first displacement within jitter file (exactly like the jitter file).
## Jitter file 

head ../spiral_8Hz_airbus_3h.dat
0.0000  **-0.1087366616   0.0022591282  -0.0925855910**
0.1250  -0.1148039119   0.0035268126  -0.0971531340
0.2500  -0.1236901618   0.0090366157  -0.1031394500
0.3750  -0.1323905479   0.0150694310  -0.1075473400
## PlatoSim current AOCS output

head psim_jit/psim_jit_displacement.dat
# Time[s] Yaw["] Pitch["] Roll["]

   0.0000000000    0.0000000000    0.0000000000    0.0000000000
   0.1250000000   **-0.1087366616    0.0022591282   -0.0925855910**
   0.2500000000   -0.1148039119    0.0035268126   -0.0971531340
   0.3750000000   -0.1236901618    0.0090366157   -0.1031394500
## PIS displacement file output

head pis_jit_displacement.dat
# Time[s] X[pixels] Y[pixels] Yaw["] Pitch["] Roll["]

   0.0000000000    0.0085935735    0.0008577392   **-0.1087366616    0.0022591282   -0.0925855910**
   0.1250000000    0.0090534794    0.0009901695   -0.1148039119    0.0035268126   -0.0971531340
   0.2500000000    0.0096805534    0.0014496726   -0.1236901618    0.0090366157   -0.1031394500
   0.3750000000    0.0102686138    0.0019515318   -0.1323905479    0.0150694310   -0.1075473400

Emmanuel

**Comment by JorisDeRidder** [comment]
Thanks for reporting this problem! I fixed this in the latest version of the simulator. If you are satisfied with the result, please close this issue on GitHub.

**Comment by manugr788** [comment]
Perfect ! 
Issue closed.
