### ISSUE TITLE
Unable to install PlatoSim

### ISSUE THREAD

**Issue by AstroSaad** [IvS-KULeuven/PlatoSim3#871]
Hello all.

I've downloaded and installed PlatoSim from the source on my Mac OS using git and python's poetry package. platosim appears as a module when I enter "conda list". From that, the platosim version is 3.6.0

However, when I run Jupyter Lab and try to go through the tutorial notebooks, I get the error message, "No module named 'platosim' ". The command "platosim --version" does not work either; I get the message "command not found: platosim" in the terminal. 

Looking through the documenation and running the installation again, it appears as if the installation didn't work out and there is a list of errors. I'm attaching the output and error text files from the installation.

macOS Ventura 13.5
[inputfile.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/12397136/inputfile.txt)
<img width="777" alt="screenshot" src="https://github.com/IvS-KULeuven/Plat
[errors.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/12427940/errors.txt)
[output.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/12427941/output.txt)
oSim3/assets/136737742/5b1fbe39-df2c-414d-9db7-6a5e106809ed">

gcc - Apple clang version 14.0.3 (clang-1403.0.22.14.1)
cmake version 3.27.3

**Comment by AstroSaad** [comment]
[errors.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/12427952/errors.txt)
[output.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/12427953/output.txt)

**Comment by nicholasjannsen** [comment]
Hi @AstroSaad, 

Thanks for this bug report. We will quickly look into the problem. 

Can you make sure that all packages are installed correctly, i.e.:
```
python ./dependencies/installscripts/install_hdf5.py
python ./dependencies/installscripts/install_yaml.py
python ./dependencies/installscripts/install_armadillo.py
python ./dependencies/installscripts/install_fftw.py
python ./dependencies/installscripts/install_faddeeva.py
python ./dependencies/installscripts/install_zeromq.py
```
Run them one by one and check the output.

**Comment by nicholasjannsen** [comment]
@AstroSaad, I looked through your files and I only see warnings from the installation procedure (which is completely normal). Could the problem be as simple as in you haven't exported your `PLATO_PROJECT_HOME` variable? If not exported neither `platosim --version` works from bash and you also can't import any of the platosim modules. Please check if you have exported your environment variables, i.e. do `echo $PLATO_PROJECT_HOME`. If this is an empty string you haven't exported this variable.  Generally it's recommended to store these exports in your `~/.bashrc` file (or whatever it is called for Mac) so they are automatically loaded when you open a new shell.

Let us know if this works :)

**Comment by AstroSaad** [comment]
So I had exported the environment variables but my string wasn't correct. I've changed it and everything seems to be working now. Thanks for the help! :)

I don't know if this is a Linux thing or if I misunderstood the documentation. The documentation has the path-export as "export PLATO_PROJECT_HOME=<full/path/to/PlatoSim3>". I was including the "<" and ">" symbols in the string. Once I got rid of those, things started working. It might be something to keep in mind for the future.

**Comment by nicholasjannsen** [comment]
Okay good that it helped, have fun running some simulations with PlatoSim!

Btw the bracket `<>` is a syntax bracket and very commonly used in code writing. Its purpose is to indicate that whatever is inside the bracket has to be modified by the user.
