### ISSUE TITLE
How to generate artificial transits and install PLATOnium?

### ISSUE THREAD

**Issue by AstroSaad** [IvS-KULeuven/PlatoSim3#877]
Hello!

I've installed PlatoSim and I've gone through the tutorials. I had a specific task I wanted to which I'm not sure was covered in the tutorial or if it's possible in PlatoSim.

I want to be able to make a star and add a transiting planet which causes a dip in the lightcurve and a background contaminating source which causes an eclipse that produces another dip. The background source would either be another star or a large planet.

Making a star catalogue and adding a background source was outlined in the tutorial and seems relatively straight forward. I wanted to know whether it would be possible to add a transiting exoplanet to the star's lightcurve or whether that is something I need PLATOnium for?

Speaking of PLATOnium, I'm unable to install it. I've installed the python packages with poetry but I'm not able to run the next step, "./setup <path/to/plato_workdir>". I get the error message "no such file or directory ./setup". I've tried this from the PlatoSim directory and the Python environment directory. Could you please let me know how to go about installing PLATOnium?

**Comment by nicholasjannsen** [comment]
Hi Saad , thanks for your issue - it sounds like a fun project! Indeed if you want to use the script `varsim` to generate a planetary transit (which uses the BATMAN package behind the scenes), then you need to follow the instructions on our web page. With that said it seems like you already did this. Essentially the `setup.sh` file sets up all your path for you and copy the different python script to your Conda environment (so they are executable directly from bash).

Which distribution are on? The `setup.sh` script is only functional (yet) for Linux users, but if you have set the `PLATO_WORKDIR` path correctly (check if `echo $PLATO_WORKDIR` prints out your desired directory where you want to store all your simulation projects  (outside `/PlatoSim3`!)). The files described on our webpage (i.e. `platonium`, `picsim`, `varsim`, and `payload`) are all located in the folder `python/platosim/platonium` and you can run these files directly from bash again simply using e.g. `python varsim.py -h`. 

Note that `<path/to/plato_workdir>` is the path you need to configure and points to `$PLATO_WORKDIR`. I.e. on my Linux system this path is set to my project folder `/home/nicholas/software/workdir`. 

I hope this helps.

**Comment by AstroSaad** [comment]
Hi Nicholas

Sorry I meant to reply earlier. So I'm using a macOS system but from what you're saying, does that mean the setup.sh will only install on a Linux distribution?

In which case, I'll need to run an installation on one of the clusters I have access to.

Until then, are there any other ways to add planetary transits to the standard PlatoSim? Could it take a particular type of file or star catalogue as an input for example?

**Comment by nicholasjannsen** [comment]
Hi Saad, 

I think going to a Linux distribution is a bit overkill for you. The "installation" of PLATOnium is really minimal after your conda environment is set. Hence, what I'm saying is that you just need to make sure that the two paths exists from your command line:
- `$PLATO_PROJECT_HOME`
- `$PLATO_WORKDIR`
These paths have to be added to `.bashrc` file (or probably it's called something else on Mac). 
Next you should be able to go to `python/platosim/platonium` and run the different scripts. 

As described in the documentation page, you need to add a variable file path in your input YAML file. This can be done by following the tutorial. However, of course this file needs to exist, hence, that is why created the `varsim` script in order automatically create a variable signal that also include the bolometric correction for PLATO. 

If the above do not work, let's set up a zoom call and I can show you step-by-step how setup everything so you can run the PLATOnium toolkit.

**Comment by AstroSaad** [comment]
Hi Nicholas

Thanks for the help! I'm able to run the scripts in the platonium folder. I'll try different things and see how things go with my project. 

Would you have an idea on how long it would take to run different things?

**Comment by nicholasjannsen** [comment]
Okay good to hear that! 

Hm that depends on what you mean with "different things"? The script generating the variable source files (`varsim`) is very fast and can easily be parallelised on a cluster (e.g. that's what I did for the technical note: PLATO-PL-KUL-0020). Running PlatoSim using PLATOnium takes a bit more time. If you only want to compute the on-board photometry of 1 star, 1 camera, and 1 mission quarter (90 days = > 300,000 exposures) then it takes ~5-10 minutes. Saving more and more data to the HDF5 file will of course take longer time. Also note that the computation time also depends on the number of stellar contaminants you include. However, maybe send me an email (to nicholas.jannsen@kuleuven.be) about your project in detail if you want more info.
