### ISSUE TITLE
PLATOnium installation problem

### ISSUE THREAD

**Issue by AstroSaad** [IvS-KULeuven/PlatoSim3#883]
Hello all!

I'm running into issues when I try to install PLATOnium. Specifically, it's on the step "poetry install --with platonium".
I get the following error message:

  at ~/Library/Application Support/pypoetry/venv/lib/python3.9/site-packages/poetry/installation/chef.py:147 in _prepare
      143│ 
      144│                 error = ChefBuildError("\n\n".join(message_parts))
      145│ 
      146│             if error is not None:
    → 147│                 raise error from None
      148│ 
      149│             return path
      150│ 
      151│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with healpy (1.16.5) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "healpy (==1.16.5)"'.

I think it seems related to the "healpy" package. I get the same issue when I try installing on a different environment.

**Comment by guyrixon** [comment]
I see exactly this error when installing using python-3.9 loaded from the dead-snakes package-repository and poetry installed via pip. The problem goes away when using anaconda3 to provide python3.9 and then installing poetry as per the PlatoSim instructions.

**Comment by nicholasjannsen** [comment]
Thanks for this issue Guy. Indeed we only support Python 3 and thus Anaconda3. I add it to the documentation as well.
