### ISSUE TITLE
Missing module for picsim

### ISSUE THREAD

**Issue by guyrixon** [IvS-KULeuven/PlatoSim3#885]
picsim does not work on newly-installed, unmodified Platonium:

(platosim) gtr@spartan05:~/platonium$ picsim -h
Traceback (most recent call last):
  File "/home/gtr/anaconda3/envs/platosim/bin/picsim", line 54, in <module>
    from platosim.utilities  import errorcode, copyInputYAML
ImportError: cannot import name 'copyInputYAML' from 'platosim.utilities' (/home/gtr/platosim3/python/platosim/utilities.py)

**Comment by guyrixon** [comment]
It seems that copyInputYAML is not used in picsim. Commenting out the import works round the problem.

**Comment by nicholasjannsen** [comment]
This issue has been fixed with the issue #886 .
