### ISSUE TITLE
platonium fails to determine Plato field, passes wrong string

### ISSUE THREAD

**Issue by guyrixon** [IvS-KULeuven/PlatoSim3#887]
This happened:

(platosim) gtr@spartan05:~/platonium$ platonium --project smoke 1 1 1 1
/home/gtr/anaconda3/envs/platosim/lib/python3.9/site-packages/scipy/__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.26.0 is required for this version of SciPy (detected version 1.26.0
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

PLATOnium

Initialize and configure PlatoSim

[Error]: inputfiles/starcatalog.txt is Not a valid PLATO field!Options: NPF, SFP, LOPN, LOPS2

after a successful run of picsim for NPF. The error is raised in platosim.utilities in the getPointingField() method, where the name parameter has been set to 'inputfiles/starcatalog.txt' rather than a field name; i.e. the caller is wrong not the function.

**Comment by guyrixon** [comment]
Fixed this by changing starcataloguefile in inputfile.yaml to NPF instead of an actual file-name. A doc tweak might help here.

**Comment by nicholasjannsen** [comment]
Hi Guy, thanks for the input and I agree. I will also introduce an copy of the YAML to your project folder that automatically replace the `starcatalog.txt` with the PLATO field chosen when running `picsim` (like `NPF` in your case).

**Comment by nicholasjannsen** [comment]
An update of `picsim` has been made such that it automatically copies a YAML file to be used by `platonium` directly for the dedicated project. More documentation will following in our next release.
