### ISSUE TITLE
platonium crashes because script pproc is missing

### ISSUE THREAD

**Issue by guyrixon** [IvS-KULeuven/PlatoSim3#889]
(platosim) gtr@spartan05:~/platonium$ platonium --project smoke --nexp 100 -v3 --sample P1 1 1 1 1

PLATOnium

Loading stellar catalogue..

Initialize and configure PlatoSim

Applying platform jitter     (ACS RedNoise)

Information about stellar target
         ID    ra [deg]  dec [deg]        mag CCD   xCCD [pix]   yCCD [pix]  rOA [deg]  xFP [mm]   yFP [mm]  Ncon
0  44238502  256.926005  35.946993  10.259266   2  3004.082115  4085.977577  12.767889 -8.932404 -55.373478     1

Star catalog used in simulation
     RA [deg]  Dec [deg]    P [mag]  Dis [pix]
0  256.926005  35.946993  10.259266   0.000000
1  256.923159  35.944579  12.265382   0.800856

[PlatoSim]: Simulating N-CAM 1.1 Q1 for 100 exposures

Microscanning & PSF inversion
Downloading miscroscanning file..
Downloading microscan_spiral_8Hz_3h_BC.txt from plato
subpath=.

[PlatoSim]: Simulating 428 imagettes along Archimedean spiral

[pproc]: Pre-processing imagettes
sh: 1: /home/gtr/anaconda3/envs/platosim/bin/pproc.py: not found
[Error]: pproc.py failed due to the above error!

**Comment by jmccormac01** [comment]
Hi Guy, has it been installed into the bin folder outside the env?

**Comment by guyrixon** [comment]
Hi James, apparently not. There is no file pproc.py in my entire file-space on the test machine, meaning that it was never in the download. I can't see it on GitHub either. extract_contaminants.py is also missing.

**Comment by jmccormac01** [comment]
I had issues with the conda envs when trying to build my containerised version of platosim/L1 pipeline and ended up ignoring the envs (which might not be possible for you of course). 

If it helps this is my Dockerfile that worked with PlatoSim (commit bf1197705 Jun 15 2023) and L1 pipeline version at that time. 

[Dockerfile.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/12764824/Dockerfile.txt)

**Comment by jmccormac01** [comment]
It looks like pproc comes from the L1 SVN. Have you got that? See below:

```
(base) plato@plato1:/ecosystem/algorithms$ find . -name "pproc*" -type f
./WP/326100/ts-pproc/pproc.py
./WP/326100/ts-pproc/pproc.xml
./WP/326100/ts-pproc/build/lib/pproc.py
./WP/326100/ts-pproc/build/scripts-3.9/pproc.py
./WP/326100/ts-pproc/dist/pproc-1.0-py3.9.egg
```

and extract_contaminant.py (singular) also comes from L1. See below for a line from my Dockerfile:

```RUN cp WP/326100/misc/extract_contaminant.py /home/plato/miniconda3/bin/extract_contaminant.py```

I have this manual step in my build process because the installation process was broken for a few files. I manually put them somewhere on the path so they could be picked up.

**Comment by guyrixon** [comment]
Thanks, that's interesting. Your Dockerfile is using the folder WP/321000 to get the missing scripts, and that's not in the platosim download. Is there some other repo I have to download to get the pipeline?

BTW, can you confirm that the PIC information is all in the HDF5 file generated by the main part of PlatoSim? Because I can get that out of platonium by not setting the --sample option. If I know that the target/contaminant details are all in the HDF5 then I can work on reading those while the rest is being fixed up.

**Comment by guyrixon** [comment]
No, I don't have any file from L1 SVN. I'm not sure that I have access; do the S2E2 credentials work there?

**Comment by jmccormac01** [comment]
You will need the L1 prototype code from LESIA for this to work. If you contact Reza Samadi he can provide you with a LESIA login so you can access their code. Once you have that the last part of my Dockerfile should help you install the missing things.

I'll need to dig around in the platonium outputs from my simulations to answer the second part of your question.

**Comment by nicholasjannsen** [comment]
Hi Guy and James, 

thanks James for answering this issue so fast. Indeed as I also mentioned in the email Guy, the L1 pipeline is a completely independent software from PlatoSim. You need to ask @drsamadi for access.

**Comment by nicholasjannsen** [comment]
@jmccormac01 would it be feasible to use your `DockerFile.txt` to get a froozen installation setup for PLATOnium for the future? I'll need a bit of training to understand how to create a Docker file that is directly usable for both Linux (and potentially Mac) users. More specific, I don't exactly understand how the ecosystem works that you set up, but perhaps we can discuss this and create a single Docker file that people can use to install the full PLATOnium package (given that you have time for it). What do you think?

FYI I have been working on several new features for PlatoSim/PLATOnium, hence, I'm now bugfixing the L1 pipeline setup to make sure we have a froozen version of PlatoSim and the LESIA L1 pipeline that will work for all applications for the EAS and SAS testing.
