### ISSUE TITLE
StarCatalog XFP, yFP values

### ISSUE THREAD

**Issue by manugr788** [IvS-KULeuven/PlatoSim3#91]
Within StarCatalog dataset, the xFPmm and yFPmm values should be the Star xFPmm and yFPmm coordinates with no jitter, or at least, the xFPmm and yFPmm coordinates of the first Exposure (assuming that the first exposure has no jitter).
Actually, the xFPmm and yFPmm values of the StarCatalog dataset are **exactly equal** to the **LAST** exposure xFPmm and yFPmm values (whatever NumExposure is).
It's clearly a bug.

Solution : 
- [ ] modify PlatoSim to have xFPmm and yFPmm values of the StarCatalog dataset **exactly equal** to the **FIRST** exposure (Exposure000000 dataset) xFPmm and yFPmm values.

**Comment by rhuygen** [comment]
Will fix this after holidays...

**Comment by manugr788** [comment]
Have you progressed about this issue ?
I envisage to show a brief comparison between PlatoSim lightcurve and PIS lightcurve during the next DPA-WG meeting (10th october) but this issue is a bit critical to do this.
Thanks

**Comment by rhuygen** [comment]
you're right, I started working on this, but them got swallowed by another project. I'll pick it up asap.

**Comment by rhuygen** [comment]
This issue should now be fixed with #98

**Comment by rhuygen** [comment]
Emmanuel, can you please check my changes and close the issue if you are happy with the result?

**Comment by manugr788** [comment]
Thank you Rik,

I will check this on Monday.

Emmanuel

De : Rik Huygen [mailto:notifications@github.com] 
Envoyé : vendredi 30 septembre 2016 23:09
À : IvS-KULeuven/PlatoSim3 PlatoSim3@noreply.github.com
Cc : manugr788 emmanuel.grolleau@obspm.fr; Author author@noreply.github.com
Objet : Re: [IvS-KULeuven/PlatoSim3] StarCatalog XFP, yFP values (#91)

Emmanuel, can you please check my changes and close the issue if you are happy with the result?

**Comment by manugr788** [comment]
Everything is OK, 
Many thanks Rik
I close this issue.
