### ISSUE TITLE
Aperture masks computed by platosim are found to be systematically larger than these computed with  the official algorithm (ATBD)

### ISSUE THREAD

**Issue by drsamadi** [IvS-KULeuven/PlatoSim3#913]
Hi,

we have compared the masks computed by PLATOSIm with these computed with the official algorithm as described in this ATBD: 
 https://s2e2.cosmos.esa.int/confluence/display/PPDWS/PLATO-LESIA-PDC-DD-0030%3A+On-ground+Nominal+Mask+Calculation+ATBD)
which algorithm is directly inspired from Marchiori et al (2019).
Also attached here the justification document associated with this ATBD.

The masks computed by platosim are found to be systematically larger.

Here attached an example (zip file).

Our mask:
Mask key number: 205119488
Mask SNR: 935.419583
Mask SPR_tot: 0.000000
Mask size: 9

PLATOSim mask:
Mask NSR: 0.0005190071845807506  -> SNR = 1926.7556012886241
Mask size: 12

The key parameters in our mask calculation are:
readout noise =  50.216432 e-
Gain = 21.049 e-/ADU
Background:  2228.519209384918 e-/pixel/exposure 
StarPosition Exposure 0 target coordinates (row,col) : 3.0951453183121416, 2.896676013638114
inferred star flux =  929789.7321024069 e-/exposure
This configuration does not contain contaminant stars.

Platosim version:  PlatoSim 3.6.0-266-g338c8ad4

[PLATO-LESIA-PDC-DD-0022_i1.0_Nominal_Mask_Library_and_Mask_Update.pdf](https://github.com/IvS-KULeuven/PlatoSim3/files/13458367/PLATO-LESIA-PDC-DD-0022_i1.0_Nominal_Mask_Library_and_Mask_Update.pdf)

[000000025.zip](https://github.com/IvS-KULeuven/PlatoSim3/files/13458277/000000025.zip)

**Comment by JorisDeRidder** [comment]
Interesting, thanks for reporting. I have a question: when computing the masks yourself, did you use the empirical PSF or the true PSF (only available for simulated data of course)?

**Comment by drsamadi** [comment]
hi Joris, for this exercise we are using the true PSFs.

**Comment by JorisDeRidder** [comment]
Another question: did you use the mapped PSF or the analytical PSF?

**Comment by drsamadi** [comment]
we are using AnalyticNonGaussian

**Comment by drsamadi** [comment]
note that estimating the SNR from the lightcurve  generated with our aperture mask gives a SNR= 928, which is a value very close to the SNR associated with our aperture mask (SNR=935 ). Doing the same calculation with the lightcurve generated with PLATOSim gives a SNR = 688, hence we get a smaller SNR, which is not surprising since PLATOSim gives a larger aperture mask. 
This shows the consistency of our results and emphasizes the problem with  platosim.

**Comment by JorisDeRidder** [comment]
Could you also post the star catalog file you used? I.e. the .coo file as specified in your input yaml file. I didn't find it in the zip file.

**Comment by drsamadi** [comment]
the file .coo contains this single line:
82.004476 -63.893132 9.  25

**Comment by drsamadi** [comment]
I discover a mistake in the my calculation: I was using the optical PSF ('highResPSF') rather than the PSF as it is seen by the CCD and which includes the diffusion (diffusedPSF). 
Doing the calculation with the latter (diffusedPSF),  I get an aperture only slightly smaller than  platosim mask (there is only one pixel difference).

Our aperture mask (mask size 11): 
![Screenshot from 2023-12-10 11-16-38](https://github.com/IvS-KULeuven/PlatoSim3/assets/19569211/3fd8c0a4-5388-478c-be56-381fb008759e)

platosim mask (mask size 12):
![Screenshot from 2023-12-10 11-16-46](https://github.com/IvS-KULeuven/PlatoSim3/assets/19569211/e68fad3d-be84-4d79-b8ce-cd6aa5db615e)

However, there is still a  discrepancy concerning the SNR value. Our SNR value is   933.393662 whereas platosim value is  1926.755

Here attached the new data set with the problem of the psf fixed.

**Comment by JorisDeRidder** [comment]
@drsamadi I fixed a bug in the photometry module that seems to solve the problem you reported. The numbers are now on par with the ones that you quoted above. In addition, I noticed that PlatoSim's photometry module didn't include quantisation noise yet when determining the S/N of pixels, so I implemented this as well. 

Could you use the new version in the develop branch to convince yourself that the problem is indeed resolved now?

**Comment by drsamadi** [comment]
Hi Joris, ok great ! I will check the new version and will come back to you.

**Comment by drsamadi** [comment]
OK, with the new version - and for this test case - I get  a consistent value of the SNR: 948.44 to be compared to the  933.393 with our calculation; 
However, the aperture masks differ: the one computed by platosim has still one more pixel. 
See the plots shown above (the shape of the platosim mask is unchanged).

**Comment by JorisDeRidder** [comment]
Thanks for checking it out!
Concerning the extra pixel in the mask: which flatfield are you using for your computations? The same one as generated by the PlatoSim calculations?

**Comment by drsamadi** [comment]
good question: the PRNU/flatfiled is not taken into account in the aperture mask calculation algorithm (see https://s2e2.cosmos.esa.int/confluence/display/PPDWS/PLATO-LESIA-PDC-DD-0030%3A+On-ground+Nominal+Mask+Calculation+ATBD ).

**Comment by JorisDeRidder** [comment]
I noticed that the pixel coordinates of the star are slightly different for PlatoSim than for your calculations:
`PlatoSim: 3.009073,  2.899124`
`Reza:     3.095145,  2.896676`
which could have an effect on the exact shape of the mask. Is it possible for you to insert the exact PlatoSim pixel coordinates in your code, to see if this resolves the mask issue?

**Comment by drsamadi** [comment]
yes indeed this could explain our differences. 
 I confirm my values however, for the platosim position, according to the information given in StarPositions/exposure0000, I see:
row,col =3.008591513258402 ,  2.899238287027167
I attach the data set. 

The difference between my coordinates and the platosim ones are due to the fact I include the chromatic aberration, which I measure from the PSF ('diffusedPSF').
Here the chromatic aberration is the difference between the photocenter of the PSF and the middle of the domain in which the PSF is sampled. In this case this an area of 8x8, hence the center is (4,4). 
For the PSF here, the Chromatic aberration shifts are
ca_dx = -0.002341425171616951, ca_dy = 0.08681365135126828
If you add this shift:
(3.008591513258402  + 0.08681365135126828  ,  2.899238287027167  -0.00234142517161695 )
you retrieve my position:
(row,col ) = (3.0954051646096703, 2.89689686185555)


[000000025_2.zip](https://github.com/IvS-KULeuven/PlatoSim3/files/13648325/000000025_2.zip)

**Comment by drsamadi** [comment]
btw I have tested using your centroid position (xc,yc) =  (2.899124 ,3.009073)
but this does not change the shape of the aperture mask

**Comment by drsamadi** [comment]
in order to test my chromatic correction, I have generated a 24x24 imagette with an PSF  that has a large width (by increasing significantly the diffusion; ChargeDiffusionStrength:     1.5  )
According to platosim,  my star is located at row,col = 12.008591513258402, 11.899238287027167

My estimate for the chromatic aberration is:
 ca_dx = -0.0001664121334865598, ca_dy = 0.006337238656308308
Accordingly my star must be located at : 
(row,col) : 12.089163952145078, 11.897037654102611

Then I took the first imagette, corrected for the background and smearing, and computed the photocenter (COB) and get :  (col,row) =(11.8989741757663, 12.101702356319501)

Accordingly the error in X (col) and Y (row) are respectively:
-0.0019365216636888505 , -0.012538404174422979
As you can see the error is smaller than the amplitude of the chromatic aberration, which suggests that the chromatic aberration is relevant.

Attached my simulation.

[000000031.zip](https://github.com/IvS-KULeuven/PlatoSim3/files/13650041/000000031.zip)

**Comment by JorisDeRidder** [comment]
Thanks for the pointer on the chromatic aberration. 
It's difficult to establish where the discrepancy in the number of mask pixels comes from, and/or whether there is an error in PlatoSim. I checked all 12 pixels of the mask, but the total flux of the star is so high that even the lowest pixel in the mask exhibits more than twice the flux of the sky background. So it seems correct to include the pixel in the mask.

**Comment by drsamadi** [comment]
yes agree, this is not straightforward .

In order to help understanding the origin of this discrepancy I have plotted the SNRagg (see the definition in Marchiori et al 2019) as a function of the pixel index (sorted in decreasing SNR values): 

![Screenshot from 2023-12-12 21-33-46](https://github.com/IvS-KULeuven/PlatoSim3/assets/19569211/9483ee1f-554d-4566-a151-737349f3a6ae)

It is useful to zoom near the optimal SNR:
![Screenshot from 2023-12-12 21-34-45](https://github.com/IvS-KULeuven/PlatoSim3/assets/19569211/b54d2dbf-b764-4f7d-a674-5b9a3802f16d)

as you can see the maximum SNR is reached with the 11th pixel (index 10) . This is the reason my aperture mask has 11 pixels. 
It is true that the next pixel (the  12th ) results in a SNRagg only slightly smaller than my optimal value (933.393529).

**Comment by JorisDeRidder** [comment]
The corresponding plots computed with PlatoSim peak at the 12th pixel, as illustrated below. 
<img width="2008" alt="AggregatedSNR1" src="https://github.com/IvS-KULeuven/PlatoSim3/assets/5747893/d845b632-ad42-4379-a5f3-929a2c51480f">
<img width="2008" alt="aggregatedSNR2" src="https://github.com/IvS-KULeuven/PlatoSim3/assets/5747893/59201adf-913b-486f-817f-dd01588d26b3">

**Comment by drsamadi** [comment]
ok , then  I think we have to investigate the parameters used for the SNR calculation since you are reaching an higher SNR value, here below my parameters and aperture characteristics:

gain = 21.049086
readout_noise = 50.216432
Mask center at x,y = 2.896897, 3.095405
Mask key number in CCD-RF = 209314048, Mask key number in FEE-RF = 209314048
Optimal Binary Mask SNR = 933.393529, Maximum Mask SNR 933.393529,  Pixel Nb = 11, SPRtot = 0.000000
Readout noise = 50.216432 [e-],  Background level = 2228.921889 [e-], star input flux = 9.297897e+05
Mask efficiency = 0.990587

**Comment by JorisDeRidder** [comment]
Here are the numbers I obtain with PlatoSim:
`gain = 21.049086` ✅
`RON = 50.216432` ✅

The variance of my quantisation noise is:
`Variance quantisation noise = 1.754091`

As you mentioned before I have a slightly different mask center because of the chromatic aberration:
`Mask center: (x,y) = 2.899017, 3.008331`

For the input fluxes I have:
`Sky = 4527 ph/pix/exp`
`Star = 1890854 ph/exp` 
Since my throughput map has values between `0.4921` and `0.4924` I obtain sky fluxes in the range:
`Sky = 2228 -> 2229 e-/pix/exp` ✅ 
Multiplying the throughput range with the star flux I obtain
`Star = 930489 ->  931057 e-/exp`  ❓
which is a little bit higher than the values you quoted. Since my star flux is a bit higher than yours, it's not surprising that my optimal mask SNR is also a bit higher:
`Optimal Binary Mask SNR = 949`

Since the aggregated SNR of your 12th pixel is only marginally decreasing the optimal SNR, I checked if a slight flux decrease would change my results. I therefore decreased the brightness of the star from `V=9` to `V=9.035`. This led to an aggregated SNR of  
`Optimal Binary Mask SNR = 933`
and a star flux of 
`Star  = 1830872 ph/exp -> ~ 901338 e-/exp`
but even then I still have a mask of 12 pixels rather than 11.

**Comment by drsamadi** [comment]
thanks !
I  have to investigate why I have a smaller value for the input flux
however, I'm surprised by your value for the variance of the quantification noise.
In our formula (see  https://s2e2.cosmos.esa.int/confluence/display/PPDWS/PLATO-LESIA-PDC-DD-0030%3A+On-ground+Nominal+Mask+Calculation+ATBD)
the variance is G^2/12 =  21.049086**2/12. = 36.922001786283

**Comment by JorisDeRidder** [comment]
You're right about the quantisation noise. I meanwhile fixed the bug in the develop branch. It has no effect on the mask size, though, still 12 pixels.

**Comment by drsamadi** [comment]
OK, on my side  adopting your value does not change my aperture mask and my SNR is only slightly increased ->    934.06378

I look at the code, and I see this line:

const double varianceRON = sqrt(pow(readoutNoise, 2) + pow(frontEndElectronics->getReadoutNoise(), 2));      // [electrons / pixel]

what you are computing here is not the variance but the standard deviation, right ? I think that there is then an error in your NSR calculation.

**Comment by JorisDeRidder** [comment]
I don't think the line of code you quote is wrong, but the variable naming does make it rather confusing.
 
The way we implement read noise in PlatoSim is that a read noise of `39 e-/pix` implies that gaussian noise with `sigma=39 e-/pix` is added. Because of the propery of Gaussians, two such read noises (the FEE and the CCD) should therefore be quadratically added to get `sigma_tot = sqrt(sigma_ccd^2 + sigma_fee^2)`.

The confusion arises because it's this `sigma_tot` value expressed in `(e-/pix)` and not the value `sigma_tot^2` expressed in `(e-/pix)^2` that is added directly to the variances of other noise sources like photon noise and quantisation noise (both variances also expressed in `e-/pix`). Hence I named it `varianceRON`...

**Comment by drsamadi** [comment]
yes but look latter in the code when you compute the variance map:

                    varianceMap(irow, icol) = (singleTargetMap(irow, icol) + contaminantMap(irow, icol) + skyBackground) 
                                                * throughputMap(irow, icol) 
                                              + varianceRON + varianceQuant;


Since you are computing the variance either you add the variance of the RON or the square of its standard deviation that is sigma_ron^2

**Comment by drsamadi** [comment]
I have changed:
 const double varianceRON = sqrt(pow(readoutNoise, 2) + pow(frontEndElectronics->getReadoutNoise(), 2)); // [electrons / pixel]
by
    const double varianceRON = pow(readoutNoise, 2) + pow(frontEndElectronics->getReadoutNoise(), 2) ;      // [electrons / pixel]^2

and get an aperture mask almost the same SNR (=933.92) and the same number of pixel. I have also checked the shape: it is identical to my aperture mask

so I think this error explains our discrepancy

**Comment by JorisDeRidder** [comment]
Great that the root cause of the mask discrepancy has been found!

I'ld still like to get a better grasp on which version of the readout variance is the correct one. Without the square root, the units of the `varianceRON` is `[e-/pix]^2`, which in Eqs. (36)-(37) has to be added to the variance of stellar flux which, because of the Poisson property, is simply the flux itself, expressed in `[e-/pix]`. The units are therefore incompatible when you omit the square root. What am I missing here?

**Comment by drsamadi** [comment]
the readout noise (ron) is added on each pixel (independently of the others)
the ron is typically ~ 50 e- (RMS) 
it variance is hence sigma^2 = 50^2 = 2500 [e-^2]
This variance is for a given pixel, but if you sum m pixels, the variance of the noise induced by  the RON will be  
m * sigma^2 =  m  2500 [e-^2] 
the corresponding standard deviation will hence be sqrt(m*2500) = sqrt(m) * 50  [e-] 
 
This the same for the photon noise:
suppose that the intensity in any  pixel is 100 e-
hence the corresponding standard deviation  is  sqrt(100) = 10 e-  right ?    which one does not express as  10 e-/pixel  despite the fact that this is the noise we have for a single pixel, right ?

**Comment by drsamadi** [comment]
concerning the issue of the chromatic aberration (see above), I found an other evidence that our chromatic aberration is correct and required:
when applying the PSF inverse (Daniel's algorithm) we find a inverse PSF centered exactly at the corrected position of the star (by construction, our PSFs are decomposed in a 6x6 grid centered at the star centroid position).

Without  the chromatic aberration the inverse PSF is (x,y) =  [2.99760992, 3.08664881]
The shift in Y is non-negligible :  0.08664881 px, 
this shift coincides almost exactly to our estimate of the chromatic aberration, which is for  our simulation with ID 25: 

PSF Chromatic aberration offset ca_dx = -0.002341425171616951, ca_dy = 0.08681365135126828

In other word,  the position given in the field StarPosition is not exact, ones has to account for the chromatic aberration.

Should I open an issue for this topic ?

**Comment by JorisDeRidder** [comment]
I fixed the problem of the RON (pull request #929) pulled into the develop branch.
For the chromatic aberration I would indeed invite you to open a separate issue (and assign Dries).
Thanks for helping us to locate the bugs!

**Comment by drsamadi** [comment]
OK thanks.
For the chromatic aberration I will open a new issue.

**Comment by drsamadi** [comment]
there is an error in this line:
 varianceQuant = 1.0/(combinedGainRight*combinedGainRight) / 12.0;

what is computed is not the variance (neither it is the standard deviation)
the variance associated with the quantification noise is the quantity:
G^2/ 12 
(I can find the reference for this formula)

Also when printing the variance associated with the quantification noise 

 var quant = " + to_string(varianceQuant) + " e-/pix"
the unit is e-^2 since we are dealing with a variance 
The same remark holds for the variance associated with the readout noise:

  to_string(varianceRON) + "e-/pix"

the unit is e-^2

On the other if you print instead the standard deviation the unit is e- for both quantities

Finally this line is a bit strange:
                                       ...        + varianceRON*varianceRON + varianceQuant;

here you adding quadratically the noise, so you are adding the variance 
hence consistently one should have
  ...  + varianceRON + varianceQuant;

and accordinlgy varianceRON shoudl be defined as:

varianceRON = pow(readoutNoise, 2) + pow(frontEndElectronics->getReadoutNoise(), 2) ;

and varianceQuant should be computed as follows:

varianceQuant = 1.0/pow(combinedGainRight*combinedGainRight,2) / 12.0;

for the right channel, and equivalently for the left channel

**Comment by JorisDeRidder** [comment]
Thanks for checking. I agree that the implementation of the varianceRON (although not leading to wrong computations), was indeed a bit idiosyncratic, so I changed it according to your suggestion. I also changed the units in the log file and the in-code comments.

I don't quite understand your comment about the quantisation error, though. What I compute is the variance of a uniform distribution (cf the comments in the code above the line that computes it). It is indeed G^2/12, but the bottom line in your previous post suggests it should be G^4/12. Could you clarify?

**Comment by drsamadi** [comment]
the variance of the quantification noise is indeed:
G^2/12
this is coded as:
varianceQuant = 1.0/pow(combinedGainRight*combinedGainRight,2) / 12.0;

since
G = 1./(combinedGainRight*combinedGainRight)
which is the global gain of the full chain (CCD+electronic) 

G is indeed the quantification step (typically 25 e-/ADU)

do we agree or may be I did not understood your question/comment?

**Comment by drsamadi** [comment]
btw the reference for the formula q^2/12  (where q is the quantification step) can be found e.g. in Loger, "The analysis and calibration of analog to digital encoders", 1967, NASA TN D-3913

**Comment by JorisDeRidder** [comment]
I just read Loger (1967) and it's described there as I understood. The quantisation variance is indeed G^2 / 12, with G the quantizing interval. But why do you say that `G = 1./(combinedGainRight*combinedGainRight)`?  I would think the quantizing interval is simply `G=1/combinedGainRight` expressed in [e-/ADU].

**Comment by drsamadi** [comment]
oups yes you are absolutely right,  G = 1/combinedGainRight 
(I made a confusion, i thought you were mutliplying the ccd gain and the FEE gain..)

**Comment by drsamadi** [comment]
issue solved
