### ISSUE TITLE
Picsim running errors (both branches)

### ISSUE THREAD

**Issue by AstroSaad** [IvS-KULeuven/PlatoSim3#914]
Hello!

I've recently git pulled the master branch and have installed platonium with poetry. I've tried running picsim but I get an attribute error.
```
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/bin/picsim", line 181, in <module>
    outputFileFOV = (outputDir / outputPrefix).joinwith_suffix(fileFormat)
AttributeError: 'PosixPath' object has no attribute 'joinwith_suffix'

```
If I switch over to the develop branch, re-build and install platonium with poetry, I get a different error running picsim
```
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/bin/picsim", line 181, in <module>
    outputFileFOV = (outputDir / outputPrefix).joinwith_suffix(fileFormat)
AttributeError: 'PosixPath' object has no attribute 'joinwith_suffix'
```

**Comment by nicholasjannsen** [comment]
Hi Saad, 

thanks for letting us know. Can you be specific in what you did to run `picsim` and the steps leading up to the script execution?

I just pulled the most recent version of the master branch and don't get that error. I am using Python 3.9 and installed all python packages into my Conda environment with `poetry install --with platonium` and I made the PLATOnium scripts executable globally using `./setup.py <path/to/plato/workdir>`. However, I did notice that the `pyarrow` package was missing in the default `platonium` domain, and hence `picsim` is crashing when the output Feather files are saved to the output location. I  have just pushed a bugfix change which are waiting to be confirmed by @Dries-Seynaeve .

**Comment by AstroSaad** [comment]
Hi Nicholas.

Specifically, the command `picsim 100 P1 NPF -p -s --project Test1` gave the error.
However, picsim was able to run fine when I dropped the "-s" term.
I was under the impression that I needed that term to save a list of the targets and contaminants. However, I believe picsim does that by default.

**Comment by nicholasjannsen** [comment]
Ah, as the help function mention (`-h`), the argument `-s` is only to be used if you wan to save a stellar catalogue in a ascii format that PlatoSim uses => not the format that `platonium` uses!  In this way one can generate a catalogue that can be used when running PlatoSim from the command line. However, since you get an error I need to make an exception case that the user needs to provide at least a name when using `-s`. Hence, in general use either `--project` or `-o` to save the files such you can run `platonium`.

**Comment by nicholasjannsen** [comment]
The pull request for the master branch has now been completed so I'm closing this issue.
