### ISSUE TITLE
Platonium module errors 

### ISSUE THREAD

**Issue by AstroSaad** [IvS-KULeuven/PlatoSim3#916]
Some errors come up when I try to run the "payload" and "platonium" modules/commands of platonium. 

When I run payload, I get a ValueError:
```
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/bin/payload", line 618, in <module>
    x = InstrumentSetup(args)
  File "/home/ubuntu/anaconda3/bin/payload", line 88, in __init__
    self.ra, self.dec, self.kappa = PF[args.field]
ValueError: too many values to unpack (expected 3)
```
The command I'm using is something like `payload --project Test1 -p NPF 150`

When I run platonium, I get a TypeError:
```
Applying platform jitter     (ACS FromRedNoise)
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/bin/platonium", line 1344, in <module>
    sim = p.init_sim()
  File "/home/ubuntu/anaconda3/bin/platonium", line 557, in init_sim
    xFPmm, yFPmm = rf.undistortedToDistortedFocalPlaneCoordinates(xFPmm, yFPmm,
TypeError: undistortedToDistortedFocalPlaneCoordinates() missing 1 required positional argument: 'focalLength'
```
The platonium error sounds like I need to have focal plane coordinates in the yaml file. However, I'm unsure of how to add this. I've tried moving the "focallength.txt" file to the project input folder but with no success.

These errors occur on both the master and the develop branch

**Comment by nicholasjannsen** [comment]
Hi Saad, 

it strange that there is no exception raised here. The command is:
```
payload 150 NPF --project Test1 -p
```
hence first the number of stars and then the pointing field.

The error with the focal plane is an issue that was fixed a while back. Try to pull the latest version of develop branch and see if you can run the following commands:

```
picsim --pic 150 P1 LOPN1 --project Test1 -p
payload 150 LOPN1 --project Test1 -p
platonium 1 1 1 1 --project Test1 -p
```

I have recently implemented PIC 2.0.0 if you want a more updated stellar catalogue.

**Comment by AstroSaad** [comment]
Hi Nicholas

My own branch wasn't fully syned up to the develop branch. I've fixed this issue and have pulled the latest version of the develop branch.

The commands work with no issues.

Given that the commands have changed slightly, would you be updating the online documentation as well?

**Comment by nicholasjannsen** [comment]
Hi again, thanks for the update. I have just gone through some final modifications to the `develop` branch. This will be merged into the `master` branch shortly and PLATOnium should be very stable for PlatoSim v. 3.6.1. I'm updating the documentation as well and pushing it later today or tomorrow.
