### ISSUE TITLE
Simulations with changed FocalPlaneOrientation don't deliver any usable data 

### ISSUE THREAD

**Issue by BertoltLang** [IvS-KULeuven/PlatoSim3#92]
As far as I understand it, changing the FocalPlaneOrientation parameter in the inputfgs file should only change the position of the star on the CCD field, but whenever I execute the fgs.py file I get warnings like these:

Running the simulator for guide star 0
Guide Star Coordinates [deg]: 82.90001374489015, -45.925314985766406
2016-08-08 11:41:40 WARNING Simulation: no information about detected stars to write to HDF5
2016-08-08 11:41:40 WARNING Camera: No star positions to write to HDF5 file.

I'm using PlatoSim version 3.1.0-292-g801be5d on Ubuntu 14.04, gcc 5.3 with CMake
 2.8.12.2.

I attached the log-message file and the corresponding .yaml file

[FocalPlaneOrientationIssue.zip](https://github.com/IvS-KULeuven/PlatoSim3/files/406539/FocalPlaneOrientationIssue.zip)

UPDATE:

I think there are two different reasons for this problem:
1. In referenceFrames.py line 1073 (setSubfieldAroundCoordinates) focalPlaneAngle is introduced as a value in degree. In line 109 f. in skyToFocalPlaneCoordinates focalPlaneAngle is used, to convert xFP and yFP in xFPprime and yFPprime. The problem is probably, that focalPlaneAngle is never converted to radiant. 
2. When using a different Focal Plane Orientation no stars are written in the star catalog. This originates in the fact, that in StarCatalog.cpp line 168 (getStarsWithinRadiusFrom), there is a check whether the angular distance between the center of the subfield and the star position is smaller than the radius of the subfield. Since there is no consideration of the rotation of the subfield center coordinates in relation to the star coordinates within the function angularDistanceBetween (line 218 in SkyCoordinates.cpp) there is only a very slight chance, that the position of the corresponding star will be considered as "within the subfield".

**Comment by JorisDeRidder** [comment]
Thanks for spotting the degrees to radians bug in setSubfieldAroundCoordinates(). This has now been fixed in the latest version. 

Your second remark about getStarsWithinRadiusFrom() does not seem to be a bug. The function computes which stars are within a certain radius from the center (ra0, dec0) and to compute the latter coordinates given the center of the subfield, the focal plane orientation is needed and taken into account.

Can you check again, and let me know if I can close this issue?

**Comment by BertoltLang** [comment]
Thank you for fixing the bug, it seems to work now.
