### ISSUE TITLE
default values for trap densities at EOL are not consistent with the paper by Prod’homme et al (2016)

### ISSUE THREAD

**Issue by drsamadi** [IvS-KULeuven/PlatoSim3#933]
In the default YAML file, the trap densities at EOL take the following values:
[9.8, 3.31, 1.56, 13.24]    [traps/pixel]

These values come from table 3 in Prod’homme et al (2016)
They are associated with  a proton fluence of 1.3e10p+/ cm 2. According to Prod’homme et al, this proton fluence corresponds to about two times the estimated average PLATO end-of-life fluence.
Furthermore, officially  the "EOL"  is set to 4.5 years (see e.g. Bonner et al 2023?) whereas  in the YAML file the default EOL is set to 6.5 years.
Accordingly, both the default trap densities  and the default EOL limit are not consistent with the mission baslines.
Use of the current platosim default values tends to over-estimate the impact of the CTI.

One should set:
MissionDuration:                 4.5
and
TrapDensity:                                                        # For each trap species [traps/pixel]
                EOL:              [4.9  , 1.655, 0.78 , 6.62 ] 

Réza
ps:  PlatoSim 3.6.0-366-g986b3f5a

Attached:

-  Prod’homme et al (2016)
- Borner et al (2023)

[Borner_Noise_Paper_submitted.pdf](https://github.com/IvS-KULeuven/PlatoSim3/files/14063138/Borner_Noise_Paper_submitted.pdf)

[2016-prodhomme-spie.pdf](https://github.com/IvS-KULeuven/PlatoSim3/files/14063142/2016-prodhomme-spie.pdf)

**Comment by Dries-Seynaeve** [comment]
Thank you Réza, I changed these values in the default input file.
