### ISSUE TITLE
HDF5 Output lightcurve/flux clarification

### ISSUE THREAD

**Issue by AstroSaad** [IvS-KULeuven/PlatoSim3#940]
Hello all!

I'm currently looking to extract data from PlatoSim's HDF5 files for further processing and testing some software. The data I have was made from simulations run by Magali Deleuil.

I want to extract the light-curve data from an HDF5 file, however, looking through the file, there are three potential sets of data that could be used. Within the file's Photometry->Lightcurves->starID path, there is "estimatedFlux" and "inputFlux". Furthermore, in each of the Exposures in "StarPositions", there are "flux" values alongside the other parameters (colPix, rowxPix etc).

I wanted to know what the differences are between the three different sets of flux values and which set of values to use depending on my use cases.

**Comment by JorisDeRidder** [comment]
In `/Photometry/Lightcurves/starID` the `estimatedFlux` is the flux of the star as estimated from applying aperture photometry on the imagettes using the same method as will be used onboard the spacecraft. The `inputFlux` is the (possibly time-dependent) "true" flux of the star as was given as input by the user. The value `/StarPositions/Exposure???????/flux` is the same as the `inputFlux`, but is rather inconvenient if you want to extract a time series, hence we extracted the time series for you in `/Photometry/Lightcurves/starID/inputFlux`.

**Comment by AstroSaad** [comment]
Right I see. Thanks for the clarification
