### ISSUE TITLE
CTI input file missing

### ISSUE THREAD

**Issue by drsamadi** [IvS-KULeuven/PlatoSim3#941]
The use of the  option  named 'Short2013FromFile' requires to provide a  file that specifies the spatial variation of the trap densities (within a given CCD?). No  example file is provided, neither it is explained how this file shall be generated.

**Comment by JorisDeRidder** [comment]
Hi Réza, indeed we should document this better. Recall [our conversation in 2022](https://github.com/IvS-KULeuven/PlatoSim3/issues/639) about this topic. There is a python script included that generates such a file. One such HDF5 file is 160 MB, so it's difficult to attach it here. For your convenience, I just sent you (by email) a download link from WeTransfer (expiration date: Feb 8).
