### ISSUE TITLE
Output files - Flux Error

### ISSUE THREAD

**Issue by AstroSaad** [IvS-KULeuven/PlatoSim3#953]
Hello all

I had a question regarding flux errors produced by PlatoSim. I'm currently looking at different simulation output files produced by Magali Deleuil.

Reading in data from feather files, I can find a set of "flux_err" values.

When reading in data from HDF5 files, however, I can't find any flux error equivalent data. There are two sets of fluxes as mentioned in #940 .

Are the flux errors buried under some set of parameters within the HDF5 files that I'm missing?

Or are flux errors only produced when PlatoSim is run with the Lesia L1 pipeline? (which produces feather files as opposed to hdf5 files)

**Comment by Dries-Seynaeve** [comment]
Hello, 

Do you know what effect causes these error values? 
I don't believe PlatoSim produces error values in the subfield so my guess would be that these are added form theLesia L1 pipeline. 

Kind regards,
Dries

**Comment by nicholasjannsen** [comment]
Hi @AstroSaad , I think that you are confusing the output of PlatoSim and the PLATOnium setup coupled to the LESIA pipeline. PlatoSim do not provide flux errors, however, the LESIA pipeline does (which is only accessible through `platonium.py`). The HDF5 files are outputs of PlatoSim and the feather files (that includes flux errors) are using the LESIA setup. It looks like Magali didn't use the LESIA setup then.

**Comment by AstroSaad** [comment]
Ah right I see. Thanks for the clarification!
