### ISSUE TITLE
PlatoSim Dependency installation issue

### ISSUE THREAD

**Issue by AstroSaad** [IvS-KULeuven/PlatoSim3#963]
Hello all

I'm trying to install the develop branch of PlatoSim (I want to use the Platonium module) on a fresh linux environment. I get some errors at the end of the dependency installation stage. Would you be able to let me know what I need to or change?
```

collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/platosim.dir/build.make:98: platosim] Error 1
make[1]: *** [CMakeFiles/Makefile2:113: CMakeFiles/platosim.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

I'm attaching the output and error log txt files, as per the instructions on the PlatoSim website.
[output.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/14837618/output.txt)
[errors.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/14837620/errors.txt)

**Comment by AstroSaad** [comment]
There's another issue when I try to run `poetry install --with docs`

The pyqt5 package fails to install; I get a ChefBuildError message whenever I try to do so.

**Comment by JorisDeRidder** [comment]
Hi @AstroSaad, we usually recommend users not to build from source, but build using conda (cf the [installation instructions](https://ivs-kuleuven.github.io/PlatoSim3/install_conda.html) in the PlatoSim documentation pages) exactly to avoid issues like the one mentioned in the top post. Is there a particular reason why you would prefer to build from source?

Concerning your second post, the fact that PyQt5 does not install on your system seems to indicate that there are some components missing on your system, i.e. this does not seem to be a PlatoSim issue. Perhaps it's best to contact your local system administrator for this.

**Comment by AstroSaad** [comment]
I was under the (probably incorrect) impression that building from source would give me more control over the simulations. I want to be able to simulate different scenarios and I wanted the option of making my own modifications if that would be neccessary. 

I'll see what I can do about the missing components.

**Comment by JorisDeRidder** [comment]
Even when built with Conda, PlatoSim is fully configurable. Either through a YAML input configuration file when launching PlatoSim directly, or using the Python API of Platonium when launching via Python. There is no extra benefit when building from source.

**Comment by AstroSaad** [comment]
Alright. Thanks for letting me know!

**Comment by AstroSaad** [comment]
I'm following the instructions to install via conda.
I get an error on the `conda install -c https://<username>:<password>@jenkins.miricle.org/platosim.devel/ platosim` step.

```
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - platosim
```

I was given credentials last year in August. Are my credentials outdated or am I using the wrong command? Or is there something else that's causing this issue?

**Comment by nicholasjannsen** [comment]
@AstroSaad, concerning your second issue, which Python version are you using? I haven't tested if `poetry install` works for higher versions that Python 3.9.

Btw there is no need to add `--add docs`, since this is only used to install `sphinx` so we, as developers, can update the GitHub documentation page.

**Comment by nicholasjannsen** [comment]
Also, I recommend to install the Conda `main` branch, as this is stable whereas develop might not always be. Use the commands:
```
conda create -n platosim python=3.9
conda activate platosim
conda install -c https://plato:miSotalP@jenkins.miricle.org/platosim/ platosim
```
Next you can install the extra Python packages that are needed to run platonium:
```
cd </path/to/your/pyproject.toml>
poetry install --with platonium
```

**Comment by AstroSaad** [comment]
@nicholasjannsen I've followed your instructions but I'm still getting the same "PackagesNotFoundError" as before

**Comment by nicholasjannsen** [comment]
Okay, then it's the Jenkins build of the master branch that doesn't work. You use Mac correct @AstroSaad?  (@JorisDeRidder  since you are also using Mac, can you check if you can install the stable master branch from Jenkins?). Did the Poetry installation work fine for installing all the Python dependencies @AstroSaad?

**Comment by nicholasjannsen** [comment]
Note that the installation above works fine for Linux/Ubuntu.

**Comment by AstroSaad** [comment]
I've been trying to install on a Linux/Ubuntu system which is where I'm getting the error. I'm not currently trying to install on a Mac.
I don't think I can do the Poetry installation if PlatoSim doesn't install first right?

My platform is linux-aarch64 if that helps

**Comment by Dries-Seynaeve** [comment]
Hi Ahmed, 

Could you show us the output from the command: `conda list`, from within the conda environment?

Kind regards 
Dries

**Comment by AstroSaad** [comment]
[Condalist.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/15039244/Condalist.txt)
Here's the list

**Comment by AstroSaad** [comment]
I'm closing the issue as I was able to successfully install Platosim from the source with Dries' help.

For future referece, I'm working on an Mac with an M1 chip. It was not possible to install platosim via conda on this Mac.
