### ISSUE TITLE
The payload platonium script crashes without the --ted_ampl argument, which is marked as optional

### ISSUE THREAD

**Issue by ilyasku** [IvS-KULeuven/PlatoSim3#966]
I was trying to use the `payload` script. The examples in the documentation omit the `--ted_ampl` argument. But when I tried that, the script crashed due to `ampl` being `None` in one computation. 

The documentation says `ted_ampl` has a default value of 5 arcsec. This seems to be outdated. Adding `--ted_ampl 5` to my command fixes the problem and the script is running without errors.

I cloned the code yesterday using the default branch, it should be on commit `decf7cf3c994ba7555c9f4f6d2caacfb580a12d4`.

**Comment by nicholasjannsen** [comment]
Hi @ilyasku, did you git clone the  `develop` branch? Indeed there is a bug right now for `payload` on the develop branch that I need to fix before it will be merged into `main`.

**Comment by nicholasjannsen** [comment]
Note this a feature to overwrite a hard-coded value inside the script. On the main branch, this `ted_ampl` should be present yet.

**Comment by ilyasku** [comment]
Oh yes right, I did not pay attention and did not realize that the default branch is `develop`, and not a stable branch. Thanks for pointing it out!
Since you are already aware of the bug in `payload`, I will close the issue.
