### ISSUE TITLE
Non linearity parameters not within InputParameters group

### ISSUE THREAD

**Issue by manugr788** [IvS-KULeuven/PlatoSim3#973]
Hi,
I don't know if it's normal and if non linearity of the gain of the electronic chain has already been implemented in Platosim but in /PlatoSim3/inputfiles/inputfile.yaml file there is:
- CCD/Gain/Nonlinearity:                [0.0, -0.0042789409, 0.0000002365]
- CCD/IncludeGainNonlinearity:         yes  

but these attributes are not in the  InputParameters group of Hdf5 output file.

And this is an issue for us since we use those parameters from HDF5 output file to calibrate the non linearity correction of the on-ground pipeline.

PlatoSim 3.6.0-495-g96297b68

![non-linearity-platosim](https://github.com/IvS-KULeuven/PlatoSim3/assets/12544881/8ba0aca6-2940-44b0-9ffd-ca3bfeb5e868)

**Comment by JorisDeRidder** [comment]
Hi,
Thanks for reporting this. I just adapted the code to write the parameters that you requested to the HDF5 file, and pushed the changes to the develop branch. Let me know if this works for you.

**Comment by manugr788** [comment]
It works !
Thanks
