### ISSUE TITLE
StarPositions group and Images index inconsistent in case of high jitter. StarPositions/time dataset with gaps.

### ISSUE THREAD

**Issue by manugr788** [IvS-KULeuven/PlatoSim3#976]
Dear,

We have found that when the jitter is very high (as in the case of inertia wheel desaturation) the StarPositions group in the Platosim output file contains no data for the exposure.
This means that, for example, we obtain a greater number of exposures in the Images group than in the StarPositions group. This means that the exposure index in the StarPositions group no longer corresponds to the index in the Images group. 
Furthermore, in the "time" dataset of the StarPositions group, we have gaps in the data.
This is a little confusing and causes us problems, and we were wondering whether it wouldn't be possible for the exposure index in the StarPositions group to be in phase with that of the Images group, and for the "time" dataset to include all the times of the simulation, even when there is no dataset in the StarPositions group for a given exposure.

```python
import numpy as np
import h5py
f=h5py.File("000009080.hdf5","r")

len(f["StarPositions/time"])
17220
len(f["Images"])
17280


t = f["StarPositions/time"]
[t2 - t1 for t1, t2 in zip(t, t[1:])]
np.where([t2 - t1 > 25. for t1, t2 in zip(t, t[1:])])

(array([ 1473,  1474,  1480,  1484,  7428,  7429,  7430,  7431,  7434,
       13076, 13081]),)

t[1473:1480]
array([36843.75, 36893.75, 37218.75, 37243.75, 37268.75, 37293.75,
       37318.75])
```

**Jitter file**
![image](https://github.com/IvS-KULeuven/PlatoSim3/assets/12544881/611517e9-d0fc-4c53-9303-693391b0d669)

[S13i2draft_LOS_AOCS_TED_TimeSeries_7d_25s.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/15165822/S13i2draft_LOS_AOCS_TED_TimeSeries_7d_25s.txt)

**Comment by JorisDeRidder** [comment]
Hello, 
Thanks for reporting this. Could you provide us with the input yaml file and the star catalog that you used, so that we can try to reproduce this issue?

**Comment by manugr788** [comment]
Find here
https://zendto.obspm.fr/pickup?claimID=qdW78NoTKoBpnggH&claimPasscode=gnhP59KUtbEuTQJ8

Before run , change JitterFileName to [S13i2draft_LOS_AOCS_TED_TimeSeries_7d_25s.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/15165822/S13i2draft_LOS_AOCS_TED_TimeSeries_7d_25s.txt)

**Comment by Dries-Seynaeve** [comment]
This should be fixed now in the latest version. Please let me know if this works for you. 

Kind regards 
Dries

**Comment by Dries-Seynaeve** [comment]
I will close the issue for now, feel free to reopen the issue me know if this didn't work.
