### ISSUE TITLE
Streaking in Full Frame Images

### ISSUE THREAD

**Issue by bowl-sa** [IvS-KULeuven/PlatoSim3#993]
Hi,

I'm trying to generate a full frame image for a catalog of stars using the FCAMs, and I'm getting some strange streaking effects. Do you know what might be causing it?

I've attached an archive that contains a sample simulation and input files that exhibit streaking.
[fgs_ffi.zip](https://github.com/user-attachments/files/15740095/fgs_ffi.zip)

Thank you,
Samuel
![streaking](https://github.com/IvS-KULeuven/PlatoSim3/assets/148346259/92f604f9-5760-47fd-a384-bbddc2224d92)

**Comment by nicholasjannsen** [comment]
Hi Samuel, 

I had a look at your simulation and I have a few questions:
- Can you provide your input catalogue? The strikes are clearly from saturated stars, so I'm wondering what the stellar magnitude distribution you are using (are you simply following the documentation with a Gaia-LOPS1 FOV or it this just the LOPS1 FOV containing P1-P5 stars?)
- The simulation you provide contains only a very small subfield with a very bright saturated star. I don't see anything strange in your simulation. I can see that you have used `platonium.py` and not a custom script to create this simulation?
-   Note that from the latest develop branch, you can now use `platonium.py` to correctly simulate the F-CAM blue and red filter. The YAML file we provide do unfortunately not discriminate between the two filters, however, the script `platonium.py` does this automatically. E.g. in your simulation your are still using the same throughput as for the N-CAMs (e.g. QE is set to 0.6218, but is in fact closer to 0.8070 and 0.4923 for the blue and red filter, respectively).

To produce a single full-frame image using the "as required" mission values, you can simply run the `platonium.py` script for the blue and red F-CAM filter using:
```
platonium 1 5 1 1 --project <project_folder> -o <output_folder> --fullframe --performance required --seed 12345 --nexp 1
platonium 1 5 2 1 --project <project_folder> -o <output_folder> --fullframe --performance required --seed 12345 --nexp 1
```  
Here the 4 mandatory arguments are the CCD#, camera-group# (5 refers to the F-CAM), camera# (blue=1, red=2), and mission-quarter#.

**Comment by nicholasjannsen** [comment]
Note that we are in the process of moving away from having multiple YAML files for usage of the F-CAMs. If not using `platonium.py` which already uses the built-in python functionalities of PlatoSim, instead we recommend to use the python methods: `simulation.useNormalCamera()` and `simulation.useFastCamera()`. These two functions take the mission requirements as input argument and we will keep them updated with the "as required", "as expected" (i.e. as built), and "as simulated" from the mission data base.

**Comment by bowl-sa** [comment]
Hi Nicholas,

I'm using an internal catalogue developed by the PLATO Consortium, so I don't think I'm at liberty to share it. I am not currently using platonium, but I'll give it a try.

EDIT: I've got PLATOnium working. Is there a way to set it up to use a custom Star Catalog File and Variable Source List generated through PlatoSim?

Thank you,
Sam

**Comment by nicholasjannsen** [comment]
Hi Samuel, 

Using PlatoSim you already have access to the PIC 2.0 (we all have NDA as this is a requirement before you can use PlatoSim). 

The variable source list can be parsed using `--varlist <path/to/varSourceList.txt>`, where the file `varSourceList.txt` is the same format as mentioned on our PlatoSim documentation. 

The star catalogue is a bit specific to the output of `picsim` normally used in priori to `platonium`. I believe that you can simply transform your catalogue into a so-called feather file having at least the columns `PIC`, `mag`, `ra`, `dec`. You can use pandas to save a feather file (e.g. having a pandas data frame, use `df.to_feather('filename')`). The filename has to be of the form `starcat**targets.ftr`. I would recommend that you try to run e.g. `picsim --pic 100 P1 LOPS2 --project test` to create a custom PIC catalogue which you can use as a benchmark if you encounter any problems with the transformation of your own catalogue.

**Comment by bowl-sa** [comment]
Hi Nicholas,

I'm getting an error when I try to run the simulation with my catalogue. I've attached a screenshot of the error message below, as well as the catalogue I am using. This also happens when I use a custom PIC, but it works fine when I get a catalogue from Vizier. Do you know what might cause this?
![error](https://github.com/IvS-KULeuven/PlatoSim3/assets/148346259/5f6813b7-4280-4fe3-a3db-edf99bab862f)
[starcat_red_targets.zip](https://github.com/user-attachments/files/15838005/starcat_red_targets.zip)


Thank you,
Sam

**Comment by nicholasjannsen** [comment]
Hi Sam, 

below is some suggestions to push forward, but we may have a small call to solve this issue asap?

The input catalogue created by `picsim` when using either the `--pic` or `--vizier` arguments are very specific. That means that your catalogue most likely do not fit the format of either of these catalogues. I just had a look at your star catalogue files and I noticed that your RA and Dec coordinates are suspicious low. Are you using degree for both of these (that's mandatory by PlatoSim)?

In any case I found an easy work around for you: Given that you have a PLATOnium project folder called `red_sims`, then you can start by creating a fake stellar catalogue:
```
picsim --pic 10 P1 LOPS2 --project red_sims
```  
This will create a feather file containing some target and contaminant stars. Here we just want to keep the "*_contaminats.ftr" file as this one is expected by the internal structure of `platonium`. Now remove the feather file containing the targets and replace it by your own file that you attached here. Obviously we don't want to include any contaminants from the file we just created, but we can ignore any stellar contaminants in the simulation using the flag `--nocon`. Hence a simple call of platonium looks like:
```
platonium 1 1 1 1 --project red_sims --nocon -p
```
This worked for me on the latest version of the develop branch. Let me know how this works for you.

**Comment by bowl-sa** [comment]
Hi Nicholas,

Sorry for the late reply, I was out of town for Exoplanets 5 last week.

When I try to call platonium, I get 
`AttributeError: 'PLATOnium' object has no attribute 'numCon'`

Would there be a good time this week to organize a call? I am unavailable today, but I should be free every other day.

Thank you,
Sam

**Comment by nicholasjannsen** [comment]
Hi Sam, sorry this issue completely went over my head.. I just checked with the latest version of the develop branch (that is `git checkout 6759e0372b0a1e99959ec682ba02f482a404b197`), and here the two command above works fine for me. Can you tell me which version of PlatoSim you are using? 

Sorry for the inconvenience, it was probably just a typo-bug in the last version. In any case, if you like to have a call to get a bit more insight from the usage of PlatoSim/PLATOnium, just let me know and we can have a call later this week perhaps.

**Comment by nicholasjannsen** [comment]
Hi @bowl-sa, do you still need help on this issue?

**Comment by bowl-sa** [comment]
@nicholasjannsen No, I have it resolved. Thank you!
