### ISSUE TITLE
full-images/Non-Gaussian Analytical PSF: variation of the PSF across the FoV

### ISSUE THREAD

**Issue by drsamadi** [IvS-KULeuven/PlatoSim3#998]
Hi,
according to our understanding and the tests we did, when a full image is generated PLATOSim consider that the stars have all the same PSF and hence the variation in shape of the PSF is not taken into account; is this correct ?

This is a strong limitation for the development and test of the CPDS and L1 algorithms.
Indeed, a large part of the calibration is done on the basis of the full images, for instance the accurate calculation of the attitude and the calibration of the Image Geometry Model parameters (distortion, focal length and CCD parameters).
Once the attitude calculated and the IGM , they are used to compute aperture mask, star centroid, ....etc 
These quantities are then used to process the data acquired during the observation (on-boar light curves and imagettes).
The imagettes are generated with the PSF corresponding to the location of the imagettes in the focal plane whereas the full image ignore the variation of the PSF across of the focal plane.
Accordingly we process the imagettes (and also the on-board light) using calibration parameters which are not consist ; this for instance introduce error of about 1/10 on the calculated star centroid.

**Comment by JorisDeRidder** [comment]
Hi,
This depends on the PSF you select in the input yaml file. If you select for PSF model "AnalyticNonGaussian", then the PSF used depends on the coordinates of the focal plane. In a full image this therefore varies from star to star depending on the distance to the optical axis.

**Comment by drsamadi** [comment]
We are using "AnalyticNonGaussian"  but we are perhaps wrong concerning our diagnostic. 
We doing further tests, the inconsistency we have may come from our pipeline or tools.

**Comment by drsamadi** [comment]
Hi, after some checks we can now firmly confirms that the issue was coming from our side, sorry, accordingly I close the issue.
